
-- Manually increase the discount by $0.01 for a single discount so that the total price is equal to $0.99 instead of $1.00
UPDATE DISCOUNT SET FIXED_AMOUNT = 19.51 WHERE ID = (
        -- Discover the ID of the discount record associated with a single product in this tier of Bundle B
        SELECT MIN(DISCOUNT.ID)
        FROM DISCOUNT, DISCOUNT_PRODUCT_OFFERING, OFFER_PRODUCT_OFFERING, OFFER_OFFER_CHAIN
        WHERE DISCOUNT.ID = DISCOUNT_PRODUCT_OFFERING.DISCOUNT_ID
        AND DISCOUNT_PRODUCT_OFFERING.PRODUCT_OFFERING_ID = OFFER_PRODUCT_OFFERING.PRODUCT_OFFERING_ID
        AND OFFER_OFFER_CHAIN.OFFER_ID = OFFER_PRODUCT_OFFERING.OFFER_ID
        AND OFFER_OFFER_CHAIN.OFFER_CHAIN_ID = 2322411102
        AND OFFER_OFFER_CHAIN.INDEX_VALUE = 1
);
