WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
SET SCAN OFF
SET DEFINE OFF


DECLARE
  TMP_VAR NUMBER;
  CUR_PRD_ID NUMBER;
  CUR_CAPABILITY_ID NUMBER;
BEGIN
  BEGIN
    SELECT 1 INTO TMP_VAR FROM OFFER_CHAIN WHERE ID = 2691330666 AND ROWNUM <= 1;
    UPDATE OFFER_CHAIN SET NAME='NYTimes: Web + Tablet App for Kindle eReader subscribers', DESCRIPTION='Unlimited access to NYTimes.com and the NYTimes tablet app for Amazon Kindle eReader subscribers.*', PRODUCT_URI='', VENDOR_SOURCE_ID='1', BILLING_SOURCE_ID=(SELECT ID FROM BILLING_SOURCE BS WHERE BS.NAME='Amazon'), IS_SEAT_LICENSE=0, GROUP_ACCOUNT_TYPE_ID='NO',IS_ADDRESS_REQUIRED=0, OFFER_CHAIN_STATUS_ID = 1, UPDATE_DATE = SYSDATE, UPDATED_BY = 'OFFERMAKER', IS_GIFT_CERTIFICATE='0', REVOKE_ENTITLEMENTS = '0', ADOPTABILITY_WINDOW_START_DATE = to_date('04-Apr-2013 00:00:00','DD-MON-YY HH24:MI:SS'), ADOPTABILITY_WINDOW_END_DATE = to_date('01-Jan-2100 00:00:00','DD-MON-YY HH24:MI:SS'), AMAZON_APPSTORE_SKU=NULL WHERE ID = 2691330666;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      INSERT INTO OFFER_CHAIN (ID, NAME, DESCRIPTION, ADOPTABILITY_WINDOW_START_DATE, ADOPTABILITY_WINDOW_END_DATE, IS_GIFT_CERTIFICATE, PRODUCT_URI, OFFER_CHAIN_STATUS_ID, REVOKE_ENTITLEMENTS, VENDOR_SOURCE_ID, BILLING_SOURCE_ID, IS_SEAT_LICENSE, GROUP_ACCOUNT_TYPE_ID, IS_ADDRESS_REQUIRED, AMAZON_APPSTORE_SKU, CREATED_BY, CREATE_DATE, updated_by, update_date) VALUES (2691330666, 'NYTimes: Web + Tablet App for Kindle eReader subscribers', 'Unlimited access to NYTimes.com and the NYTimes tablet app for Amazon Kindle eReader subscribers.*', to_date('04-Apr-2013 00:00:00','DD-MON-YY HH24:MI:SS'), to_date('01-Jan-2100 00:00:00','DD-MON-YY HH24:MI:SS'), '0', NULL, '1', '0', '1', (SELECT ID FROM BILLING_SOURCE BS WHERE BS.NAME='Amazon'), decode('NO','IL',1,0), 'NO', '0', '', 'OFFERMAKER', SYSDATE, 'OFFERMAKER', SYSDATE);
  END;
  DELETE FROM OFFER_CHAIN_ELIGIBILITY WHERE offer_chain_id = 2691330666;
  INSERT INTO OFFER_CHAIN_ELIGIBILITY (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (ELG_ID_SEQ.NEXTVAL, 2691330666, 'IS_COMP', '0', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_ELIGIBILITY (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (ELG_ID_SEQ.NEXTVAL, 2691330666, 'MAX_CONCURRENT_SUBS', 'UNLIMITED', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_ELIGIBILITY (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (ELG_ID_SEQ.NEXTVAL, 2691330666, 'INTERNAL_ONLY', '0', 'OFFERMAKER', SYSDATE);
  DELETE FROM OFFER_CHAIN_META_DATA WHERE offer_chain_id = 2691330666;
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 2691330666, 'BUNDLE_EXPLANATION', 'W+T (for Amazon Kindle eReaders)', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 2691330666, 'PRICE_DESCRIPTION', 'For Amazon Kindle eReader only subscribers to get free Web +Tablet only access', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 2691330666, 'PRICE_SHORT_DESCRIPTION', 'Amazon eReaders Bundle B', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 2691330666, 'OFFER_TYPE', 'Complimentary', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 2691330666, 'PROMO_PRICE_FOOTER_LABEL', 'Billing Cycle', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 2691330666, 'BILLING_CYCLE', 'monthly', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 2691330666, 'SUBSCRIBER_TYPE', 'Kindle', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 2691330666, 'REFUND_POLICY', 'Monthly Billing: No refund.  Users will maintain access for the remainder of the billing period.  Users will not be billed in the next billing cycle.', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 2691330666, 'BUNDLE', 'Bundle B (Web+Tab)', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 2691330666, 'ADX_BUNDLE', 'MM_PROMO', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 2691330666, 'SIEBEL_CAMPAIGN_CODE', '3887K', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 2691330666, 'UID', '1aa5e1320bcdd0a5c39ab58b592b161df1c568fb1e4dbfc76afbc6faa97e71d0', 'OFFERMAKER', SYSDATE);
  DELETE FROM OFFER_CHAIN_NOTIFICATION_TYPE WHERE offer_chain_id = 2691330666;
  BEGIN
    SELECT 1 INTO TMP_VAR FROM OFFER_OFFER_CHAIN WHERE OFFER_CHAIN_ID = 2691330666 AND INDEX_VALUE = 0 AND ROWNUM <= 1;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
  INSERT INTO OFFER (ID, OFFER_STATUS_ID, ENTITLEMENT_DURATION, CREATED_BY, CREATE_DATE, updated_by, update_date) VALUES (OFR_ID_SEQ.NEXTVAL, 1, 'P0Y0M980DT0H0M', 'OFFERMAKER', SYSDATE, 'OFFERMAKER', SYSDATE);
  BEGIN
    SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Web' AND PRODUCT_STATUS_ID = 1 AND ROWNUM <= 1;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      INSERT INTO PRODUCT (ID, NAME, PRODUCTION_COST, PRODUCT_STATUS_ID, PRODUCT_URI, UNIT_PRICE, CREATED_BY, CREATE_DATE) VALUES (PRD_ID_SEQ.NEXTVAL, 'Web', '0', 1, NULL, '0', 'OFFERMAKER', SYSDATE);
      SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Web' AND PRODUCT_STATUS_ID = 1 AND ROWNUM <= 1;
    WHEN OTHERS THEN
      RAISE;
  END;
  SELECT ID INTO CUR_CAPABILITY_ID FROM CAPABILITY WHERE CODE IN LTRIM(RTRIM((UPPER('MM')))) AND ROWNUM <= 1;
  INSERT INTO PRODUCT_OFFERING (ID, PRODUCT_ID, TAX_POLICY_TYPE_ID, QUANTITY, UNIT_PRICE, TAX_CATEGORY_ID, CAPABILITY_ID, CREATED_BY, CREATE_DATE) VALUES (PO_ID_SEQ.NEXTVAL, CUR_PRD_ID, '1', '980', '0', '2', CUR_CAPABILITY_ID, 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'entitlement_uri', 'http://:hostname:/svc/user/entitlements/mm/:id:.json', 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'DEFAULT_VAT_RATE', '{"*": }', 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'capability', 'MM', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_PRODUCT_OFFERING (OFFER_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (OFR_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
  BEGIN
    SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Mobile' AND PRODUCT_STATUS_ID = 1 AND ROWNUM <= 1;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      INSERT INTO PRODUCT (ID, NAME, PRODUCTION_COST, PRODUCT_STATUS_ID, PRODUCT_URI, UNIT_PRICE, CREATED_BY, CREATE_DATE) VALUES (PRD_ID_SEQ.NEXTVAL, 'Mobile', '0', 1, NULL, '0', 'OFFERMAKER', SYSDATE);
      SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Mobile' AND PRODUCT_STATUS_ID = 1 AND ROWNUM <= 1;
    WHEN OTHERS THEN
      RAISE;
  END;
  SELECT ID INTO CUR_CAPABILITY_ID FROM CAPABILITY WHERE CODE IN LTRIM(RTRIM((UPPER('MOW')))) AND ROWNUM <= 1;
  INSERT INTO PRODUCT_OFFERING (ID, PRODUCT_ID, TAX_POLICY_TYPE_ID, QUANTITY, UNIT_PRICE, TAX_CATEGORY_ID, CAPABILITY_ID, CREATED_BY, CREATE_DATE) VALUES (PO_ID_SEQ.NEXTVAL, CUR_PRD_ID, '1', '980', '0', '2', CUR_CAPABILITY_ID, 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'entitlement_uri', 'http://:hostname:/svc/user/entitlements/mow/:id:.json', 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'DEFAULT_VAT_RATE', '{"*": }', 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'capability', 'MOW', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_PRODUCT_OFFERING (OFFER_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (OFR_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
  BEGIN
    SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Archive Article' AND PRODUCT_STATUS_ID = 1 AND ROWNUM <= 1;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      INSERT INTO PRODUCT (ID, NAME, PRODUCTION_COST, PRODUCT_STATUS_ID, PRODUCT_URI, UNIT_PRICE, CREATED_BY, CREATE_DATE) VALUES (PRD_ID_SEQ.NEXTVAL, 'Archive Article', '0', 1, NULL, '0', 'OFFERMAKER', SYSDATE);
      SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Archive Article' AND PRODUCT_STATUS_ID = 1 AND ROWNUM <= 1;
    WHEN OTHERS THEN
      RAISE;
  END;
  SELECT ID INTO CUR_CAPABILITY_ID FROM CAPABILITY WHERE CODE IN LTRIM(RTRIM((UPPER('AAA')))) AND ROWNUM <= 1;
  INSERT INTO PRODUCT_OFFERING (ID, PRODUCT_ID, TAX_POLICY_TYPE_ID, QUANTITY, UNIT_PRICE, TAX_CATEGORY_ID, CAPABILITY_ID, CREATED_BY, CREATE_DATE) VALUES (PO_ID_SEQ.NEXTVAL, CUR_PRD_ID, '1', '3500', '0', '2', CUR_CAPABILITY_ID, 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'entitlement_uri', 'http://:hostname:/svc/user/entitlements/archive/size/3500/:id:.json', 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'DEFAULT_VAT_RATE', '{"*": }', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_PRODUCT_OFFERING (OFFER_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (OFR_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
  BEGIN
    SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'TimesMachine' AND PRODUCT_STATUS_ID = 1 AND ROWNUM <= 1;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      INSERT INTO PRODUCT (ID, NAME, PRODUCTION_COST, PRODUCT_STATUS_ID, PRODUCT_URI, UNIT_PRICE, CREATED_BY, CREATE_DATE) VALUES (PRD_ID_SEQ.NEXTVAL, 'TimesMachine', '0', 1, NULL, '0', 'OFFERMAKER', SYSDATE);
      SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'TimesMachine' AND PRODUCT_STATUS_ID = 1 AND ROWNUM <= 1;
    WHEN OTHERS THEN
      RAISE;
  END;
  SELECT ID INTO CUR_CAPABILITY_ID FROM CAPABILITY WHERE CODE IN LTRIM(RTRIM((UPPER('NONE')))) AND ROWNUM <= 1;
  INSERT INTO PRODUCT_OFFERING (ID, PRODUCT_ID, TAX_POLICY_TYPE_ID, QUANTITY, UNIT_PRICE, TAX_CATEGORY_ID, CAPABILITY_ID, CREATED_BY, CREATE_DATE) VALUES (PO_ID_SEQ.NEXTVAL, CUR_PRD_ID, '1', '980', '0', '2', CUR_CAPABILITY_ID, 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'DEFAULT_VAT_RATE', '{"*": }', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_PRODUCT_OFFERING (OFFER_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (OFR_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
  BEGIN
    SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Tablet' AND PRODUCT_STATUS_ID = 1 AND ROWNUM <= 1;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      INSERT INTO PRODUCT (ID, NAME, PRODUCTION_COST, PRODUCT_STATUS_ID, PRODUCT_URI, UNIT_PRICE, CREATED_BY, CREATE_DATE) VALUES (PRD_ID_SEQ.NEXTVAL, 'Tablet', '0', 1, NULL, '0', 'OFFERMAKER', SYSDATE);
      SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Tablet' AND PRODUCT_STATUS_ID = 1 AND ROWNUM <= 1;
    WHEN OTHERS THEN
      RAISE;
  END;
  SELECT ID INTO CUR_CAPABILITY_ID FROM CAPABILITY WHERE CODE IN LTRIM(RTRIM((UPPER('MTD')))) AND ROWNUM <= 1;
  INSERT INTO PRODUCT_OFFERING (ID, PRODUCT_ID, TAX_POLICY_TYPE_ID, QUANTITY, UNIT_PRICE, TAX_CATEGORY_ID, CAPABILITY_ID, CREATED_BY, CREATE_DATE) VALUES (PO_ID_SEQ.NEXTVAL, CUR_PRD_ID, '1', '980', '0', '2', CUR_CAPABILITY_ID, 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'entitlement_uri', 'http://:hostname:/svc/user/entitlements/mtd/:id:.json', 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'DEFAULT_VAT_RATE', '{"*": }', 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'capability', 'MTD', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_PRODUCT_OFFERING (OFFER_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (OFR_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
  BEGIN
    SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'TimesReader' AND PRODUCT_STATUS_ID = 1 AND ROWNUM <= 1;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      INSERT INTO PRODUCT (ID, NAME, PRODUCTION_COST, PRODUCT_STATUS_ID, PRODUCT_URI, UNIT_PRICE, CREATED_BY, CREATE_DATE) VALUES (PRD_ID_SEQ.NEXTVAL, 'TimesReader', '0', 1, NULL, '0', 'OFFERMAKER', SYSDATE);
      SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'TimesReader' AND PRODUCT_STATUS_ID = 1 AND ROWNUM <= 1;
    WHEN OTHERS THEN
      RAISE;
  END;
  SELECT ID INTO CUR_CAPABILITY_ID FROM CAPABILITY WHERE CODE IN LTRIM(RTRIM((UPPER('TNR')))) AND ROWNUM <= 1;
  INSERT INTO PRODUCT_OFFERING (ID, PRODUCT_ID, TAX_POLICY_TYPE_ID, QUANTITY, UNIT_PRICE, TAX_CATEGORY_ID, CAPABILITY_ID, CREATED_BY, CREATE_DATE) VALUES (PO_ID_SEQ.NEXTVAL, CUR_PRD_ID, '1', '980', '0', '2', CUR_CAPABILITY_ID, 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'entitlement_uri', 'http://:hostname:/svc/user/entitlements/timesreader/:id:.json', 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'capability', 'TNR', 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'DEFAULT_VAT_RATE', '{"*": }', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_PRODUCT_OFFERING (OFFER_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (OFR_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_OFFER_CHAIN (OFFER_ID, OFFER_CHAIN_ID, INDEX_VALUE, NUM_RECURRENCES, CREATED_BY, CREATE_DATE, updated_by, update_date) VALUES (OFR_ID_SEQ.CURRVAL, 2691330666, '0', '-1', 'OFFERMAKER', SYSDATE, 'OFFERMAKER', SYSDATE);
  END;
END;
/

COMMIT;

