WHENEVER SQLERROR EXIT ROLLBACK;

variable is_current_version_fine NUMBER;
variable change_version NUMBER;
variable bad_current_version VARCHAR2(1024);

exec :change_version := 28;
exec PROCS_SYSTEM_V17.CHECK_VERSION(:change_version - 1, :is_current_version_fine);
exec :bad_current_version := 'Current version is bad, please update your version to '||(:change_version-1);

BEGIN
  IF (:is_current_version_fine != 0) THEN
    RAISE_APPLICATION_ERROR(-20001, :bad_current_version);
  END IF;
END;
/

CREATE SEQUENCE AAS_HISTORY_ID_SEQ;
CREATE TABLE CORE_HIST_OWNER.AMAZON_APPSTORE_HISTORY (
  ID NUMBER NOT NULL,
  AMAZON_APPSTORE_ID NUMBER NOT NULL,
  SUBSCRIPTION_ID NUMBER NOT NULL,
  USER_ID VARCHAR2(4000) NOT NULL,
  ITEM_TYPE VARCHAR2(50) NOT NULL,
  START_DATE DATE NOT NULL,
  END_DATE DATE NULL,
  SKU VARCHAR2(4000) NOT NULL,
  PURCHASE_TOKEN VARCHAR2(4000) NOT NULL,
  AMAZON_APPSTORE_CREATE_DATE DATE NOT NULL,
  AMAZON_APPSTORE_CREATED_BY VARCHAR2(255) NOT NULL,
  AMAZON_APPSTORE_UPDATE_DATE DATE NOT NULL,
  AMAZON_APPSTORE_UPDATED_BY VARCHAR2(255) NOT NULL,
  CREATE_DATE DATE NOT NULL,
  CREATED_BY VARCHAR2(255) NOT NULL,
  UPDATE_DATE DATE NOT NULL,
  UPDATED_BY VARCHAR2(255) NOT NULL,
  SYSTEM_ACTIVITY_REASON_ID NUMBER NOT NULL,
  CONSTRAINT AAP_HISTORY_PK PRIMARY KEY (ID) USING INDEX TABLESPACE CORE_HIST_IDX
) TABLESPACE CORE_HIST;
COMMENT ON TABLE CORE_HIST_OWNER.AMAZON_APPSTORE_HISTORY  IS 'This is the history table for CORE_OWNER.AMAZON_APPSTORE';
CREATE INDEX CORE_HIST_OWNER.AMAZON_APPSTORE_HISTORY ON CORE_HIST_OWNER.AMAZON_APPSTORE_HISTORY (AMAZON_APPSTORE_ID) TABLESPACE CORE_HIST_IDX;

exec PROCS_SYSTEM_V17.INCREMENT_VERSION();
