WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
SET SCAN OFF
SET DEFINE OFF


DECLARE
  TMP_VAR NUMBER;
  CUR_PRD_ID NUMBER;
  CUR_CAPABILITY_ID NUMBER;
BEGIN
  BEGIN
    SELECT 1 INTO TMP_VAR FROM OFFER_CHAIN WHERE ID = 1203650 AND ROWNUM <= 1;
    UPDATE OFFER_CHAIN SET NAME='NYTimes: Web + Smartphone App', DESCRIPTION='Unlimited access to NYTimes.com and the NYTimes smartphone app.*', PRODUCT_URI='', VENDOR_SOURCE_ID='1', BILLING_SOURCE_ID=(SELECT ID FROM BILLING_SOURCE BS WHERE BS.NAME='Sartre'), IS_SEAT_LICENSE=0, GROUP_ACCOUNT_TYPE_ID='NO',IS_ADDRESS_REQUIRED=0, OFFER_CHAIN_STATUS_ID = 1, UPDATE_DATE = SYSDATE, UPDATED_BY = 'OFFERMAKER', IS_GIFT_CERTIFICATE='1', REVOKE_ENTITLEMENTS = '0', ADOPTABILITY_WINDOW_START_DATE = to_date('09-Mar-2012 00:00:00','DD-MON-YY HH24:MI:SS'), ADOPTABILITY_WINDOW_END_DATE = to_date('15-Jul-2013 00:00:00','DD-MON-YY HH24:MI:SS') WHERE ID = 1203650;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      INSERT INTO OFFER_CHAIN (ID, NAME, DESCRIPTION, ADOPTABILITY_WINDOW_START_DATE, ADOPTABILITY_WINDOW_END_DATE, IS_GIFT_CERTIFICATE, PRODUCT_URI, OFFER_CHAIN_STATUS_ID, REVOKE_ENTITLEMENTS, VENDOR_SOURCE_ID, BILLING_SOURCE_ID, IS_SEAT_LICENSE, GROUP_ACCOUNT_TYPE_ID, IS_ADDRESS_REQUIRED, CREATED_BY, CREATE_DATE, updated_by, update_date) VALUES (1203650, 'NYTimes: Web + Smartphone App', 'Unlimited access to NYTimes.com and the NYTimes smartphone app.*', to_date('09-Mar-2012 00:00:00','DD-MON-YY HH24:MI:SS'), to_date('15-Jul-2013 00:00:00','DD-MON-YY HH24:MI:SS'), '1', NULL, '1', '0', '1', (SELECT ID FROM BILLING_SOURCE BS WHERE BS.NAME='Sartre'), decode('NO','IL',1,0), 'NO', '0', 'OFFERMAKER', SYSDATE, 'OFFERMAKER', SYSDATE);
  END;
  DELETE FROM OFFER_CHAIN_ELIGIBILITY WHERE offer_chain_id = 1203650;
  INSERT INTO OFFER_CHAIN_ELIGIBILITY (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (ELG_ID_SEQ.NEXTVAL, 1203650, 'IS_COMP', '1', 'OFFERMAKER', SYSDATE);
  DELETE FROM OFFER_CHAIN_META_DATA WHERE offer_chain_id = 1203650;
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1203650, 'BUNDLE_EXPLANATION', 'Bundle A - Anniversary Free 12 Week Comp Sub - Generation OC', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1203650, 'PRICE_DESCRIPTION', '12 Week Anniversary Free Comp Sub Promotion Subscription - Comp Code Generation', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1203650, 'PRICE_SHORT_DESCRIPTION', 'BNDL A / $0 12 wks Anniversary Free Comp Sub - GC purch', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1203650, 'OFFER_TYPE', 'Complimentary', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1203650, 'BILLING_CYCLE', '12 Week subscription', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1203650, 'SUBSCRIBER_TYPE', 'Complimentary - Anniversary', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1203650, 'redemption offer chain id', '1203651, 1203652', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1203650, 'BUNDLE', 'Bundle A (Web+SP)', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1203650, 'ADX_BUNDLE', 'MM_PROMO', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1203650, 'SIEBEL_CAMPAIGN_CODE', '39QYU', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1203650, 'IS_COMP', '1', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1203650, 'ANNUAL_PRICE', '0.00', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1203650, 'UID', '0ce48d8d9b3df2dd8565f965f56ceae0d031f1174e2bbe14d4165cd6a057ee5e', 'OFFERMAKER', SYSDATE);
  DELETE FROM OFFER_CHAIN_NOTIFICATION_TYPE WHERE offer_chain_id = 1203650;
  BEGIN
    SELECT 1 INTO TMP_VAR FROM OFFER_OFFER_CHAIN WHERE OFFER_CHAIN_ID = 1203650 AND INDEX_VALUE = 0 AND ROWNUM <= 1;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
  INSERT INTO OFFER (ID, OFFER_STATUS_ID, ENTITLEMENT_DURATION, CREATED_BY, CREATE_DATE, updated_by, update_date) VALUES (OFR_ID_SEQ.NEXTVAL, 1, 'P0Y0M84DT0H0M', 'OFFERMAKER', SYSDATE, 'OFFERMAKER', SYSDATE);
  BEGIN
    SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Web' AND PRODUCT_STATUS_ID = 1 AND ROWNUM <= 1;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      INSERT INTO PRODUCT (ID, NAME, PRODUCTION_COST, PRODUCT_STATUS_ID, PRODUCT_URI, UNIT_PRICE, CREATED_BY, CREATE_DATE) VALUES (PRD_ID_SEQ.NEXTVAL, 'Web', '0', 1, NULL, '0.357143', 'OFFERMAKER', SYSDATE);
      SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Web' AND PRODUCT_STATUS_ID = 1 AND ROWNUM <= 1;
    WHEN OTHERS THEN
      RAISE;
  END;
  SELECT ID INTO CUR_CAPABILITY_ID FROM CAPABILITY WHERE CODE IN LTRIM(RTRIM((UPPER('MM')))) AND ROWNUM <= 1;
  INSERT INTO PRODUCT_OFFERING (ID, PRODUCT_ID, TAX_POLICY_TYPE_ID, QUANTITY, UNIT_PRICE, TAX_CATEGORY_ID, CAPABILITY_ID, CREATED_BY, CREATE_DATE) VALUES (PO_ID_SEQ.NEXTVAL, CUR_PRD_ID, '1', '84', '0.357143', '2', CUR_CAPABILITY_ID, 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'entitlement_uri', 'http://:hostname:/svc/user/entitlements/mm/:id:.json', 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'DEFAULT_VAT_RATE', '{"*": 0.0}', 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'capability', 'MM', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_PRODUCT_OFFERING (OFFER_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (OFR_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
  INSERT INTO DISCOUNT (ID, NAME, DESCRIPTION, FIXED_AMOUNT, PERCENT_AMOUNT, DISCOUNT_TYPE_ID, CREATED_BY, CREATE_DATE) VALUES (DSC_ID_SEQ.NEXTVAL, 'Discount', 'Target offer price 0.0 given offer total price 44.999976 and product price 30.000012', '30.000012', '0', 1, 'OFFERMAKER', SYSDATE);
  INSERT INTO DISCOUNT_PRODUCT_OFFERING (DISCOUNT_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (DSC_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
  BEGIN
    SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Mobile' AND PRODUCT_STATUS_ID = 1 AND ROWNUM <= 1;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      INSERT INTO PRODUCT (ID, NAME, PRODUCTION_COST, PRODUCT_STATUS_ID, PRODUCT_URI, UNIT_PRICE, CREATED_BY, CREATE_DATE) VALUES (PRD_ID_SEQ.NEXTVAL, 'Mobile', '0', 1, NULL, '0', 'OFFERMAKER', SYSDATE);
      SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Mobile' AND PRODUCT_STATUS_ID = 1 AND ROWNUM <= 1;
    WHEN OTHERS THEN
      RAISE;
  END;
  SELECT ID INTO CUR_CAPABILITY_ID FROM CAPABILITY WHERE CODE IN LTRIM(RTRIM((UPPER('MOW')))) AND ROWNUM <= 1;
  INSERT INTO PRODUCT_OFFERING (ID, PRODUCT_ID, TAX_POLICY_TYPE_ID, QUANTITY, UNIT_PRICE, TAX_CATEGORY_ID, CAPABILITY_ID, CREATED_BY, CREATE_DATE) VALUES (PO_ID_SEQ.NEXTVAL, CUR_PRD_ID, '1', '84', '0', '2', CUR_CAPABILITY_ID, 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'entitlement_uri', 'http://:hostname:/svc/user/entitlements/mow/:id:.json', 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'DEFAULT_VAT_RATE', '{"*": 0.0}', 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'capability', 'MOW', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_PRODUCT_OFFERING (OFFER_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (OFR_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
  BEGIN
    SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Archive Article' AND PRODUCT_STATUS_ID = 1 AND ROWNUM <= 1;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      INSERT INTO PRODUCT (ID, NAME, PRODUCTION_COST, PRODUCT_STATUS_ID, PRODUCT_URI, UNIT_PRICE, CREATED_BY, CREATE_DATE) VALUES (PRD_ID_SEQ.NEXTVAL, 'Archive Article', '0', 1, NULL, '0', 'OFFERMAKER', SYSDATE);
      SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Archive Article' AND PRODUCT_STATUS_ID = 1 AND ROWNUM <= 1;
    WHEN OTHERS THEN
      RAISE;
  END;
  SELECT ID INTO CUR_CAPABILITY_ID FROM CAPABILITY WHERE CODE IN LTRIM(RTRIM((UPPER('AAA')))) AND ROWNUM <= 1;
  INSERT INTO PRODUCT_OFFERING (ID, PRODUCT_ID, TAX_POLICY_TYPE_ID, QUANTITY, UNIT_PRICE, TAX_CATEGORY_ID, CAPABILITY_ID, CREATED_BY, CREATE_DATE) VALUES (PO_ID_SEQ.NEXTVAL, CUR_PRD_ID, '1', '300', '0', '2', CUR_CAPABILITY_ID, 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'entitlement_uri', 'http://:hostname:/svc/user/entitlements/archive/size/300/:id:.json', 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'DEFAULT_VAT_RATE', '{"*": 0.0}', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_PRODUCT_OFFERING (OFFER_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (OFR_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
  BEGIN
    SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'TimesMachine' AND PRODUCT_STATUS_ID = 1 AND ROWNUM <= 1;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      INSERT INTO PRODUCT (ID, NAME, PRODUCTION_COST, PRODUCT_STATUS_ID, PRODUCT_URI, UNIT_PRICE, CREATED_BY, CREATE_DATE) VALUES (PRD_ID_SEQ.NEXTVAL, 'TimesMachine', '0', 1, NULL, '0', 'OFFERMAKER', SYSDATE);
      SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'TimesMachine' AND PRODUCT_STATUS_ID = 1 AND ROWNUM <= 1;
    WHEN OTHERS THEN
      RAISE;
  END;
  SELECT ID INTO CUR_CAPABILITY_ID FROM CAPABILITY WHERE CODE IN LTRIM(RTRIM((UPPER('NONE')))) AND ROWNUM <= 1;
  INSERT INTO PRODUCT_OFFERING (ID, PRODUCT_ID, TAX_POLICY_TYPE_ID, QUANTITY, UNIT_PRICE, TAX_CATEGORY_ID, CAPABILITY_ID, CREATED_BY, CREATE_DATE) VALUES (PO_ID_SEQ.NEXTVAL, CUR_PRD_ID, '1', '84', '0', '2', CUR_CAPABILITY_ID, 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'DEFAULT_VAT_RATE', '{"*": 0.0}', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_PRODUCT_OFFERING (OFFER_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (OFR_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
  BEGIN
    SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Smartphone' AND PRODUCT_STATUS_ID = 1 AND ROWNUM <= 1;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      INSERT INTO PRODUCT (ID, NAME, PRODUCTION_COST, PRODUCT_STATUS_ID, PRODUCT_URI, UNIT_PRICE, CREATED_BY, CREATE_DATE) VALUES (PRD_ID_SEQ.NEXTVAL, 'Smartphone', '0', 1, NULL, '0.178571', 'OFFERMAKER', SYSDATE);
      SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Smartphone' AND PRODUCT_STATUS_ID = 1 AND ROWNUM <= 1;
    WHEN OTHERS THEN
      RAISE;
  END;
  SELECT ID INTO CUR_CAPABILITY_ID FROM CAPABILITY WHERE CODE IN LTRIM(RTRIM((UPPER('MSD')))) AND ROWNUM <= 1;
  INSERT INTO PRODUCT_OFFERING (ID, PRODUCT_ID, TAX_POLICY_TYPE_ID, QUANTITY, UNIT_PRICE, TAX_CATEGORY_ID, CAPABILITY_ID, CREATED_BY, CREATE_DATE) VALUES (PO_ID_SEQ.NEXTVAL, CUR_PRD_ID, '1', '84', '0.178571', '2', CUR_CAPABILITY_ID, 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'entitlement_uri', 'http://:hostname:/svc/user/entitlements/msd/:id:.json', 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'DEFAULT_VAT_RATE', '{"*": 0.0}', 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'capability', 'MSD', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_PRODUCT_OFFERING (OFFER_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (OFR_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
  INSERT INTO DISCOUNT (ID, NAME, DESCRIPTION, FIXED_AMOUNT, PERCENT_AMOUNT, DISCOUNT_TYPE_ID, CREATED_BY, CREATE_DATE) VALUES (DSC_ID_SEQ.NEXTVAL, 'Discount', 'Target offer price 0.0 given offer total price 44.999976 and product price 14.999964', '14.999964', '0', 1, 'OFFERMAKER', SYSDATE);
  INSERT INTO DISCOUNT_PRODUCT_OFFERING (DISCOUNT_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (DSC_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_OFFER_CHAIN (OFFER_ID, OFFER_CHAIN_ID, INDEX_VALUE, NUM_RECURRENCES, CREATED_BY, CREATE_DATE, updated_by, update_date) VALUES (OFR_ID_SEQ.CURRVAL, 1203650, '0', '1', 'OFFERMAKER', SYSDATE, 'OFFERMAKER', SYSDATE);
  END;
END;
/

DECLARE
  TMP_VAR NUMBER;
  CUR_PRD_ID NUMBER;
  CUR_CAPABILITY_ID NUMBER;
BEGIN
  BEGIN
    SELECT 1 INTO TMP_VAR FROM OFFER_CHAIN WHERE ID = 1203651 AND ROWNUM <= 1;
    UPDATE OFFER_CHAIN SET NAME='NYTimes: Web + Smartphone App', DESCRIPTION='Unlimited access to NYTimes.com and the NYTimes smartphone app.', PRODUCT_URI='', VENDOR_SOURCE_ID='1', BILLING_SOURCE_ID=(SELECT ID FROM BILLING_SOURCE BS WHERE BS.NAME='Sartre'), IS_SEAT_LICENSE=0, GROUP_ACCOUNT_TYPE_ID='NO',IS_ADDRESS_REQUIRED=0, OFFER_CHAIN_STATUS_ID = 1, UPDATE_DATE = SYSDATE, UPDATED_BY = 'OFFERMAKER', IS_GIFT_CERTIFICATE='0', REVOKE_ENTITLEMENTS = '0', ADOPTABILITY_WINDOW_START_DATE = to_date('09-Mar-2012 00:00:00','DD-MON-YY HH24:MI:SS'), ADOPTABILITY_WINDOW_END_DATE = to_date('15-Jul-2013 00:00:00','DD-MON-YY HH24:MI:SS') WHERE ID = 1203651;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      INSERT INTO OFFER_CHAIN (ID, NAME, DESCRIPTION, ADOPTABILITY_WINDOW_START_DATE, ADOPTABILITY_WINDOW_END_DATE, IS_GIFT_CERTIFICATE, PRODUCT_URI, OFFER_CHAIN_STATUS_ID, REVOKE_ENTITLEMENTS, VENDOR_SOURCE_ID, BILLING_SOURCE_ID, IS_SEAT_LICENSE, GROUP_ACCOUNT_TYPE_ID, IS_ADDRESS_REQUIRED, CREATED_BY, CREATE_DATE, updated_by, update_date) VALUES (1203651, 'NYTimes: Web + Smartphone App', 'Unlimited access to NYTimes.com and the NYTimes smartphone app.', to_date('09-Mar-2012 00:00:00','DD-MON-YY HH24:MI:SS'), to_date('15-Jul-2013 00:00:00','DD-MON-YY HH24:MI:SS'), '0', NULL, '1', '0', '1', (SELECT ID FROM BILLING_SOURCE BS WHERE BS.NAME='Sartre'), decode('NO','IL',1,0), 'NO', '0', 'OFFERMAKER', SYSDATE, 'OFFERMAKER', SYSDATE);
  END;
  DELETE FROM OFFER_CHAIN_ELIGIBILITY WHERE offer_chain_id = 1203651;
  INSERT INTO OFFER_CHAIN_ELIGIBILITY (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (ELG_ID_SEQ.NEXTVAL, 1203651, 'GIFT CERTIFICATE REQUIRED', '1', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_ELIGIBILITY (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (ELG_ID_SEQ.NEXTVAL, 1203651, 'IS_COMP', '1', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_ELIGIBILITY (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (ELG_ID_SEQ.NEXTVAL, 1203651, 'MAX_CONCURRENT_SUBS', '1', 'OFFERMAKER', SYSDATE);
  DELETE FROM OFFER_CHAIN_META_DATA WHERE offer_chain_id = 1203651;
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1203651, 'BUNDLE_EXPLANATION', 'Bundle A - Anniversary Free 12 Week Comp Sub - Redeem OC', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1203651, 'PRICE_DESCRIPTION', '12 Week Anniversary Free Comp Sub Promotion Subscription - Redemption', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1203651, 'PRICE_SHORT_DESCRIPTION', 'BNDL A / $0 12 wks Anniversary Free Comp Sub - GC redemp', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1203651, 'OFFER_TYPE', 'Complimentary', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1203651, 'PROMO_PRICE_FOOTER_LABEL', '12 Weeks', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1203651, 'BILLING_CYCLE', '12 Week subscription', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1203651, 'SUBSCRIBER_TYPE', 'Complimentary - Anniversary', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1203651, 'BUNDLE', 'Bundle A (Web+SP)', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1203651, 'ADX_BUNDLE', 'MM_PROMO', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1203651, 'SIEBEL_CAMPAIGN_CODE', '39QYU', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1203651, 'IS_COMP', '1', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1203651, 'ANNUAL_PRICE', '0.00', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1203651, 'UID', '454a37b571800c432947125e4e6ab3430bcf346ce16290e0a2db3db26f1a7b22', 'OFFERMAKER', SYSDATE);
  DELETE FROM OFFER_CHAIN_NOTIFICATION_TYPE WHERE offer_chain_id = 1203651;
  BEGIN
    SELECT 1 INTO TMP_VAR FROM ACTION WHERE NAME = 'GC_REDEEMER_ON_REDEEM';
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      INSERT INTO ACTION (ID, NAME, CREATE_DATE, CREATED_BY) VALUES (ACTION_ID_SEQ.NEXTVAL, 'GC_REDEEMER_ON_REDEEM', SYSDATE, 'OFFERMAKER');
  END;
  BEGIN
    SELECT 1 INTO TMP_VAR FROM CORE_OWNER.NOTIFICATION_TYPE WHERE VALUE = 'sartre-anniversary-comp-activation';
  EXCEPTION
    WHEN NO_DATA_FOUND THEN NULL;
      INSERT INTO CORE_OWNER.NOTIFICATION_TYPE (ID, VALUE, TEMPLATE_URL) VALUES (CORE_OWNER.NOTTID_SEQ.NEXTVAL, 'sartre-anniversary-comp-activation', 'N/A');
  END;
  BEGIN
    SELECT 1 INTO TMP_VAR FROM ACTION WHERE NAME = 'CLOSE_SUBSCRIPTION';
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      INSERT INTO ACTION (ID, NAME, CREATE_DATE, CREATED_BY) VALUES (ACTION_ID_SEQ.NEXTVAL, 'CLOSE_SUBSCRIPTION', SYSDATE, 'OFFERMAKER');
  END;
  BEGIN
    SELECT 1 INTO TMP_VAR FROM CORE_OWNER.NOTIFICATION_TYPE WHERE VALUE = 'sartre-sub-expired-gift';
  EXCEPTION
    WHEN NO_DATA_FOUND THEN NULL;
      INSERT INTO CORE_OWNER.NOTIFICATION_TYPE (ID, VALUE, TEMPLATE_URL) VALUES (CORE_OWNER.NOTTID_SEQ.NEXTVAL, 'sartre-sub-expired-gift', 'N/A');
  END;
  INSERT INTO OFFER_CHAIN_NOTIFICATION_TYPE (ID, OFFER_CHAIN_ID, NOTIFICATION_TYPE_ID, ACTION_ID, CREATED_BY, CREATE_DATE) VALUES (OCET_ID_SEQ.NEXTVAL, 1203651, (SELECT ID FROM CORE_OWNER.NOTIFICATION_TYPE WHERE VALUE = 'sartre-anniversary-comp-activation'), (SELECT ID FROM ACTION WHERE NAME = 'GC_REDEEMER_ON_REDEEM'), 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_NOTIFICATION_TYPE (ID, OFFER_CHAIN_ID, NOTIFICATION_TYPE_ID, ACTION_ID, CREATED_BY, CREATE_DATE) VALUES (OCET_ID_SEQ.NEXTVAL, 1203651, (SELECT ID FROM CORE_OWNER.NOTIFICATION_TYPE WHERE VALUE = 'sartre-sub-expired-gift'), (SELECT ID FROM ACTION WHERE NAME = 'CLOSE_SUBSCRIPTION'), 'OFFERMAKER', SYSDATE);
  BEGIN
    SELECT 1 INTO TMP_VAR FROM OFFER_OFFER_CHAIN WHERE OFFER_CHAIN_ID = 1203651 AND INDEX_VALUE = 0 AND ROWNUM <= 1;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
  INSERT INTO OFFER (ID, OFFER_STATUS_ID, ENTITLEMENT_DURATION, CREATED_BY, CREATE_DATE, updated_by, update_date) VALUES (OFR_ID_SEQ.NEXTVAL, 1, 'P0Y0M84DT0H0M', 'OFFERMAKER', SYSDATE, 'OFFERMAKER', SYSDATE);
  BEGIN
    SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Web' AND PRODUCT_STATUS_ID = 1 AND ROWNUM <= 1;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      INSERT INTO PRODUCT (ID, NAME, PRODUCTION_COST, PRODUCT_STATUS_ID, PRODUCT_URI, UNIT_PRICE, CREATED_BY, CREATE_DATE) VALUES (PRD_ID_SEQ.NEXTVAL, 'Web', '0', 1, NULL, '0.357143', 'OFFERMAKER', SYSDATE);
      SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Web' AND PRODUCT_STATUS_ID = 1 AND ROWNUM <= 1;
    WHEN OTHERS THEN
      RAISE;
  END;
  SELECT ID INTO CUR_CAPABILITY_ID FROM CAPABILITY WHERE CODE IN LTRIM(RTRIM((UPPER('MM')))) AND ROWNUM <= 1;
  INSERT INTO PRODUCT_OFFERING (ID, PRODUCT_ID, TAX_POLICY_TYPE_ID, QUANTITY, UNIT_PRICE, TAX_CATEGORY_ID, CAPABILITY_ID, CREATED_BY, CREATE_DATE) VALUES (PO_ID_SEQ.NEXTVAL, CUR_PRD_ID, '1', '84', '0.357143', '2', CUR_CAPABILITY_ID, 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'entitlement_uri', 'http://:hostname:/svc/user/entitlements/mm/:id:.json', 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'DEFAULT_VAT_RATE', '{"*": 0.0}', 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'capability', 'MM', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_PRODUCT_OFFERING (OFFER_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (OFR_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
  INSERT INTO DISCOUNT (ID, NAME, DESCRIPTION, FIXED_AMOUNT, PERCENT_AMOUNT, DISCOUNT_TYPE_ID, CREATED_BY, CREATE_DATE) VALUES (DSC_ID_SEQ.NEXTVAL, 'Discount', 'Target offer price 0.0 given offer total price 44.999976 and product price 30.000012', '30.000012', '0', 1, 'OFFERMAKER', SYSDATE);
  INSERT INTO DISCOUNT_PRODUCT_OFFERING (DISCOUNT_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (DSC_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
  BEGIN
    SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Mobile' AND PRODUCT_STATUS_ID = 1 AND ROWNUM <= 1;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      INSERT INTO PRODUCT (ID, NAME, PRODUCTION_COST, PRODUCT_STATUS_ID, PRODUCT_URI, UNIT_PRICE, CREATED_BY, CREATE_DATE) VALUES (PRD_ID_SEQ.NEXTVAL, 'Mobile', '0', 1, NULL, '0', 'OFFERMAKER', SYSDATE);
      SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Mobile' AND PRODUCT_STATUS_ID = 1 AND ROWNUM <= 1;
    WHEN OTHERS THEN
      RAISE;
  END;
  SELECT ID INTO CUR_CAPABILITY_ID FROM CAPABILITY WHERE CODE IN LTRIM(RTRIM((UPPER('MOW')))) AND ROWNUM <= 1;
  INSERT INTO PRODUCT_OFFERING (ID, PRODUCT_ID, TAX_POLICY_TYPE_ID, QUANTITY, UNIT_PRICE, TAX_CATEGORY_ID, CAPABILITY_ID, CREATED_BY, CREATE_DATE) VALUES (PO_ID_SEQ.NEXTVAL, CUR_PRD_ID, '1', '84', '0', '2', CUR_CAPABILITY_ID, 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'entitlement_uri', 'http://:hostname:/svc/user/entitlements/mow/:id:.json', 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'DEFAULT_VAT_RATE', '{"*": 0.0}', 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'capability', 'MOW', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_PRODUCT_OFFERING (OFFER_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (OFR_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
  BEGIN
    SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Archive Article' AND PRODUCT_STATUS_ID = 1 AND ROWNUM <= 1;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      INSERT INTO PRODUCT (ID, NAME, PRODUCTION_COST, PRODUCT_STATUS_ID, PRODUCT_URI, UNIT_PRICE, CREATED_BY, CREATE_DATE) VALUES (PRD_ID_SEQ.NEXTVAL, 'Archive Article', '0', 1, NULL, '0', 'OFFERMAKER', SYSDATE);
      SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Archive Article' AND PRODUCT_STATUS_ID = 1 AND ROWNUM <= 1;
    WHEN OTHERS THEN
      RAISE;
  END;
  SELECT ID INTO CUR_CAPABILITY_ID FROM CAPABILITY WHERE CODE IN LTRIM(RTRIM((UPPER('AAA')))) AND ROWNUM <= 1;
  INSERT INTO PRODUCT_OFFERING (ID, PRODUCT_ID, TAX_POLICY_TYPE_ID, QUANTITY, UNIT_PRICE, TAX_CATEGORY_ID, CAPABILITY_ID, CREATED_BY, CREATE_DATE) VALUES (PO_ID_SEQ.NEXTVAL, CUR_PRD_ID, '1', '300', '0', '2', CUR_CAPABILITY_ID, 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'entitlement_uri', 'http://:hostname:/svc/user/entitlements/archive/size/300/:id:.json', 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'DEFAULT_VAT_RATE', '{"*": 0.0}', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_PRODUCT_OFFERING (OFFER_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (OFR_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
  BEGIN
    SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'TimesMachine' AND PRODUCT_STATUS_ID = 1 AND ROWNUM <= 1;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      INSERT INTO PRODUCT (ID, NAME, PRODUCTION_COST, PRODUCT_STATUS_ID, PRODUCT_URI, UNIT_PRICE, CREATED_BY, CREATE_DATE) VALUES (PRD_ID_SEQ.NEXTVAL, 'TimesMachine', '0', 1, NULL, '0', 'OFFERMAKER', SYSDATE);
      SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'TimesMachine' AND PRODUCT_STATUS_ID = 1 AND ROWNUM <= 1;
    WHEN OTHERS THEN
      RAISE;
  END;
  SELECT ID INTO CUR_CAPABILITY_ID FROM CAPABILITY WHERE CODE IN LTRIM(RTRIM((UPPER('NONE')))) AND ROWNUM <= 1;
  INSERT INTO PRODUCT_OFFERING (ID, PRODUCT_ID, TAX_POLICY_TYPE_ID, QUANTITY, UNIT_PRICE, TAX_CATEGORY_ID, CAPABILITY_ID, CREATED_BY, CREATE_DATE) VALUES (PO_ID_SEQ.NEXTVAL, CUR_PRD_ID, '1', '84', '0', '2', CUR_CAPABILITY_ID, 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'DEFAULT_VAT_RATE', '{"*": 0.0}', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_PRODUCT_OFFERING (OFFER_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (OFR_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
  BEGIN
    SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Smartphone' AND PRODUCT_STATUS_ID = 1 AND ROWNUM <= 1;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      INSERT INTO PRODUCT (ID, NAME, PRODUCTION_COST, PRODUCT_STATUS_ID, PRODUCT_URI, UNIT_PRICE, CREATED_BY, CREATE_DATE) VALUES (PRD_ID_SEQ.NEXTVAL, 'Smartphone', '0', 1, NULL, '0.178571', 'OFFERMAKER', SYSDATE);
      SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Smartphone' AND PRODUCT_STATUS_ID = 1 AND ROWNUM <= 1;
    WHEN OTHERS THEN
      RAISE;
  END;
  SELECT ID INTO CUR_CAPABILITY_ID FROM CAPABILITY WHERE CODE IN LTRIM(RTRIM((UPPER('MSD')))) AND ROWNUM <= 1;
  INSERT INTO PRODUCT_OFFERING (ID, PRODUCT_ID, TAX_POLICY_TYPE_ID, QUANTITY, UNIT_PRICE, TAX_CATEGORY_ID, CAPABILITY_ID, CREATED_BY, CREATE_DATE) VALUES (PO_ID_SEQ.NEXTVAL, CUR_PRD_ID, '1', '84', '0.178571', '2', CUR_CAPABILITY_ID, 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'entitlement_uri', 'http://:hostname:/svc/user/entitlements/msd/:id:.json', 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'DEFAULT_VAT_RATE', '{"*": 0.0}', 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'capability', 'MSD', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_PRODUCT_OFFERING (OFFER_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (OFR_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
  INSERT INTO DISCOUNT (ID, NAME, DESCRIPTION, FIXED_AMOUNT, PERCENT_AMOUNT, DISCOUNT_TYPE_ID, CREATED_BY, CREATE_DATE) VALUES (DSC_ID_SEQ.NEXTVAL, 'Discount', 'Target offer price 0.0 given offer total price 44.999976 and product price 14.999964', '14.999964', '0', 1, 'OFFERMAKER', SYSDATE);
  INSERT INTO DISCOUNT_PRODUCT_OFFERING (DISCOUNT_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (DSC_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_OFFER_CHAIN (OFFER_ID, OFFER_CHAIN_ID, INDEX_VALUE, NUM_RECURRENCES, CREATED_BY, CREATE_DATE, updated_by, update_date) VALUES (OFR_ID_SEQ.CURRVAL, 1203651, '0', '1', 'OFFERMAKER', SYSDATE, 'OFFERMAKER', SYSDATE);
  END;
END;
/

DECLARE
  TMP_VAR NUMBER;
  CUR_PRD_ID NUMBER;
  CUR_CAPABILITY_ID NUMBER;
BEGIN
  BEGIN
    SELECT 1 INTO TMP_VAR FROM OFFER_CHAIN WHERE ID = 1203652 AND ROWNUM <= 1;
    UPDATE OFFER_CHAIN SET NAME='NYTimes: Web + Smartphone App', DESCRIPTION='Unlimited access to NYTimes.com and the NYTimes smartphone app.*', PRODUCT_URI='', VENDOR_SOURCE_ID='1', BILLING_SOURCE_ID=(SELECT ID FROM BILLING_SOURCE BS WHERE BS.NAME='Sartre'), IS_SEAT_LICENSE=0, GROUP_ACCOUNT_TYPE_ID='NO',IS_ADDRESS_REQUIRED=0, OFFER_CHAIN_STATUS_ID = 1, UPDATE_DATE = SYSDATE, UPDATED_BY = 'OFFERMAKER', IS_GIFT_CERTIFICATE='0', REVOKE_ENTITLEMENTS = '0', ADOPTABILITY_WINDOW_START_DATE = to_date('09-Mar-2012 00:00:00','DD-MON-YY HH24:MI:SS'), ADOPTABILITY_WINDOW_END_DATE = to_date('15-Jul-2013 00:00:00','DD-MON-YY HH24:MI:SS') WHERE ID = 1203652;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      INSERT INTO OFFER_CHAIN (ID, NAME, DESCRIPTION, ADOPTABILITY_WINDOW_START_DATE, ADOPTABILITY_WINDOW_END_DATE, IS_GIFT_CERTIFICATE, PRODUCT_URI, OFFER_CHAIN_STATUS_ID, REVOKE_ENTITLEMENTS, VENDOR_SOURCE_ID, BILLING_SOURCE_ID, IS_SEAT_LICENSE, GROUP_ACCOUNT_TYPE_ID, IS_ADDRESS_REQUIRED, CREATED_BY, CREATE_DATE, updated_by, update_date) VALUES (1203652, 'NYTimes: Web + Smartphone App', 'Unlimited access to NYTimes.com and the NYTimes smartphone app.*', to_date('09-Mar-2012 00:00:00','DD-MON-YY HH24:MI:SS'), to_date('15-Jul-2013 00:00:00','DD-MON-YY HH24:MI:SS'), '0', NULL, '1', '0', '1', (SELECT ID FROM BILLING_SOURCE BS WHERE BS.NAME='Sartre'), decode('NO','IL',1,0), 'NO', '0', 'OFFERMAKER', SYSDATE, 'OFFERMAKER', SYSDATE);
  END;
  DELETE FROM OFFER_CHAIN_ELIGIBILITY WHERE offer_chain_id = 1203652;
  INSERT INTO OFFER_CHAIN_ELIGIBILITY (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (ELG_ID_SEQ.NEXTVAL, 1203652, 'GIFT CERTIFICATE REQUIRED', '1', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_ELIGIBILITY (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (ELG_ID_SEQ.NEXTVAL, 1203652, 'IS_COMP', '0', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_ELIGIBILITY (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (ELG_ID_SEQ.NEXTVAL, 1203652, 'MAX_CONCURRENT_SUBS', '1', 'OFFERMAKER', SYSDATE);
  DELETE FROM OFFER_CHAIN_META_DATA WHERE offer_chain_id = 1203652;
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1203652, 'BUNDLE_EXPLANATION', 'Bundle A - Anniversary Free 12 Week Comp Sub - UpSell OC', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1203652, 'PRICE_DESCRIPTION', '12 week Free Comp Subscription upsell - $0 for 12 weeks. Then $0.99 for your first 8 weeks ($3.75 / week thereafter)', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1203652, 'PRICE_SHORT_DESCRIPTION', 'BNDL A / $0 12 wks Anniversary Free Comp Sub - GC upsell', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1203652, 'OFFER_TYPE', '$0.99 for first 8 Weeks after gift period', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1203652, 'PRODUCT_MARKETING_DESCRIPTOR', 'Add to your complimentary subscription', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1203652, 'OFFER_PRICE_DESCRIPTOR', 'First 12 Weeks Free', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1203652, 'OFFER_PRICE', '$0.99 for subsequent 8 weeks', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1203652, 'OFFER_PRICE_DETAIL', '($3.75 /  week thereafter)', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1203652, 'PROMO_PRICE_FOOTER_LABEL', 'First 12 weeks', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1203652, 'ACTUAL_PRICE_FOOTER_LABEL', 'Subsequent 8 weeks $0.99', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1203652, 'UPSELL_OFFER_HEADER', 'WANT TO ADD 8 WEEKS FOR ONLY 99 CENTS?', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1203652, 'UPSELL_OFFER_TRAILER', 'Sign up now to get 8 additional weeks for just 99 cents', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1203652, 'BILLING_CYCLE', 'every 4 weeks thereafter', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1203652, 'SUBSCRIBER_TYPE', 'Upsell - Anniversary', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1203652, 'CANCELABLE', '1', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1203652, 'PRORATED_REFUND_DAYS_LIMIT', '28', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1203652, 'OPEN_TO_ANONYMOUS', '1', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1203652, 'BUNDLE', 'Bundle A (Web+SP)', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1203652, 'ADX_BUNDLE', 'MM_PROMO', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1203652, 'SIEBEL_CAMPAIGN_CODE', '39RL8', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1203652, 'ANNUAL_PRICE', '195.00', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1203652, 'UID', '2acd98e70ff8ca72f4e5504db053dbbe22bcda4cbbb439006b9bd5c60fe1b5a7', 'OFFERMAKER', SYSDATE);
  DELETE FROM OFFER_CHAIN_NOTIFICATION_TYPE WHERE offer_chain_id = 1203652;
  BEGIN
    SELECT 1 INTO TMP_VAR FROM ACTION WHERE NAME = 'SUBSCRIBE_TO_OFFER_CHAIN';
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      INSERT INTO ACTION (ID, NAME, CREATE_DATE, CREATED_BY) VALUES (ACTION_ID_SEQ.NEXTVAL, 'SUBSCRIBE_TO_OFFER_CHAIN', SYSDATE, 'OFFERMAKER');
  END;
  BEGIN
    SELECT 1 INTO TMP_VAR FROM CORE_OWNER.NOTIFICATION_TYPE WHERE VALUE = 'sartre-purchase';
  EXCEPTION
    WHEN NO_DATA_FOUND THEN NULL;
      INSERT INTO CORE_OWNER.NOTIFICATION_TYPE (ID, VALUE, TEMPLATE_URL) VALUES (CORE_OWNER.NOTTID_SEQ.NEXTVAL, 'sartre-purchase', 'N/A');
  END;
  BEGIN
    SELECT 1 INTO TMP_VAR FROM ACTION WHERE NAME = 'UPGRADE_SUBSCRIPTION';
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      INSERT INTO ACTION (ID, NAME, CREATE_DATE, CREATED_BY) VALUES (ACTION_ID_SEQ.NEXTVAL, 'UPGRADE_SUBSCRIPTION', SYSDATE, 'OFFERMAKER');
  END;
  BEGIN
    SELECT 1 INTO TMP_VAR FROM CORE_OWNER.NOTIFICATION_TYPE WHERE VALUE = 'sartre-purchase';
  EXCEPTION
    WHEN NO_DATA_FOUND THEN NULL;
      INSERT INTO CORE_OWNER.NOTIFICATION_TYPE (ID, VALUE, TEMPLATE_URL) VALUES (CORE_OWNER.NOTTID_SEQ.NEXTVAL, 'sartre-purchase', 'N/A');
  END;
  BEGIN
    SELECT 1 INTO TMP_VAR FROM ACTION WHERE NAME = 'CANCEL_SUBSCRIPTION';
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      INSERT INTO ACTION (ID, NAME, CREATE_DATE, CREATED_BY) VALUES (ACTION_ID_SEQ.NEXTVAL, 'CANCEL_SUBSCRIPTION', SYSDATE, 'OFFERMAKER');
  END;
  BEGIN
    SELECT 1 INTO TMP_VAR FROM CORE_OWNER.NOTIFICATION_TYPE WHERE VALUE = 'sartre-cancel';
  EXCEPTION
    WHEN NO_DATA_FOUND THEN NULL;
      INSERT INTO CORE_OWNER.NOTIFICATION_TYPE (ID, VALUE, TEMPLATE_URL) VALUES (CORE_OWNER.NOTTID_SEQ.NEXTVAL, 'sartre-cancel', 'N/A');
  END;
  BEGIN
    SELECT 1 INTO TMP_VAR FROM ACTION WHERE NAME = 'SYSTEM_CANCEL';
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      INSERT INTO ACTION (ID, NAME, CREATE_DATE, CREATED_BY) VALUES (ACTION_ID_SEQ.NEXTVAL, 'SYSTEM_CANCEL', SYSDATE, 'OFFERMAKER');
  END;
  BEGIN
    SELECT 1 INTO TMP_VAR FROM CORE_OWNER.NOTIFICATION_TYPE WHERE VALUE = 'sartre-decline';
  EXCEPTION
    WHEN NO_DATA_FOUND THEN NULL;
      INSERT INTO CORE_OWNER.NOTIFICATION_TYPE (ID, VALUE, TEMPLATE_URL) VALUES (CORE_OWNER.NOTTID_SEQ.NEXTVAL, 'sartre-decline', 'N/A');
  END;
  BEGIN
    SELECT 1 INTO TMP_VAR FROM ACTION WHERE NAME = 'CREDIT_CARD_EXP';
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      INSERT INTO ACTION (ID, NAME, CREATE_DATE, CREATED_BY) VALUES (ACTION_ID_SEQ.NEXTVAL, 'CREDIT_CARD_EXP', SYSDATE, 'OFFERMAKER');
  END;
  BEGIN
    SELECT 1 INTO TMP_VAR FROM CORE_OWNER.NOTIFICATION_TYPE WHERE VALUE = 'card_expiration';
  EXCEPTION
    WHEN NO_DATA_FOUND THEN NULL;
      INSERT INTO CORE_OWNER.NOTIFICATION_TYPE (ID, VALUE, TEMPLATE_URL) VALUES (CORE_OWNER.NOTTID_SEQ.NEXTVAL, 'card_expiration', 'N/A');
  END;
  BEGIN
    SELECT 1 INTO TMP_VAR FROM ACTION WHERE NAME = 'GC_REDEEMER_ON_REDEEM';
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      INSERT INTO ACTION (ID, NAME, CREATE_DATE, CREATED_BY) VALUES (ACTION_ID_SEQ.NEXTVAL, 'GC_REDEEMER_ON_REDEEM', SYSDATE, 'OFFERMAKER');
  END;
  BEGIN
    SELECT 1 INTO TMP_VAR FROM CORE_OWNER.NOTIFICATION_TYPE WHERE VALUE = 'sartre-anniversary-comp-upsell-activation';
  EXCEPTION
    WHEN NO_DATA_FOUND THEN NULL;
      INSERT INTO CORE_OWNER.NOTIFICATION_TYPE (ID, VALUE, TEMPLATE_URL) VALUES (CORE_OWNER.NOTTID_SEQ.NEXTVAL, 'sartre-anniversary-comp-upsell-activation', 'N/A');
  END;
  INSERT INTO OFFER_CHAIN_NOTIFICATION_TYPE (ID, OFFER_CHAIN_ID, NOTIFICATION_TYPE_ID, ACTION_ID, CREATED_BY, CREATE_DATE) VALUES (OCET_ID_SEQ.NEXTVAL, 1203652, (SELECT ID FROM CORE_OWNER.NOTIFICATION_TYPE WHERE VALUE = 'sartre-purchase'), (SELECT ID FROM ACTION WHERE NAME = 'SUBSCRIBE_TO_OFFER_CHAIN'), 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_NOTIFICATION_TYPE (ID, OFFER_CHAIN_ID, NOTIFICATION_TYPE_ID, ACTION_ID, CREATED_BY, CREATE_DATE) VALUES (OCET_ID_SEQ.NEXTVAL, 1203652, (SELECT ID FROM CORE_OWNER.NOTIFICATION_TYPE WHERE VALUE = 'sartre-purchase'), (SELECT ID FROM ACTION WHERE NAME = 'UPGRADE_SUBSCRIPTION'), 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_NOTIFICATION_TYPE (ID, OFFER_CHAIN_ID, NOTIFICATION_TYPE_ID, ACTION_ID, CREATED_BY, CREATE_DATE) VALUES (OCET_ID_SEQ.NEXTVAL, 1203652, (SELECT ID FROM CORE_OWNER.NOTIFICATION_TYPE WHERE VALUE = 'sartre-cancel'), (SELECT ID FROM ACTION WHERE NAME = 'CANCEL_SUBSCRIPTION'), 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_NOTIFICATION_TYPE (ID, OFFER_CHAIN_ID, NOTIFICATION_TYPE_ID, ACTION_ID, CREATED_BY, CREATE_DATE) VALUES (OCET_ID_SEQ.NEXTVAL, 1203652, (SELECT ID FROM CORE_OWNER.NOTIFICATION_TYPE WHERE VALUE = 'sartre-decline'), (SELECT ID FROM ACTION WHERE NAME = 'SYSTEM_CANCEL'), 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_NOTIFICATION_TYPE (ID, OFFER_CHAIN_ID, NOTIFICATION_TYPE_ID, ACTION_ID, CREATED_BY, CREATE_DATE) VALUES (OCET_ID_SEQ.NEXTVAL, 1203652, (SELECT ID FROM CORE_OWNER.NOTIFICATION_TYPE WHERE VALUE = 'card_expiration'), (SELECT ID FROM ACTION WHERE NAME = 'CREDIT_CARD_EXP'), 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_NOTIFICATION_TYPE (ID, OFFER_CHAIN_ID, NOTIFICATION_TYPE_ID, ACTION_ID, CREATED_BY, CREATE_DATE) VALUES (OCET_ID_SEQ.NEXTVAL, 1203652, (SELECT ID FROM CORE_OWNER.NOTIFICATION_TYPE WHERE VALUE = 'sartre-anniversary-comp-upsell-activation'), (SELECT ID FROM ACTION WHERE NAME = 'GC_REDEEMER_ON_REDEEM'), 'OFFERMAKER', SYSDATE);
  BEGIN
    SELECT 1 INTO TMP_VAR FROM OFFER_OFFER_CHAIN WHERE OFFER_CHAIN_ID = 1203652 AND INDEX_VALUE = 0 AND ROWNUM <= 1;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
  INSERT INTO OFFER (ID, OFFER_STATUS_ID, ENTITLEMENT_DURATION, CREATED_BY, CREATE_DATE, updated_by, update_date) VALUES (OFR_ID_SEQ.NEXTVAL, 1, 'P0Y0M84DT0H0M', 'OFFERMAKER', SYSDATE, 'OFFERMAKER', SYSDATE);
  BEGIN
    SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Web' AND PRODUCT_STATUS_ID = 1 AND ROWNUM <= 1;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      INSERT INTO PRODUCT (ID, NAME, PRODUCTION_COST, PRODUCT_STATUS_ID, PRODUCT_URI, UNIT_PRICE, CREATED_BY, CREATE_DATE) VALUES (PRD_ID_SEQ.NEXTVAL, 'Web', '0', 1, NULL, '0.357143', 'OFFERMAKER', SYSDATE);
      SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Web' AND PRODUCT_STATUS_ID = 1 AND ROWNUM <= 1;
    WHEN OTHERS THEN
      RAISE;
  END;
  SELECT ID INTO CUR_CAPABILITY_ID FROM CAPABILITY WHERE CODE IN LTRIM(RTRIM((UPPER('MM')))) AND ROWNUM <= 1;
  INSERT INTO PRODUCT_OFFERING (ID, PRODUCT_ID, TAX_POLICY_TYPE_ID, QUANTITY, UNIT_PRICE, TAX_CATEGORY_ID, CAPABILITY_ID, CREATED_BY, CREATE_DATE) VALUES (PO_ID_SEQ.NEXTVAL, CUR_PRD_ID, '1', '84', '0.357143', '2', CUR_CAPABILITY_ID, 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'entitlement_uri', 'http://:hostname:/svc/user/entitlements/mm/:id:.json', 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'DEFAULT_VAT_RATE', '{"*": 0.0}', 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'capability', 'MM', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_PRODUCT_OFFERING (OFFER_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (OFR_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
  INSERT INTO DISCOUNT (ID, NAME, DESCRIPTION, FIXED_AMOUNT, PERCENT_AMOUNT, DISCOUNT_TYPE_ID, CREATED_BY, CREATE_DATE) VALUES (DSC_ID_SEQ.NEXTVAL, 'Discount', 'Target offer price 0.0 given offer total price 44.999976 and product price 30.000012', '30.000012', '0', 1, 'OFFERMAKER', SYSDATE);
  INSERT INTO DISCOUNT_PRODUCT_OFFERING (DISCOUNT_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (DSC_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
  BEGIN
    SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Mobile' AND PRODUCT_STATUS_ID = 1 AND ROWNUM <= 1;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      INSERT INTO PRODUCT (ID, NAME, PRODUCTION_COST, PRODUCT_STATUS_ID, PRODUCT_URI, UNIT_PRICE, CREATED_BY, CREATE_DATE) VALUES (PRD_ID_SEQ.NEXTVAL, 'Mobile', '0', 1, NULL, '0', 'OFFERMAKER', SYSDATE);
      SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Mobile' AND PRODUCT_STATUS_ID = 1 AND ROWNUM <= 1;
    WHEN OTHERS THEN
      RAISE;
  END;
  SELECT ID INTO CUR_CAPABILITY_ID FROM CAPABILITY WHERE CODE IN LTRIM(RTRIM((UPPER('MOW')))) AND ROWNUM <= 1;
  INSERT INTO PRODUCT_OFFERING (ID, PRODUCT_ID, TAX_POLICY_TYPE_ID, QUANTITY, UNIT_PRICE, TAX_CATEGORY_ID, CAPABILITY_ID, CREATED_BY, CREATE_DATE) VALUES (PO_ID_SEQ.NEXTVAL, CUR_PRD_ID, '1', '84', '0', '2', CUR_CAPABILITY_ID, 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'entitlement_uri', 'http://:hostname:/svc/user/entitlements/mow/:id:.json', 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'DEFAULT_VAT_RATE', '{"*": 0.0}', 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'capability', 'MOW', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_PRODUCT_OFFERING (OFFER_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (OFR_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
  BEGIN
    SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Archive Article' AND PRODUCT_STATUS_ID = 1 AND ROWNUM <= 1;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      INSERT INTO PRODUCT (ID, NAME, PRODUCTION_COST, PRODUCT_STATUS_ID, PRODUCT_URI, UNIT_PRICE, CREATED_BY, CREATE_DATE) VALUES (PRD_ID_SEQ.NEXTVAL, 'Archive Article', '0', 1, NULL, '0', 'OFFERMAKER', SYSDATE);
      SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Archive Article' AND PRODUCT_STATUS_ID = 1 AND ROWNUM <= 1;
    WHEN OTHERS THEN
      RAISE;
  END;
  SELECT ID INTO CUR_CAPABILITY_ID FROM CAPABILITY WHERE CODE IN LTRIM(RTRIM((UPPER('AAA')))) AND ROWNUM <= 1;
  INSERT INTO PRODUCT_OFFERING (ID, PRODUCT_ID, TAX_POLICY_TYPE_ID, QUANTITY, UNIT_PRICE, TAX_CATEGORY_ID, CAPABILITY_ID, CREATED_BY, CREATE_DATE) VALUES (PO_ID_SEQ.NEXTVAL, CUR_PRD_ID, '1', '300', '0', '2', CUR_CAPABILITY_ID, 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'entitlement_uri', 'http://:hostname:/svc/user/entitlements/archive/size/300/:id:.json', 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'DEFAULT_VAT_RATE', '{"*": 0.0}', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_PRODUCT_OFFERING (OFFER_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (OFR_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
  BEGIN
    SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'TimesMachine' AND PRODUCT_STATUS_ID = 1 AND ROWNUM <= 1;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      INSERT INTO PRODUCT (ID, NAME, PRODUCTION_COST, PRODUCT_STATUS_ID, PRODUCT_URI, UNIT_PRICE, CREATED_BY, CREATE_DATE) VALUES (PRD_ID_SEQ.NEXTVAL, 'TimesMachine', '0', 1, NULL, '0', 'OFFERMAKER', SYSDATE);
      SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'TimesMachine' AND PRODUCT_STATUS_ID = 1 AND ROWNUM <= 1;
    WHEN OTHERS THEN
      RAISE;
  END;
  SELECT ID INTO CUR_CAPABILITY_ID FROM CAPABILITY WHERE CODE IN LTRIM(RTRIM((UPPER('NONE')))) AND ROWNUM <= 1;
  INSERT INTO PRODUCT_OFFERING (ID, PRODUCT_ID, TAX_POLICY_TYPE_ID, QUANTITY, UNIT_PRICE, TAX_CATEGORY_ID, CAPABILITY_ID, CREATED_BY, CREATE_DATE) VALUES (PO_ID_SEQ.NEXTVAL, CUR_PRD_ID, '1', '84', '0', '2', CUR_CAPABILITY_ID, 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'DEFAULT_VAT_RATE', '{"*": 0.0}', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_PRODUCT_OFFERING (OFFER_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (OFR_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
  BEGIN
    SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Smartphone' AND PRODUCT_STATUS_ID = 1 AND ROWNUM <= 1;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      INSERT INTO PRODUCT (ID, NAME, PRODUCTION_COST, PRODUCT_STATUS_ID, PRODUCT_URI, UNIT_PRICE, CREATED_BY, CREATE_DATE) VALUES (PRD_ID_SEQ.NEXTVAL, 'Smartphone', '0', 1, NULL, '0.178571', 'OFFERMAKER', SYSDATE);
      SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Smartphone' AND PRODUCT_STATUS_ID = 1 AND ROWNUM <= 1;
    WHEN OTHERS THEN
      RAISE;
  END;
  SELECT ID INTO CUR_CAPABILITY_ID FROM CAPABILITY WHERE CODE IN LTRIM(RTRIM((UPPER('MSD')))) AND ROWNUM <= 1;
  INSERT INTO PRODUCT_OFFERING (ID, PRODUCT_ID, TAX_POLICY_TYPE_ID, QUANTITY, UNIT_PRICE, TAX_CATEGORY_ID, CAPABILITY_ID, CREATED_BY, CREATE_DATE) VALUES (PO_ID_SEQ.NEXTVAL, CUR_PRD_ID, '1', '84', '0.178571', '2', CUR_CAPABILITY_ID, 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'entitlement_uri', 'http://:hostname:/svc/user/entitlements/msd/:id:.json', 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'DEFAULT_VAT_RATE', '{"*": 0.0}', 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'capability', 'MSD', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_PRODUCT_OFFERING (OFFER_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (OFR_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
  INSERT INTO DISCOUNT (ID, NAME, DESCRIPTION, FIXED_AMOUNT, PERCENT_AMOUNT, DISCOUNT_TYPE_ID, CREATED_BY, CREATE_DATE) VALUES (DSC_ID_SEQ.NEXTVAL, 'Discount', 'Target offer price 0.0 given offer total price 44.999976 and product price 14.999964', '14.999964', '0', 1, 'OFFERMAKER', SYSDATE);
  INSERT INTO DISCOUNT_PRODUCT_OFFERING (DISCOUNT_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (DSC_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_OFFER_CHAIN (OFFER_ID, OFFER_CHAIN_ID, INDEX_VALUE, NUM_RECURRENCES, CREATED_BY, CREATE_DATE, updated_by, update_date) VALUES (OFR_ID_SEQ.CURRVAL, 1203652, '0', '1', 'OFFERMAKER', SYSDATE, 'OFFERMAKER', SYSDATE);
  END;
  BEGIN
    SELECT 1 INTO TMP_VAR FROM OFFER_OFFER_CHAIN WHERE OFFER_CHAIN_ID = 1203652 AND INDEX_VALUE = 1 AND ROWNUM <= 1;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
  INSERT INTO OFFER (ID, OFFER_STATUS_ID, ENTITLEMENT_DURATION, CREATED_BY, CREATE_DATE, updated_by, update_date) VALUES (OFR_ID_SEQ.NEXTVAL, 1, 'P0Y0M56DT0H0M', 'OFFERMAKER', SYSDATE, 'OFFERMAKER', SYSDATE);
  BEGIN
    SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Web' AND PRODUCT_STATUS_ID = 1 AND ROWNUM <= 1;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      INSERT INTO PRODUCT (ID, NAME, PRODUCTION_COST, PRODUCT_STATUS_ID, PRODUCT_URI, UNIT_PRICE, CREATED_BY, CREATE_DATE) VALUES (PRD_ID_SEQ.NEXTVAL, 'Web', '0', 1, NULL, '0.357143', 'OFFERMAKER', SYSDATE);
      SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Web' AND PRODUCT_STATUS_ID = 1 AND ROWNUM <= 1;
    WHEN OTHERS THEN
      RAISE;
  END;
  SELECT ID INTO CUR_CAPABILITY_ID FROM CAPABILITY WHERE CODE IN LTRIM(RTRIM((UPPER('MM')))) AND ROWNUM <= 1;
  INSERT INTO PRODUCT_OFFERING (ID, PRODUCT_ID, TAX_POLICY_TYPE_ID, QUANTITY, UNIT_PRICE, TAX_CATEGORY_ID, CAPABILITY_ID, CREATED_BY, CREATE_DATE) VALUES (PO_ID_SEQ.NEXTVAL, CUR_PRD_ID, '1', '56', '0.357143', '2', CUR_CAPABILITY_ID, 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'entitlement_uri', 'http://:hostname:/svc/user/entitlements/mm/:id:.json', 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'DEFAULT_VAT_RATE', '{"*": 0.0}', 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'capability', 'MM', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_PRODUCT_OFFERING (OFFER_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (OFR_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
  INSERT INTO DISCOUNT (ID, NAME, DESCRIPTION, FIXED_AMOUNT, PERCENT_AMOUNT, DISCOUNT_TYPE_ID, CREATED_BY, CREATE_DATE) VALUES (DSC_ID_SEQ.NEXTVAL, 'Discount', 'Target offer price 0.99 given offer total price 29.999984 and product price 19.340007384', '19.340007384', '0', 1, 'OFFERMAKER', SYSDATE);
  INSERT INTO DISCOUNT_PRODUCT_OFFERING (DISCOUNT_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (DSC_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
  BEGIN
    SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Mobile' AND PRODUCT_STATUS_ID = 1 AND ROWNUM <= 1;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      INSERT INTO PRODUCT (ID, NAME, PRODUCTION_COST, PRODUCT_STATUS_ID, PRODUCT_URI, UNIT_PRICE, CREATED_BY, CREATE_DATE) VALUES (PRD_ID_SEQ.NEXTVAL, 'Mobile', '0', 1, NULL, '0', 'OFFERMAKER', SYSDATE);
      SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Mobile' AND PRODUCT_STATUS_ID = 1 AND ROWNUM <= 1;
    WHEN OTHERS THEN
      RAISE;
  END;
  SELECT ID INTO CUR_CAPABILITY_ID FROM CAPABILITY WHERE CODE IN LTRIM(RTRIM((UPPER('MOW')))) AND ROWNUM <= 1;
  INSERT INTO PRODUCT_OFFERING (ID, PRODUCT_ID, TAX_POLICY_TYPE_ID, QUANTITY, UNIT_PRICE, TAX_CATEGORY_ID, CAPABILITY_ID, CREATED_BY, CREATE_DATE) VALUES (PO_ID_SEQ.NEXTVAL, CUR_PRD_ID, '1', '56', '0', '2', CUR_CAPABILITY_ID, 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'entitlement_uri', 'http://:hostname:/svc/user/entitlements/mow/:id:.json', 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'DEFAULT_VAT_RATE', '{"*": 0.0}', 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'capability', 'MOW', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_PRODUCT_OFFERING (OFFER_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (OFR_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
  BEGIN
    SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Archive Article' AND PRODUCT_STATUS_ID = 1 AND ROWNUM <= 1;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      INSERT INTO PRODUCT (ID, NAME, PRODUCTION_COST, PRODUCT_STATUS_ID, PRODUCT_URI, UNIT_PRICE, CREATED_BY, CREATE_DATE) VALUES (PRD_ID_SEQ.NEXTVAL, 'Archive Article', '0', 1, NULL, '0', 'OFFERMAKER', SYSDATE);
      SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Archive Article' AND PRODUCT_STATUS_ID = 1 AND ROWNUM <= 1;
    WHEN OTHERS THEN
      RAISE;
  END;
  SELECT ID INTO CUR_CAPABILITY_ID FROM CAPABILITY WHERE CODE IN LTRIM(RTRIM((UPPER('AAA')))) AND ROWNUM <= 1;
  INSERT INTO PRODUCT_OFFERING (ID, PRODUCT_ID, TAX_POLICY_TYPE_ID, QUANTITY, UNIT_PRICE, TAX_CATEGORY_ID, CAPABILITY_ID, CREATED_BY, CREATE_DATE) VALUES (PO_ID_SEQ.NEXTVAL, CUR_PRD_ID, '1', '200', '0', '2', CUR_CAPABILITY_ID, 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'entitlement_uri', 'http://:hostname:/svc/user/entitlements/archive/size/200/:id:.json', 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'DEFAULT_VAT_RATE', '{"*": 0.0}', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_PRODUCT_OFFERING (OFFER_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (OFR_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
  BEGIN
    SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'TimesMachine' AND PRODUCT_STATUS_ID = 1 AND ROWNUM <= 1;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      INSERT INTO PRODUCT (ID, NAME, PRODUCTION_COST, PRODUCT_STATUS_ID, PRODUCT_URI, UNIT_PRICE, CREATED_BY, CREATE_DATE) VALUES (PRD_ID_SEQ.NEXTVAL, 'TimesMachine', '0', 1, NULL, '0', 'OFFERMAKER', SYSDATE);
      SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'TimesMachine' AND PRODUCT_STATUS_ID = 1 AND ROWNUM <= 1;
    WHEN OTHERS THEN
      RAISE;
  END;
  SELECT ID INTO CUR_CAPABILITY_ID FROM CAPABILITY WHERE CODE IN LTRIM(RTRIM((UPPER('NONE')))) AND ROWNUM <= 1;
  INSERT INTO PRODUCT_OFFERING (ID, PRODUCT_ID, TAX_POLICY_TYPE_ID, QUANTITY, UNIT_PRICE, TAX_CATEGORY_ID, CAPABILITY_ID, CREATED_BY, CREATE_DATE) VALUES (PO_ID_SEQ.NEXTVAL, CUR_PRD_ID, '1', '56', '0', '2', CUR_CAPABILITY_ID, 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'DEFAULT_VAT_RATE', '{"*": 0.0}', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_PRODUCT_OFFERING (OFFER_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (OFR_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
  BEGIN
    SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Smartphone' AND PRODUCT_STATUS_ID = 1 AND ROWNUM <= 1;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      INSERT INTO PRODUCT (ID, NAME, PRODUCTION_COST, PRODUCT_STATUS_ID, PRODUCT_URI, UNIT_PRICE, CREATED_BY, CREATE_DATE) VALUES (PRD_ID_SEQ.NEXTVAL, 'Smartphone', '0', 1, NULL, '0.178571', 'OFFERMAKER', SYSDATE);
      SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Smartphone' AND PRODUCT_STATUS_ID = 1 AND ROWNUM <= 1;
    WHEN OTHERS THEN
      RAISE;
  END;
  SELECT ID INTO CUR_CAPABILITY_ID FROM CAPABILITY WHERE CODE IN LTRIM(RTRIM((UPPER('MSD')))) AND ROWNUM <= 1;
  INSERT INTO PRODUCT_OFFERING (ID, PRODUCT_ID, TAX_POLICY_TYPE_ID, QUANTITY, UNIT_PRICE, TAX_CATEGORY_ID, CAPABILITY_ID, CREATED_BY, CREATE_DATE) VALUES (PO_ID_SEQ.NEXTVAL, CUR_PRD_ID, '1', '56', '0.178571', '2', CUR_CAPABILITY_ID, 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'entitlement_uri', 'http://:hostname:/svc/user/entitlements/msd/:id:.json', 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'DEFAULT_VAT_RATE', '{"*": 0.0}', 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'capability', 'MSD', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_PRODUCT_OFFERING (OFFER_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (OFR_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
  INSERT INTO DISCOUNT (ID, NAME, DESCRIPTION, FIXED_AMOUNT, PERCENT_AMOUNT, DISCOUNT_TYPE_ID, CREATED_BY, CREATE_DATE) VALUES (DSC_ID_SEQ.NEXTVAL, 'Discount', 'Target offer price 0.99 given offer total price 29.999984 and product price 9.669976616', '9.669976616', '0', 1, 'OFFERMAKER', SYSDATE);
  INSERT INTO DISCOUNT_PRODUCT_OFFERING (DISCOUNT_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (DSC_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_OFFER_CHAIN (OFFER_ID, OFFER_CHAIN_ID, INDEX_VALUE, NUM_RECURRENCES, CREATED_BY, CREATE_DATE, updated_by, update_date) VALUES (OFR_ID_SEQ.CURRVAL, 1203652, '1', '1', 'OFFERMAKER', SYSDATE, 'OFFERMAKER', SYSDATE);
  END;
  BEGIN
    SELECT 1 INTO TMP_VAR FROM OFFER_OFFER_CHAIN WHERE OFFER_CHAIN_ID = 1203652 AND INDEX_VALUE = 2 AND ROWNUM <= 1;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
  INSERT INTO OFFER (ID, OFFER_STATUS_ID, ENTITLEMENT_DURATION, CREATED_BY, CREATE_DATE, updated_by, update_date) VALUES (OFR_ID_SEQ.NEXTVAL, 1, 'P0Y0M28DT0H0M', 'OFFERMAKER', SYSDATE, 'OFFERMAKER', SYSDATE);
  BEGIN
    SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Web' AND PRODUCT_STATUS_ID = 1 AND ROWNUM <= 1;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      INSERT INTO PRODUCT (ID, NAME, PRODUCTION_COST, PRODUCT_STATUS_ID, PRODUCT_URI, UNIT_PRICE, CREATED_BY, CREATE_DATE) VALUES (PRD_ID_SEQ.NEXTVAL, 'Web', '0', 1, NULL, '0.357143', 'OFFERMAKER', SYSDATE);
      SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Web' AND PRODUCT_STATUS_ID = 1 AND ROWNUM <= 1;
    WHEN OTHERS THEN
      RAISE;
  END;
  SELECT ID INTO CUR_CAPABILITY_ID FROM CAPABILITY WHERE CODE IN LTRIM(RTRIM((UPPER('MM')))) AND ROWNUM <= 1;
  INSERT INTO PRODUCT_OFFERING (ID, PRODUCT_ID, TAX_POLICY_TYPE_ID, QUANTITY, UNIT_PRICE, TAX_CATEGORY_ID, CAPABILITY_ID, CREATED_BY, CREATE_DATE) VALUES (PO_ID_SEQ.NEXTVAL, CUR_PRD_ID, '1', '28', '0.357143', '2', CUR_CAPABILITY_ID, 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'entitlement_uri', 'http://:hostname:/svc/user/entitlements/mm/:id:.json', 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'DEFAULT_VAT_RATE', '{"*": 0.0}', 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'capability', 'MM', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_PRODUCT_OFFERING (OFFER_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (OFR_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
  INSERT INTO DISCOUNT (ID, NAME, DESCRIPTION, FIXED_AMOUNT, PERCENT_AMOUNT, DISCOUNT_TYPE_ID, CREATED_BY, CREATE_DATE) VALUES (DSC_ID_SEQ.NEXTVAL, 'Discount', 'Target offer price 15.0 given offer total price 14.999992 and product price -5.33333831111e-06', '-5.33333831111e-06', '0', 1, 'OFFERMAKER', SYSDATE);
  INSERT INTO DISCOUNT_PRODUCT_OFFERING (DISCOUNT_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (DSC_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
  BEGIN
    SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Mobile' AND PRODUCT_STATUS_ID = 1 AND ROWNUM <= 1;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      INSERT INTO PRODUCT (ID, NAME, PRODUCTION_COST, PRODUCT_STATUS_ID, PRODUCT_URI, UNIT_PRICE, CREATED_BY, CREATE_DATE) VALUES (PRD_ID_SEQ.NEXTVAL, 'Mobile', '0', 1, NULL, '0', 'OFFERMAKER', SYSDATE);
      SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Mobile' AND PRODUCT_STATUS_ID = 1 AND ROWNUM <= 1;
    WHEN OTHERS THEN
      RAISE;
  END;
  SELECT ID INTO CUR_CAPABILITY_ID FROM CAPABILITY WHERE CODE IN LTRIM(RTRIM((UPPER('MOW')))) AND ROWNUM <= 1;
  INSERT INTO PRODUCT_OFFERING (ID, PRODUCT_ID, TAX_POLICY_TYPE_ID, QUANTITY, UNIT_PRICE, TAX_CATEGORY_ID, CAPABILITY_ID, CREATED_BY, CREATE_DATE) VALUES (PO_ID_SEQ.NEXTVAL, CUR_PRD_ID, '1', '28', '0', '2', CUR_CAPABILITY_ID, 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'entitlement_uri', 'http://:hostname:/svc/user/entitlements/mow/:id:.json', 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'DEFAULT_VAT_RATE', '{"*": 0.0}', 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'capability', 'MOW', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_PRODUCT_OFFERING (OFFER_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (OFR_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
  BEGIN
    SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Archive Article' AND PRODUCT_STATUS_ID = 1 AND ROWNUM <= 1;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      INSERT INTO PRODUCT (ID, NAME, PRODUCTION_COST, PRODUCT_STATUS_ID, PRODUCT_URI, UNIT_PRICE, CREATED_BY, CREATE_DATE) VALUES (PRD_ID_SEQ.NEXTVAL, 'Archive Article', '0', 1, NULL, '0', 'OFFERMAKER', SYSDATE);
      SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Archive Article' AND PRODUCT_STATUS_ID = 1 AND ROWNUM <= 1;
    WHEN OTHERS THEN
      RAISE;
  END;
  SELECT ID INTO CUR_CAPABILITY_ID FROM CAPABILITY WHERE CODE IN LTRIM(RTRIM((UPPER('AAA')))) AND ROWNUM <= 1;
  INSERT INTO PRODUCT_OFFERING (ID, PRODUCT_ID, TAX_POLICY_TYPE_ID, QUANTITY, UNIT_PRICE, TAX_CATEGORY_ID, CAPABILITY_ID, CREATED_BY, CREATE_DATE) VALUES (PO_ID_SEQ.NEXTVAL, CUR_PRD_ID, '1', '100', '0', '2', CUR_CAPABILITY_ID, 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'entitlement_uri', 'http://:hostname:/svc/user/entitlements/archive/size/100/:id:.json', 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'DEFAULT_VAT_RATE', '{"*": 0.0}', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_PRODUCT_OFFERING (OFFER_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (OFR_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
  BEGIN
    SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'TimesMachine' AND PRODUCT_STATUS_ID = 1 AND ROWNUM <= 1;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      INSERT INTO PRODUCT (ID, NAME, PRODUCTION_COST, PRODUCT_STATUS_ID, PRODUCT_URI, UNIT_PRICE, CREATED_BY, CREATE_DATE) VALUES (PRD_ID_SEQ.NEXTVAL, 'TimesMachine', '0', 1, NULL, '0', 'OFFERMAKER', SYSDATE);
      SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'TimesMachine' AND PRODUCT_STATUS_ID = 1 AND ROWNUM <= 1;
    WHEN OTHERS THEN
      RAISE;
  END;
  SELECT ID INTO CUR_CAPABILITY_ID FROM CAPABILITY WHERE CODE IN LTRIM(RTRIM((UPPER('NONE')))) AND ROWNUM <= 1;
  INSERT INTO PRODUCT_OFFERING (ID, PRODUCT_ID, TAX_POLICY_TYPE_ID, QUANTITY, UNIT_PRICE, TAX_CATEGORY_ID, CAPABILITY_ID, CREATED_BY, CREATE_DATE) VALUES (PO_ID_SEQ.NEXTVAL, CUR_PRD_ID, '1', '28', '0', '2', CUR_CAPABILITY_ID, 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'DEFAULT_VAT_RATE', '{"*": 0.0}', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_PRODUCT_OFFERING (OFFER_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (OFR_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
  BEGIN
    SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Smartphone' AND PRODUCT_STATUS_ID = 1 AND ROWNUM <= 1;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      INSERT INTO PRODUCT (ID, NAME, PRODUCTION_COST, PRODUCT_STATUS_ID, PRODUCT_URI, UNIT_PRICE, CREATED_BY, CREATE_DATE) VALUES (PRD_ID_SEQ.NEXTVAL, 'Smartphone', '0', 1, NULL, '0.178571', 'OFFERMAKER', SYSDATE);
      SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Smartphone' AND PRODUCT_STATUS_ID = 1 AND ROWNUM <= 1;
    WHEN OTHERS THEN
      RAISE;
  END;
  SELECT ID INTO CUR_CAPABILITY_ID FROM CAPABILITY WHERE CODE IN LTRIM(RTRIM((UPPER('MSD')))) AND ROWNUM <= 1;
  INSERT INTO PRODUCT_OFFERING (ID, PRODUCT_ID, TAX_POLICY_TYPE_ID, QUANTITY, UNIT_PRICE, TAX_CATEGORY_ID, CAPABILITY_ID, CREATED_BY, CREATE_DATE) VALUES (PO_ID_SEQ.NEXTVAL, CUR_PRD_ID, '1', '28', '0.178571', '2', CUR_CAPABILITY_ID, 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'entitlement_uri', 'http://:hostname:/svc/user/entitlements/msd/:id:.json', 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'DEFAULT_VAT_RATE', '{"*": 0.0}', 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'capability', 'MSD', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_PRODUCT_OFFERING (OFFER_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (OFR_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
  INSERT INTO DISCOUNT (ID, NAME, DESCRIPTION, FIXED_AMOUNT, PERCENT_AMOUNT, DISCOUNT_TYPE_ID, CREATED_BY, CREATE_DATE) VALUES (DSC_ID_SEQ.NEXTVAL, 'Discount', 'Target offer price 15.0 given offer total price 14.999992 and product price -2.66666168889e-06', '-2.66666168889e-06', '0', 1, 'OFFERMAKER', SYSDATE);
  INSERT INTO DISCOUNT_PRODUCT_OFFERING (DISCOUNT_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (DSC_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_OFFER_CHAIN (OFFER_ID, OFFER_CHAIN_ID, INDEX_VALUE, NUM_RECURRENCES, CREATED_BY, CREATE_DATE, updated_by, update_date) VALUES (OFR_ID_SEQ.CURRVAL, 1203652, '2', '-1', 'OFFERMAKER', SYSDATE, 'OFFERMAKER', SYSDATE);
  END;
END;
/

COMMIT;

