
BEGIN
  INSERT INTO OPS_OWNER.NOTIFICATION_TYPE (ID, VALUE, TEMPLATE_URL) VALUES (OPS_OWNER.NOTTID_SEQ.NEXTVAL, 'cancel_8week', 'N/A');
EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL;
WHEN OTHERS THEN RAISE;
END;
  /
  
BEGIN
  INSERT INTO OPS_OWNER.NOTIFICATION_TYPE (ID, VALUE, TEMPLATE_URL) VALUES (OPS_OWNER.NOTTID_SEQ.NEXTVAL, 'cancel_digital', 'N/A');
EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL;
WHEN OTHERS THEN RAISE;
END;
  /
  
BEGIN
  INSERT INTO OPS_OWNER.NOTIFICATION_TYPE (ID, VALUE, TEMPLATE_URL) VALUES (OPS_OWNER.NOTTID_SEQ.NEXTVAL, 'card_expiration', 'N/A');
EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL;
WHEN OTHERS THEN RAISE;
END;
  /
  
BEGIN
  INSERT INTO OPS_OWNER.NOTIFICATION_TYPE (ID, VALUE, TEMPLATE_URL) VALUES (OPS_OWNER.NOTTID_SEQ.NEXTVAL, 'complimentary_access2_biz', 'N/A');
EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL;
WHEN OTHERS THEN RAISE;
END;
  /
  
BEGIN
  INSERT INTO OPS_OWNER.NOTIFICATION_TYPE (ID, VALUE, TEMPLATE_URL) VALUES (OPS_OWNER.NOTTID_SEQ.NEXTVAL, 'complimentary_access2', 'N/A');
EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL;
WHEN OTHERS THEN RAISE;
END;
  /
  
BEGIN
  INSERT INTO OPS_OWNER.NOTIFICATION_TYPE (ID, VALUE, TEMPLATE_URL) VALUES (OPS_OWNER.NOTTID_SEQ.NEXTVAL, 'complimentary_access2_nr', 'N/A');
EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL;
WHEN OTHERS THEN RAISE;
END;
  /
  
BEGIN
  INSERT INTO OPS_OWNER.NOTIFICATION_TYPE (ID, VALUE, TEMPLATE_URL) VALUES (OPS_OWNER.NOTTID_SEQ.NEXTVAL, 'complimentary_access2_ns', 'N/A');
EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL;
WHEN OTHERS THEN RAISE;
END;
  /
  
BEGIN
  INSERT INTO OPS_OWNER.NOTIFICATION_TYPE (ID, VALUE, TEMPLATE_URL) VALUES (OPS_OWNER.NOTTID_SEQ.NEXTVAL, 'complimentary_access2_pr', 'N/A');
EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL;
WHEN OTHERS THEN RAISE;
END;
  /
  
BEGIN
  INSERT INTO OPS_OWNER.NOTIFICATION_TYPE (ID, VALUE, TEMPLATE_URL) VALUES (OPS_OWNER.NOTTID_SEQ.NEXTVAL, 'complimentary_access_ad', 'N/A');
EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL;
WHEN OTHERS THEN RAISE;
END;
  /
  
BEGIN
  INSERT INTO OPS_OWNER.NOTIFICATION_TYPE (ID, VALUE, TEMPLATE_URL) VALUES (OPS_OWNER.NOTTID_SEQ.NEXTVAL, 'complimentary_access_bundle_d', 'N/A');
EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL;
WHEN OTHERS THEN RAISE;
END;
  /
  
BEGIN
  INSERT INTO OPS_OWNER.NOTIFICATION_TYPE (ID, VALUE, TEMPLATE_URL) VALUES (OPS_OWNER.NOTTID_SEQ.NEXTVAL, 'iht_free_access', 'N/A');
EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL;
WHEN OTHERS THEN RAISE;
END;
  /
  
BEGIN
  INSERT INTO OPS_OWNER.NOTIFICATION_TYPE (ID, VALUE, TEMPLATE_URL) VALUES (OPS_OWNER.NOTTID_SEQ.NEXTVAL, 'meu_gc_redeemer', 'N/A');
EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL;
WHEN OTHERS THEN RAISE;
END;
  /
  
BEGIN
  INSERT INTO OPS_OWNER.NOTIFICATION_TYPE (ID, VALUE, TEMPLATE_URL) VALUES (OPS_OWNER.NOTTID_SEQ.NEXTVAL, 'meu_subscribe', 'N/A');
EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL;
WHEN OTHERS THEN RAISE;
END;
  /
  
BEGIN
  INSERT INTO OPS_OWNER.NOTIFICATION_TYPE (ID, VALUE, TEMPLATE_URL) VALUES (OPS_OWNER.NOTTID_SEQ.NEXTVAL, 'nyt_order_digital', 'N/A');
EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL;
WHEN OTHERS THEN RAISE;
END;
  /
  
BEGIN
  INSERT INTO OPS_OWNER.NOTIFICATION_TYPE (ID, VALUE, TEMPLATE_URL) VALUES (OPS_OWNER.NOTTID_SEQ.NEXTVAL, 'sartre-cancel', 'N/A');
EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL;
WHEN OTHERS THEN RAISE;
END;
  /
  
BEGIN
  INSERT INTO OPS_OWNER.NOTIFICATION_TYPE (ID, VALUE, TEMPLATE_URL) VALUES (OPS_OWNER.NOTTID_SEQ.NEXTVAL, 'sartre-decline', 'N/A');
EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL;
WHEN OTHERS THEN RAISE;
END;
  /
  
BEGIN
  INSERT INTO OPS_OWNER.NOTIFICATION_TYPE (ID, VALUE, TEMPLATE_URL) VALUES (OPS_OWNER.NOTTID_SEQ.NEXTVAL, 'sartre-digital-purchase', 'N/A');
EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL;
WHEN OTHERS THEN RAISE;
END;
  /
  
BEGIN
  INSERT INTO OPS_OWNER.NOTIFICATION_TYPE (ID, VALUE, TEMPLATE_URL) VALUES (OPS_OWNER.NOTTID_SEQ.NEXTVAL, 'sartre-gift-subscription', 'N/A');
EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL;
WHEN OTHERS THEN RAISE;
END;
  /
  
BEGIN
  INSERT INTO OPS_OWNER.NOTIFICATION_TYPE (ID, VALUE, TEMPLATE_URL) VALUES (OPS_OWNER.NOTTID_SEQ.NEXTVAL, 'sartre-purchase', 'N/A');
EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL;
WHEN OTHERS THEN RAISE;
END;
  /
  
BEGIN
  INSERT INTO OPS_OWNER.NOTIFICATION_TYPE (ID, VALUE, TEMPLATE_URL) VALUES (OPS_OWNER.NOTTID_SEQ.NEXTVAL, 'subscriber_access', 'N/A');
EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL;
WHEN OTHERS THEN RAISE;
END;
  /
  
BEGIN
  INSERT INTO OPS_OWNER.NOTIFICATION_TYPE (ID, VALUE, TEMPLATE_URL) VALUES (OPS_OWNER.NOTTID_SEQ.NEXTVAL, 'times_reader', 'N/A');
EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL;
WHEN OTHERS THEN RAISE;
END;
  /
  
exit
