BEGIN
  UPDATE OFFER_CHAIN_META_DATA SET VALUE = 'pugetsound.edu' WHERE OFFER_CHAIN_ID = 475300 AND NAME = 'REQUIRES_EMAIL_DOMAIN';
  UPDATE OFFER_CHAIN_ELIGIBILITY SET VALUE = 'pugetsound.edu' WHERE OFFER_CHAIN_ID = 475300 AND NAME = 'REQUIRES_EMAIL_DOMAIN';
  UPDATE OFFER_CHAIN_META_DATA SET VALUE = 'sunysb.edu' WHERE OFFER_CHAIN_ID = 203712 AND NAME = 'REQUIRES_EMAIL_DOMAIN';
  UPDATE OFFER_CHAIN_ELIGIBILITY SET VALUE = 'sunysb.edu' WHERE OFFER_CHAIN_ID = 203712 AND NAME = 'REQUIRES_EMAIL_DOMAIN';
  COMMIT;
END;
/
EXIT
