WHENEVER SQLERROR EXIT ROLLBACK

BEGIN
  UPDATE OFFER_CHAIN_META_DATA SET VALUE = 'once for the first 12 weeks, and every 4 weeks thereafter' WHERE OFFER_CHAIN_ID = 370489 AND NAME = 'BILLING_CYCLE';
END;
/
