CREATE USER PLATO_OWNER  PROFILE DEFAULT IDENTIFIED BY VALUES 'S:5E738ED1F38C057E62E108F411ACA6CC1120304C5180C4122920D7C981BD' DEFAULT TABLESPACE PLATO TEMPORARY TABLESPACE TEMP ACCOUNT UNLOCK;

ALTER USER PLATO_OWNER QUOTA UNLIMITED ON PLATO QUOTA UNLIMITED ON PLATO_IDX;
    
GRANT CREATE TRIGGER TO PLATO_OWNER;
GRANT CREATE SEQUENCE TO  PLATO_OWNER;
GRANT CREATE TABLE TO  PLATO_OWNER;
GRANT CREATE PROCEDURE TO  PLATO_OWNER;
GRANT CREATE SYNONYM TO  PLATO_OWNER;
GRANT CREATE VIEW TO  PLATO_OWNER;
GRANT CREATE TYPE TO  PLATO_OWNER;
GRANT CREATE SESSION TO  PLATO_OWNER;