
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
SET SCAN OFF
SET DEFINE OFF


PROMPT Creating offerchain: 0
DECLARE
  TMP_VAR NUMBER;
  CUR_PRD_ID NUMBER;
  CUR_CAPABILITY_ID NUMBER;
BEGIN
  BEGIN
    SELECT 1 INTO TMP_VAR FROM OFFER_CHAIN WHERE ID = 654697354 AND ROWNUM <= 1;
    UPDATE OFFER_CHAIN SET NAME='Crosswords - Monthly', DESCRIPTION=' Unlimited access to Premium Crosswords', PRODUCT_URI='', VENDOR_SOURCE_ID='1', BILLING_SOURCE_ID=(SELECT ID FROM BILLING_SOURCE BS WHERE BS.NAME='Sartre'), IS_SEAT_LICENSE=0, GROUP_ACCOUNT_TYPE_ID='NO',IS_ADDRESS_REQUIRED=0, OFFER_CHAIN_STATUS_ID = 1, UPDATE_DATE = SYSDATE, UPDATED_BY = 'OFFERMAKER', IS_GIFT_CERTIFICATE='0', REVOKE_ENTITLEMENTS = '0', ADOPTABILITY_WINDOW_START_DATE = to_date('17-Sep-2012 00:00:00','DD-MON-YY HH24:MI:SS'), ADOPTABILITY_WINDOW_END_DATE = to_date('01-Jan-2070 00:00:00','DD-MON-YY HH24:MI:SS') WHERE ID = 654697354;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      INSERT INTO OFFER_CHAIN (ID, NAME, DESCRIPTION, ADOPTABILITY_WINDOW_START_DATE, ADOPTABILITY_WINDOW_END_DATE, IS_GIFT_CERTIFICATE, PRODUCT_URI, OFFER_CHAIN_STATUS_ID, REVOKE_ENTITLEMENTS, VENDOR_SOURCE_ID, BILLING_SOURCE_ID, IS_SEAT_LICENSE, GROUP_ACCOUNT_TYPE_ID, IS_ADDRESS_REQUIRED, CREATED_BY, CREATE_DATE, updated_by, update_date) VALUES (654697354, 'Crosswords - Monthly', ' Unlimited access to Premium Crosswords', to_date('17-Sep-2012 00:00:00','DD-MON-YY HH24:MI:SS'), to_date('01-Jan-2070 00:00:00','DD-MON-YY HH24:MI:SS'), '0', NULL, '1', '0', '1', (SELECT ID FROM BILLING_SOURCE BS WHERE BS.NAME='Sartre'), decode('NO','IL',1,0), 'NO', '0', 'OFFERMAKER', SYSDATE, 'OFFERMAKER', SYSDATE);
  END;
  DELETE FROM OFFER_CHAIN_ELIGIBILITY WHERE offer_chain_id = 654697354;
  INSERT INTO OFFER_CHAIN_ELIGIBILITY (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (ELG_ID_SEQ.NEXTVAL, 654697354, 'IS_COMP', '0', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_ELIGIBILITY (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (ELG_ID_SEQ.NEXTVAL, 654697354, 'MAX_CONCURRENT_SUBS', '1', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_ELIGIBILITY (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (ELG_ID_SEQ.NEXTVAL, 654697354, 'INTERNAL_ONLY', '0', 'OFFERMAKER', SYSDATE);
  DELETE FROM OFFER_CHAIN_META_DATA WHERE offer_chain_id = 654697354;
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 654697354, 'BUNDLE_EXPLANATION', 'Crosswords - Monthly - 1st Month Free, then $6.95 every 30 days', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 654697354, 'PRICE_DESCRIPTION', 'Crosswords - Monthly - 1st Month Free, then $6.95 every 30 days', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 654697354, 'PRICE_SHORT_DESCRIPTION', 'Crosswords - Monthly / 1st 30 days free', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 654697354, 'OFFER_TYPE', 'Full Price', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 654697354, 'OFFER_PRICE_DESCRIPTOR', 'Risk-Free Trial', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 654697354, 'OFFER_PRICE', 'Get your first month free', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 654697354, 'OFFER_PRICE_DETAIL', '($6.95/month thereafter)', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 654697354, 'PROMO_PRICE_FOOTER_LABEL', 'First 30 days', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 654697354, 'ACTUAL_PRICE_FOOTER_LABEL', 'Product Price', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 654697354, 'BILLING_CYCLE', 'Monthly', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 654697354, 'SUBSCRIBER_TYPE', 'Regular', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 654697354, 'REFUND_POLICY', 'Monthly Billing: No refund.  Users will maintain access for the remainder of the billing period.  Users will not be billed in the next billing cycle.', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 654697354, 'ABOUT_ORDER', 'New York Times Premium Crosswords subscriptions are sold separately from e-reader editions and The New York Times Crosswords apps. All Premium Crosswords subscriptions will automatically renew and your credit card or PayPal account will be charged in advance of each billing period unless canceled. If the subscription is canceled, refunds and termination of access will follow the Terms of Sale policy. Prices are in U.S. dollars and are subject to change. Other restrictions and taxes may apply.', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 654697354, 'CANCELABLE', '1', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 654697354, 'PRORATED_REFUND_DAYS_LIMIT', '30', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 654697354, 'OPEN_TO_ANONYMOUS', '1', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 654697354, 'BUNDLE', 'Crosswords', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 654697354, 'ADX_BUNDLE', 'XWD_FULL', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 654697354, 'SIEBEL_CAMPAIGN_CODE', '3H69U', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 654697354, 'ANNUAL_PRICE', '0.00', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 654697354, 'UID', '286d54e0f95ce515dda5801eabcbfdcb182bb2924cb0b8ef63496300fb12c0ac', 'OFFERMAKER', SYSDATE);
  DELETE FROM OFFER_CHAIN_NOTIFICATION_TYPE WHERE offer_chain_id = 654697354;
  BEGIN
    SELECT 1 INTO TMP_VAR FROM ACTION WHERE NAME = 'SUBSCRIBE_TO_OFFER_CHAIN';
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      INSERT INTO ACTION (ID, NAME, CREATE_DATE, CREATED_BY) VALUES (ACTION_ID_SEQ.NEXTVAL, 'SUBSCRIBE_TO_OFFER_CHAIN', SYSDATE, 'OFFERMAKER');
  END;
  BEGIN
    SELECT 1 INTO TMP_VAR FROM OPS_OWNER.NOTIFICATION_TYPE WHERE VALUE = 'sartre-purchase-xwd';
  EXCEPTION
    WHEN NO_DATA_FOUND THEN NULL;
      -- INSERT INTO OPS_OWNER.NOTIFICATION_TYPE (ID, VALUE, TEMPLATE_URL) VALUES (OPS_OWNER.NOTTID_SEQ.NEXTVAL, 'sartre-purchase-xwd', 'N/A');
  END;
  BEGIN
    SELECT 1 INTO TMP_VAR FROM ACTION WHERE NAME = 'UPGRADE_SUBSCRIPTION';
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      INSERT INTO ACTION (ID, NAME, CREATE_DATE, CREATED_BY) VALUES (ACTION_ID_SEQ.NEXTVAL, 'UPGRADE_SUBSCRIPTION', SYSDATE, 'OFFERMAKER');
  END;
  BEGIN
    SELECT 1 INTO TMP_VAR FROM OPS_OWNER.NOTIFICATION_TYPE WHERE VALUE = 'sartre-purchase-xwd';
  EXCEPTION
    WHEN NO_DATA_FOUND THEN NULL;
      -- INSERT INTO OPS_OWNER.NOTIFICATION_TYPE (ID, VALUE, TEMPLATE_URL) VALUES (OPS_OWNER.NOTTID_SEQ.NEXTVAL, 'sartre-purchase-xwd', 'N/A');
  END;
  BEGIN
    SELECT 1 INTO TMP_VAR FROM ACTION WHERE NAME = 'CANCEL_SUBSCRIPTION';
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      INSERT INTO ACTION (ID, NAME, CREATE_DATE, CREATED_BY) VALUES (ACTION_ID_SEQ.NEXTVAL, 'CANCEL_SUBSCRIPTION', SYSDATE, 'OFFERMAKER');
  END;
  BEGIN
    SELECT 1 INTO TMP_VAR FROM OPS_OWNER.NOTIFICATION_TYPE WHERE VALUE = 'sartre-cancel-xwd';
  EXCEPTION
    WHEN NO_DATA_FOUND THEN NULL;
      -- INSERT INTO OPS_OWNER.NOTIFICATION_TYPE (ID, VALUE, TEMPLATE_URL) VALUES (OPS_OWNER.NOTTID_SEQ.NEXTVAL, 'sartre-cancel-xwd', 'N/A');
  END;
  BEGIN
    SELECT 1 INTO TMP_VAR FROM ACTION WHERE NAME = 'SYSTEM_CANCEL';
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      INSERT INTO ACTION (ID, NAME, CREATE_DATE, CREATED_BY) VALUES (ACTION_ID_SEQ.NEXTVAL, 'SYSTEM_CANCEL', SYSDATE, 'OFFERMAKER');
  END;
  BEGIN
    SELECT 1 INTO TMP_VAR FROM OPS_OWNER.NOTIFICATION_TYPE WHERE VALUE = 'sartre-decline';
  EXCEPTION
    WHEN NO_DATA_FOUND THEN NULL;
      -- INSERT INTO OPS_OWNER.NOTIFICATION_TYPE (ID, VALUE, TEMPLATE_URL) VALUES (OPS_OWNER.NOTTID_SEQ.NEXTVAL, 'sartre-decline', 'N/A');
  END;
  BEGIN
    SELECT 1 INTO TMP_VAR FROM ACTION WHERE NAME = 'CREDIT_CARD_EXP';
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      INSERT INTO ACTION (ID, NAME, CREATE_DATE, CREATED_BY) VALUES (ACTION_ID_SEQ.NEXTVAL, 'CREDIT_CARD_EXP', SYSDATE, 'OFFERMAKER');
  END;
  BEGIN
    SELECT 1 INTO TMP_VAR FROM OPS_OWNER.NOTIFICATION_TYPE WHERE VALUE = 'card_expiration';
  EXCEPTION
    WHEN NO_DATA_FOUND THEN NULL;
      -- INSERT INTO OPS_OWNER.NOTIFICATION_TYPE (ID, VALUE, TEMPLATE_URL) VALUES (OPS_OWNER.NOTTID_SEQ.NEXTVAL, 'card_expiration', 'N/A');
  END;
  INSERT INTO OFFER_CHAIN_NOTIFICATION_TYPE (ID, OFFER_CHAIN_ID, NOTIFICATION_TYPE_ID, ACTION_ID, CREATED_BY, CREATE_DATE) VALUES (OCET_ID_SEQ.NEXTVAL, 654697354, (SELECT ID FROM OPS_OWNER.NOTIFICATION_TYPE WHERE VALUE = 'sartre-purchase-xwd'), (SELECT ID FROM ACTION WHERE NAME = 'SUBSCRIBE_TO_OFFER_CHAIN'), 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_NOTIFICATION_TYPE (ID, OFFER_CHAIN_ID, NOTIFICATION_TYPE_ID, ACTION_ID, CREATED_BY, CREATE_DATE) VALUES (OCET_ID_SEQ.NEXTVAL, 654697354, (SELECT ID FROM OPS_OWNER.NOTIFICATION_TYPE WHERE VALUE = 'sartre-purchase-xwd'), (SELECT ID FROM ACTION WHERE NAME = 'UPGRADE_SUBSCRIPTION'), 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_NOTIFICATION_TYPE (ID, OFFER_CHAIN_ID, NOTIFICATION_TYPE_ID, ACTION_ID, CREATED_BY, CREATE_DATE) VALUES (OCET_ID_SEQ.NEXTVAL, 654697354, (SELECT ID FROM OPS_OWNER.NOTIFICATION_TYPE WHERE VALUE = 'sartre-cancel-xwd'), (SELECT ID FROM ACTION WHERE NAME = 'CANCEL_SUBSCRIPTION'), 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_NOTIFICATION_TYPE (ID, OFFER_CHAIN_ID, NOTIFICATION_TYPE_ID, ACTION_ID, CREATED_BY, CREATE_DATE) VALUES (OCET_ID_SEQ.NEXTVAL, 654697354, (SELECT ID FROM OPS_OWNER.NOTIFICATION_TYPE WHERE VALUE = 'sartre-decline'), (SELECT ID FROM ACTION WHERE NAME = 'SYSTEM_CANCEL'), 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_CHAIN_NOTIFICATION_TYPE (ID, OFFER_CHAIN_ID, NOTIFICATION_TYPE_ID, ACTION_ID, CREATED_BY, CREATE_DATE) VALUES (OCET_ID_SEQ.NEXTVAL, 654697354, (SELECT ID FROM OPS_OWNER.NOTIFICATION_TYPE WHERE VALUE = 'card_expiration'), (SELECT ID FROM ACTION WHERE NAME = 'CREDIT_CARD_EXP'), 'OFFERMAKER', SYSDATE);
  BEGIN
    SELECT 1 INTO TMP_VAR FROM OFFER_OFFER_CHAIN WHERE OFFER_CHAIN_ID = 654697354 AND INDEX_VALUE = 0 AND ROWNUM <= 1;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
  INSERT INTO OFFER (ID, OFFER_STATUS_ID, ENTITLEMENT_DURATION, CREATED_BY, CREATE_DATE, updated_by, update_date) VALUES (OFR_ID_SEQ.NEXTVAL, 1, 'P0Y0M30DT0H0M', 'OFFERMAKER', SYSDATE, 'OFFERMAKER', SYSDATE);
  BEGIN
    SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Crosswords' AND PRODUCT_STATUS_ID = 1 AND ROWNUM <= 1;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      INSERT INTO PRODUCT (ID, NAME, PRODUCTION_COST, PRODUCT_STATUS_ID, PRODUCT_URI, UNIT_PRICE, CREATED_BY, CREATE_DATE) VALUES (PRD_ID_SEQ.NEXTVAL, 'Crosswords', '0', 1, NULL, '0.24', 'OFFERMAKER', SYSDATE);
      SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Crosswords' AND PRODUCT_STATUS_ID = 1 AND ROWNUM <= 1;
    WHEN OTHERS THEN
      RAISE;
  END;
  SELECT ID INTO CUR_CAPABILITY_ID FROM CAPABILITY WHERE CODE IN LTRIM(RTRIM((UPPER('XWD')))) AND ROWNUM <= 1;
  INSERT INTO PRODUCT_OFFERING (ID, PRODUCT_ID, TAX_POLICY_TYPE_ID, QUANTITY, UNIT_PRICE, TAX_CATEGORY_ID, CAPABILITY_ID, CREATED_BY, CREATE_DATE) VALUES (PO_ID_SEQ.NEXTVAL, CUR_PRD_ID, '1', '30', '0.24', '4', CUR_CAPABILITY_ID, 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'entitlement_uri', 'http://:hostname:/svc/user/entitlements/crosswords/:id:.json', 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'capability', 'XWD', 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'DEFAULT_VAT_RATE', '{"*": 0.2}', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_PRODUCT_OFFERING (OFFER_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (OFR_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
  INSERT INTO DISCOUNT (ID, NAME, DESCRIPTION, FIXED_AMOUNT, PERCENT_AMOUNT, DISCOUNT_TYPE_ID, CREATED_BY, CREATE_DATE) VALUES (DSC_ID_SEQ.NEXTVAL, 'Discount', 'Target offer price 0.0 given offer total price 7.20 and product price 7.2', '7.2', '0', 1, 'OFFERMAKER', SYSDATE);
  INSERT INTO DISCOUNT_PRODUCT_OFFERING (DISCOUNT_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (DSC_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_OFFER_CHAIN (OFFER_ID, OFFER_CHAIN_ID, INDEX_VALUE, NUM_RECURRENCES, CREATED_BY, CREATE_DATE, updated_by, update_date) VALUES (OFR_ID_SEQ.CURRVAL, 654697354, '0', '1', 'OFFERMAKER', SYSDATE, 'OFFERMAKER', SYSDATE);
  END;
  BEGIN
    SELECT 1 INTO TMP_VAR FROM OFFER_OFFER_CHAIN WHERE OFFER_CHAIN_ID = 654697354 AND INDEX_VALUE = 1 AND ROWNUM <= 1;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
  INSERT INTO OFFER (ID, OFFER_STATUS_ID, ENTITLEMENT_DURATION, CREATED_BY, CREATE_DATE, updated_by, update_date) VALUES (OFR_ID_SEQ.NEXTVAL, 1, 'P0Y0M30DT0H0M', 'OFFERMAKER', SYSDATE, 'OFFERMAKER', SYSDATE);
  BEGIN
    SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Crosswords' AND PRODUCT_STATUS_ID = 1 AND ROWNUM <= 1;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      INSERT INTO PRODUCT (ID, NAME, PRODUCTION_COST, PRODUCT_STATUS_ID, PRODUCT_URI, UNIT_PRICE, CREATED_BY, CREATE_DATE) VALUES (PRD_ID_SEQ.NEXTVAL, 'Crosswords', '0', 1, NULL, '0.24', 'OFFERMAKER', SYSDATE);
      SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Crosswords' AND PRODUCT_STATUS_ID = 1 AND ROWNUM <= 1;
    WHEN OTHERS THEN
      RAISE;
  END;
  SELECT ID INTO CUR_CAPABILITY_ID FROM CAPABILITY WHERE CODE IN LTRIM(RTRIM((UPPER('XWD')))) AND ROWNUM <= 1;
  INSERT INTO PRODUCT_OFFERING (ID, PRODUCT_ID, TAX_POLICY_TYPE_ID, QUANTITY, UNIT_PRICE, TAX_CATEGORY_ID, CAPABILITY_ID, CREATED_BY, CREATE_DATE) VALUES (PO_ID_SEQ.NEXTVAL, CUR_PRD_ID, '1', '30', '0.24', '4', CUR_CAPABILITY_ID, 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'entitlement_uri', 'http://:hostname:/svc/user/entitlements/crosswords/:id:.json', 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'capability', 'XWD', 'OFFERMAKER', SYSDATE);
  INSERT INTO PRODUCT_OFFERING_META_DATA (ID, PRODUCT_OFFERING_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (PROMD_ID_SEQ.NEXTVAL, PO_ID_SEQ.CURRVAL, 'DEFAULT_VAT_RATE', '{"*": 0.2}', 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_PRODUCT_OFFERING (OFFER_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (OFR_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
  INSERT INTO DISCOUNT (ID, NAME, DESCRIPTION, FIXED_AMOUNT, PERCENT_AMOUNT, DISCOUNT_TYPE_ID, CREATED_BY, CREATE_DATE) VALUES (DSC_ID_SEQ.NEXTVAL, 'Discount', 'Target offer price 6.95 given offer total price 7.20 and product price 0.25', '0.25', '0', 1, 'OFFERMAKER', SYSDATE);
  INSERT INTO DISCOUNT_PRODUCT_OFFERING (DISCOUNT_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (DSC_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
  INSERT INTO OFFER_OFFER_CHAIN (OFFER_ID, OFFER_CHAIN_ID, INDEX_VALUE, NUM_RECURRENCES, CREATED_BY, CREATE_DATE, updated_by, update_date) VALUES (OFR_ID_SEQ.CURRVAL, 654697354, '1', '-1', 'OFFERMAKER', SYSDATE, 'OFFERMAKER', SYSDATE);
  END;
END;
/

COMMIT;

