
BEGIN
  INSERT INTO CORE_OWNER.NOTIFICATION_TYPE (ID, VALUE, TEMPLATE_URL) VALUES (CORE_OWNER.NOTTID_SEQ.NEXTVAL, 'complimentary_access2', 'N/A');
EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL;
WHEN OTHERS THEN RAISE;
END;
/

BEGIN
  INSERT INTO CORE_OWNER.NOTIFICATION_TYPE (ID, VALUE, TEMPLATE_URL) VALUES (CORE_OWNER.NOTTID_SEQ.NEXTVAL, 'complimentary_access2_biz', 'N/A');
EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL;
WHEN OTHERS THEN RAISE;
END;
/

BEGIN
  INSERT INTO CORE_OWNER.NOTIFICATION_TYPE (ID, VALUE, TEMPLATE_URL) VALUES (CORE_OWNER.NOTTID_SEQ.NEXTVAL, 'complimentary_access2_cr', 'N/A');
EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL;
WHEN OTHERS THEN RAISE;
END;
/

BEGIN
  INSERT INTO CORE_OWNER.NOTIFICATION_TYPE (ID, VALUE, TEMPLATE_URL) VALUES (CORE_OWNER.NOTTID_SEQ.NEXTVAL, 'complimentary_access2_nr', 'N/A');
EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL;
WHEN OTHERS THEN RAISE;
END;
/

BEGIN
  INSERT INTO CORE_OWNER.NOTIFICATION_TYPE (ID, VALUE, TEMPLATE_URL) VALUES (CORE_OWNER.NOTTID_SEQ.NEXTVAL, 'complimentary_access2_ns', 'N/A');
EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL;
WHEN OTHERS THEN RAISE;
END;
/

BEGIN
  INSERT INTO CORE_OWNER.NOTIFICATION_TYPE (ID, VALUE, TEMPLATE_URL) VALUES (CORE_OWNER.NOTTID_SEQ.NEXTVAL, 'complimentary_access2_pr', 'N/A');
EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL;
WHEN OTHERS THEN RAISE;
END;
/
COMMIT;
exit
