WHENEVER SQLERROR EXIT ROLLBACK;

-- resolve version inconsistency in production
UPDATE SYS_VERSION SET VERSION = 125;
COMMIT;

variable is_current_version_fine NUMBER;
variable change_version NUMBER;
variable bad_current_version VARCHAR2(1024);

exec :change_version := 126;
exec PROCS_SYSTEM_V14.CHECK_VERSION(:change_version - 1, :is_current_version_fine);
exec :bad_current_version := 'Current version is bad, please update your version to '||(:change_version-1);

BEGIN
  IF (:is_current_version_fine != 0) THEN
    RAISE_APPLICATION_ERROR(-20001, :bad_current_version);
  END IF;
END;
/

CREATE INDEX CC_REQUEST_STATUS_UPD_DATE_IDX ON CC_REQUEST_FILE(CC_REQUEST_FILE_STATUS, UPDATE_DATE) TABLESPACE CORE_IDX;

CREATE INDEX CC_REQUEST_FILE_ID_STATUS_IDX ON CC_REQUEST_FILE(ID, CC_REQUEST_FILE_STATUS) TABLESPACE CORE_IDX;

CREATE INDEX CC_UPPER_CHASE_PROFILE_ID_IDX ON CREDIT_CARD (UPPER(CHASE_PROFILE_ID)) TABLESPACE CORE_IDX;

-- new request file statuses
INSERT INTO CC_REQUEST_FILE_STATUS (ID, DESCRIPTION, CREATE_DATE, CREATED_BY)
VALUES ('NO_RESPONSE', 'No response file downloaded from Chase', SYSDATE, 'JIRA-RV-583');

INSERT INTO CC_REQUEST_FILE_STATUS (ID, DESCRIPTION, CREATE_DATE, CREATED_BY)
VALUES ('NO_REPORT', 'No report file downloaded from Chase', SYSDATE, 'JIRA-RV-583');

INSERT INTO CC_REQUEST_FILE_STATUS (ID, DESCRIPTION, CREATE_DATE, CREATED_BY)
VALUES ('RESPONSE_DOWNLOADED', 'The response file has been downloaded from Chase', SYSDATE, 'JIRA-RV-583');

INSERT INTO CC_REQUEST_FILE_STATUS (ID, DESCRIPTION, CREATE_DATE, CREATED_BY)
VALUES ('REPORT_COMPLETE', 'The report file has been successfully processed', SYSDATE, 'JIRA-RV-583');

INSERT INTO CC_REQUEST_FILE_STATUS (ID, DESCRIPTION, CREATE_DATE, CREATED_BY)
VALUES ('REPORT_COMPLETE_WITH_FAILURES', 'The report file has been successfully processed despite request failures', SYSDATE, 'JIRA-RV-583');

INSERT INTO CC_REQUEST_FILE_STATUS (ID, DESCRIPTION, CREATE_DATE, CREATED_BY)
VALUES ('RESPONSE_COMPLETE', 'The response file has been successfully processed', SYSDATE, 'JIRA-RV-583');

-- new credit card update statuses
INSERT INTO CC_UPDATE_STATUS (ID, DESCRIPTION, CREATE_DATE, CREATED_BY)
VALUES ('REQUEST_OK', 'OK response received for credit card request', SYSDATE, 'JIRA-RV-583');

INSERT INTO CC_UPDATE_STATUS (ID, DESCRIPTION, CREATE_DATE, CREATED_BY)
VALUES ('REQUEST_FAILED', 'Error response received for credit card request', SYSDATE, 'JIRA-RV-583');

commit;

ALTER TABLE CC_UPDATE ADD (
  RESPONSE_PROC_STATUS_CODE NUMBER NULL,
  RESPONSE_PROC_STATUS_MESSAGE VARCHAR2(2000) NULL
);

EXEC PROCS_SYSTEM_V14.INCREMENT_VERSION();

