WHENEVER SQLERROR EXIT ROLLBACK;

CREATE TABLE GC_CAMPAIGN_AND_REF (
  GC_ID NUMBER REFERENCES GIFT_CERTIFICATE(ID) ON DELETE CASCADE,
  CAMPAIGN VARCHAR2(255) NOT NULL,
  REFERENCE_CODE VARCHAR2(255) PRIMARY KEY
);

