BEGIN
  UPDATE
    OFFER_CHAIN
  SET
    ADOPTABILITY_WINDOW_START_DATE = '14-MAR-2011',
    UPDATE_DATE = SYSDATE,
    UPDATED_BY = 'BUGZILLA_CASE-48551'
  WHERE
    CREATE_DATE >= '03-MAR-2011'
    AND NOT ID IN (
      SELECT OFFER_CHAIN_ID FROM OFFER_CHAIN_META_DATA WHERE NAME = 'IS_COMP' AND VALUE = '1'
    );
END;
/

BEGIN
  UPDATE
    OFFER_CHAIN
  SET
    ADOPTABILITY_WINDOW_START_DATE = '07-MAR-2011',
    ADOPTABILITY_WINDOW_END_DATE = '10-MAR-2011',
    UPDATE_DATE = SYSDATE,
    UPDATED_BY = 'OFFERMAKER'
  WHERE
    ID IN (1000029, 224016, 231921, 439509);

  COMMIT;
END;
/
