WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
SET SCAN OFF
SET DEFINE OFF
DECLARE
TMP_VAR NUMBER;
CUR_PRD_ID NUMBER;
CUR_CAPABILITY_ID NUMBER;
BEGIN
BEGIN
  SELECT 1 INTO TMP_VAR FROM OFFER_CHAIN WHERE ID = 4271558976 AND ROWNUM <= 1;
  UPDATE OFFER_CHAIN SET NAME='NYTimes: Web + Smartphone App', DESCRIPTION='Unlimited access to NYTimes.com and the NYTimes smartphone app.*', PRODUCT_URI='', VENDOR_SOURCE_ID='1', BILLING_SOURCE_ID=(SELECT ID FROM BILLING_SOURCE BS WHERE BS.NAME='Sartre'), IS_SEAT_LICENSE=0, GROUP_ACCOUNT_TYPE_ID='NO',IS_ADDRESS_REQUIRED=0, OFFER_CHAIN_STATUS_ID = 1, UPDATE_DATE = SYSDATE, UPDATED_BY = 'OFFERMAKER', IS_GIFT_CERTIFICATE='0', REVOKE_ENTITLEMENTS = '0', ADOPTABILITY_WINDOW_START_DATE = to_date('24-Jul-2013 00:00:00','DD-MON-YY HH24:MI:SS'), ADOPTABILITY_WINDOW_END_DATE = to_date('31-Dec-2014 00:00:00','DD-MON-YY HH24:MI:SS'), AMAZON_APPSTORE_SKU=NULL WHERE ID = 4271558976;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    INSERT INTO OFFER_CHAIN (ID, NAME, DESCRIPTION, ADOPTABILITY_WINDOW_START_DATE, ADOPTABILITY_WINDOW_END_DATE, IS_GIFT_CERTIFICATE, PRODUCT_URI, OFFER_CHAIN_STATUS_ID, REVOKE_ENTITLEMENTS, VENDOR_SOURCE_ID, BILLING_SOURCE_ID, IS_SEAT_LICENSE, GROUP_ACCOUNT_TYPE_ID, IS_ADDRESS_REQUIRED, AMAZON_APPSTORE_SKU, CREATED_BY, CREATE_DATE, updated_by, update_date) VALUES (4271558976, 'NYTimes: Web + Smartphone App', 'Unlimited access to NYTimes.com and the NYTimes smartphone app.*', to_date('24-Jul-2013 00:00:00','DD-MON-YY HH24:MI:SS'), to_date('31-Dec-2014 00:00:00','DD-MON-YY HH24:MI:SS'), '0', NULL, '1', '0', '1', (SELECT ID FROM BILLING_SOURCE BS WHERE BS.NAME='Sartre'), decode('NO','IL',1,0), 'NO', '0', '', 'OFFERMAKER', SYSDATE, 'OFFERMAKER', SYSDATE);
END;
DELETE FROM OFFER_CHAIN_ELIGIBILITY WHERE offer_chain_id = 4271558976;
INSERT INTO OFFER_CHAIN_ELIGIBILITY (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (ELG_ID_SEQ.NEXTVAL, 4271558976, 'IS_COMP', '0', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_ELIGIBILITY (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (ELG_ID_SEQ.NEXTVAL, 4271558976, 'MAX_CONCURRENT_SUBS', '1', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_ELIGIBILITY (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (ELG_ID_SEQ.NEXTVAL, 4271558976, 'INTERNAL_ONLY', '0', 'OFFERMAKER', SYSDATE);
DELETE FROM OFFER_CHAIN_META_DATA WHERE offer_chain_id = 4271558976;
INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 4271558976, 'BUNDLE_EXPLANATION', 'Web +Smartphone 12 wk free, Thereafter $15.00/4 wks', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 4271558976, 'PRICE_DESCRIPTION', '12 wks free and then Regular Price $15.00 every 4 weeks', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 4271558976, 'PRICE_SHORT_DESCRIPTION', ' BNDL A 12 wk free and then $15.00 / 4 weeks', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 4271558976, 'OFFER_TYPE', 'Digital Subscription for 12 weeks free and then full price', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 4271558976, 'OFFER_PRICE_DESCRIPTOR', 'RISK FREE TRIAL', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 4271558976, 'OFFER_PRICE', 'Get your first 12 weeks free', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 4271558976, 'OFFER_PRICE_DETAIL', '($3.75 / week thereafter)', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 4271558976, 'PROMO_PRICE_FOOTER_LABEL', 'First 12 weeks', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 4271558976, 'ACTUAL_PRICE_FOOTER_LABEL', 'Thereafter', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 4271558976, 'BILLING_CYCLE', 'every 4 weeks', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 4271558976, 'SUBSCRIBER_TYPE', 'Regular', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 4271558976, 'REFUND_POLICY', 'Monthly Billing: No refund.  Users will maintain access for the remainder of the billing period.  Users will not be billed in the next billing cycle.', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 4271558976, 'CANCELABLE', '1', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 4271558976, 'PRORATED_REFUND_DAYS_LIMIT', '28', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 4271558976, 'OPEN_TO_ANONYMOUS', '1', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 4271558976, 'BUNDLE', 'Bundle A (Web+SP)', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 4271558976, 'ADX_BUNDLE', 'MM_PROMO', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 4271558976, 'SIEBEL_CAMPAIGN_CODE', '3K9WH', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 4271558976, 'ANNUAL_PRICE', '195.00', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 4271558976, 'UID', '74657585a49947a9a60d948df0cd764c292d0e56cd531851ce42e61659faf931', 'OFFERMAKER', SYSDATE);
DELETE FROM OFFER_CHAIN_NOTIFICATION_TYPE WHERE offer_chain_id = 4271558976;
BEGIN
  SELECT 1 INTO TMP_VAR FROM ACTION WHERE NAME = 'SUBSCRIBE_TO_OFFER_CHAIN';
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    INSERT INTO ACTION (ID, NAME, CREATE_DATE, CREATED_BY) VALUES (ACTION_ID_SEQ.NEXTVAL, 'SUBSCRIBE_TO_OFFER_CHAIN', SYSDATE, 'OFFERMAKER');
END;
BEGIN
  SELECT 1 INTO TMP_VAR FROM CORE_OWNER.NOTIFICATION_TYPE WHERE VALUE = 'sartre-digital-purchase';
EXCEPTION
  WHEN NO_DATA_FOUND THEN NULL;
    INSERT INTO CORE_OWNER.NOTIFICATION_TYPE (ID, VALUE, TEMPLATE_URL) VALUES (CORE_OWNER.NOTTID_SEQ.NEXTVAL, 'sartre-digital-purchase', 'N/A');
END;
BEGIN
  SELECT 1 INTO TMP_VAR FROM ACTION WHERE NAME = 'UPGRADE_SUBSCRIPTION';
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    INSERT INTO ACTION (ID, NAME, CREATE_DATE, CREATED_BY) VALUES (ACTION_ID_SEQ.NEXTVAL, 'UPGRADE_SUBSCRIPTION', SYSDATE, 'OFFERMAKER');
END;
BEGIN
  SELECT 1 INTO TMP_VAR FROM CORE_OWNER.NOTIFICATION_TYPE WHERE VALUE = 'sartre-digital-purchase';
EXCEPTION
  WHEN NO_DATA_FOUND THEN NULL;
    INSERT INTO CORE_OWNER.NOTIFICATION_TYPE (ID, VALUE, TEMPLATE_URL) VALUES (CORE_OWNER.NOTTID_SEQ.NEXTVAL, 'sartre-digital-purchase', 'N/A');
END;
BEGIN
  SELECT 1 INTO TMP_VAR FROM ACTION WHERE NAME = 'CANCEL_SUBSCRIPTION';
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    INSERT INTO ACTION (ID, NAME, CREATE_DATE, CREATED_BY) VALUES (ACTION_ID_SEQ.NEXTVAL, 'CANCEL_SUBSCRIPTION', SYSDATE, 'OFFERMAKER');
END;
BEGIN
  SELECT 1 INTO TMP_VAR FROM CORE_OWNER.NOTIFICATION_TYPE WHERE VALUE = 'sartre-cancel';
EXCEPTION
  WHEN NO_DATA_FOUND THEN NULL;
    INSERT INTO CORE_OWNER.NOTIFICATION_TYPE (ID, VALUE, TEMPLATE_URL) VALUES (CORE_OWNER.NOTTID_SEQ.NEXTVAL, 'sartre-cancel', 'N/A');
END;
BEGIN
  SELECT 1 INTO TMP_VAR FROM ACTION WHERE NAME = 'SYSTEM_CANCEL';
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    INSERT INTO ACTION (ID, NAME, CREATE_DATE, CREATED_BY) VALUES (ACTION_ID_SEQ.NEXTVAL, 'SYSTEM_CANCEL', SYSDATE, 'OFFERMAKER');
END;
BEGIN
  SELECT 1 INTO TMP_VAR FROM CORE_OWNER.NOTIFICATION_TYPE WHERE VALUE = 'sartre-decline';
EXCEPTION
  WHEN NO_DATA_FOUND THEN NULL;
    INSERT INTO CORE_OWNER.NOTIFICATION_TYPE (ID, VALUE, TEMPLATE_URL) VALUES (CORE_OWNER.NOTTID_SEQ.NEXTVAL, 'sartre-decline', 'N/A');
END;
BEGIN
  SELECT 1 INTO TMP_VAR FROM ACTION WHERE NAME = 'CREDIT_CARD_EXP';
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    INSERT INTO ACTION (ID, NAME, CREATE_DATE, CREATED_BY) VALUES (ACTION_ID_SEQ.NEXTVAL, 'CREDIT_CARD_EXP', SYSDATE, 'OFFERMAKER');
END;
BEGIN
  SELECT 1 INTO TMP_VAR FROM CORE_OWNER.NOTIFICATION_TYPE WHERE VALUE = 'card_expiration';
EXCEPTION
  WHEN NO_DATA_FOUND THEN NULL;
    INSERT INTO CORE_OWNER.NOTIFICATION_TYPE (ID, VALUE, TEMPLATE_URL) VALUES (CORE_OWNER.NOTTID_SEQ.NEXTVAL, 'card_expiration', 'N/A');
END;
INSERT INTO OFFER_CHAIN_NOTIFICATION_TYPE (ID, OFFER_CHAIN_ID, NOTIFICATION_TYPE_ID, ACTION_ID, CREATED_BY, CREATE_DATE) VALUES (OCET_ID_SEQ.NEXTVAL, 4271558976, (SELECT ID FROM CORE_OWNER.NOTIFICATION_TYPE WHERE VALUE = 'sartre-digital-purchase'), (SELECT ID FROM ACTION WHERE NAME = 'SUBSCRIBE_TO_OFFER_CHAIN'), 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_NOTIFICATION_TYPE (ID, OFFER_CHAIN_ID, NOTIFICATION_TYPE_ID, ACTION_ID, CREATED_BY, CREATE_DATE) VALUES (OCET_ID_SEQ.NEXTVAL, 4271558976, (SELECT ID FROM CORE_OWNER.NOTIFICATION_TYPE WHERE VALUE = 'sartre-digital-purchase'), (SELECT ID FROM ACTION WHERE NAME = 'UPGRADE_SUBSCRIPTION'), 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_NOTIFICATION_TYPE (ID, OFFER_CHAIN_ID, NOTIFICATION_TYPE_ID, ACTION_ID, CREATED_BY, CREATE_DATE) VALUES (OCET_ID_SEQ.NEXTVAL, 4271558976, (SELECT ID FROM CORE_OWNER.NOTIFICATION_TYPE WHERE VALUE = 'sartre-cancel'), (SELECT ID FROM ACTION WHERE NAME = 'CANCEL_SUBSCRIPTION'), 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_NOTIFICATION_TYPE (ID, OFFER_CHAIN_ID, NOTIFICATION_TYPE_ID, ACTION_ID, CREATED_BY, CREATE_DATE) VALUES (OCET_ID_SEQ.NEXTVAL, 4271558976, (SELECT ID FROM CORE_OWNER.NOTIFICATION_TYPE WHERE VALUE = 'sartre-decline'), (SELECT ID FROM ACTION WHERE NAME = 'SYSTEM_CANCEL'), 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_NOTIFICATION_TYPE (ID, OFFER_CHAIN_ID, NOTIFICATION_TYPE_ID, ACTION_ID, CREATED_BY, CREATE_DATE) VALUES (OCET_ID_SEQ.NEXTVAL, 4271558976, (SELECT ID FROM CORE_OWNER.NOTIFICATION_TYPE WHERE VALUE = 'card_expiration'), (SELECT ID FROM ACTION WHERE NAME = 'CREDIT_CARD_EXP'), 'OFFERMAKER', SYSDATE);
BEGIN
  SELECT 1 INTO TMP_VAR FROM OFFER_OFFER_CHAIN WHERE OFFER_CHAIN_ID = 4271558976 AND INDEX_VALUE = 0 AND ROWNUM <= 1;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
INSERT INTO OFFER (ID, OFFER_STATUS_ID, ENTITLEMENT_DURATION, CREATED_BY, CREATE_DATE, updated_by, update_date) VALUES (OFR_ID_SEQ.NEXTVAL, 1, 'P0Y0M84DT0H0M', 'OFFERMAKER', SYSDATE, 'OFFERMAKER', SYSDATE);
BEGIN
  SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Web' AND ROWNUM <= 1;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    INSERT INTO PRODUCT (ID, NAME, CREATED_BY, CREATE_DATE) VALUES (PRD_ID_SEQ.NEXTVAL, 'Web', 'OFFERMAKER', SYSDATE);
    SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Web' AND ROWNUM <= 1;
  WHEN OTHERS THEN
    RAISE;
END;
INSERT INTO PRODUCT_OFFERING (ID, PRODUCT_ID, TAX_POLICY_TYPE_ID, QUANTITY, UNIT_PRICE, CREATED_BY, CREATE_DATE) VALUES (PO_ID_SEQ.NEXTVAL, CUR_PRD_ID, '1', '84', '0.357143', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_PRODUCT_OFFERING (OFFER_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (OFR_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
INSERT INTO DISCOUNT (ID, NAME, DESCRIPTION, FIXED_AMOUNT, PERCENT_AMOUNT, DISCOUNT_TYPE_ID, CREATED_BY, CREATE_DATE) VALUES (DSC_ID_SEQ.NEXTVAL, 'Discount', 'Off: 0.0. P.Disc: 0.0000. P.Full: 30.0000', '30.00', '0', 1, 'OFFERMAKER', SYSDATE);
INSERT INTO DISCOUNT_PRODUCT_OFFERING (DISCOUNT_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (DSC_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
BEGIN
  SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Mobile' AND ROWNUM <= 1;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    INSERT INTO PRODUCT (ID, NAME, CREATED_BY, CREATE_DATE) VALUES (PRD_ID_SEQ.NEXTVAL, 'Mobile', 'OFFERMAKER', SYSDATE);
    SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Mobile' AND ROWNUM <= 1;
  WHEN OTHERS THEN
    RAISE;
END;
INSERT INTO PRODUCT_OFFERING (ID, PRODUCT_ID, TAX_POLICY_TYPE_ID, QUANTITY, UNIT_PRICE, CREATED_BY, CREATE_DATE) VALUES (PO_ID_SEQ.NEXTVAL, CUR_PRD_ID, '1', '84', '0', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_PRODUCT_OFFERING (OFFER_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (OFR_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
BEGIN
  SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Archive Article' AND ROWNUM <= 1;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    INSERT INTO PRODUCT (ID, NAME, CREATED_BY, CREATE_DATE) VALUES (PRD_ID_SEQ.NEXTVAL, 'Archive Article', 'OFFERMAKER', SYSDATE);
    SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Archive Article' AND ROWNUM <= 1;
  WHEN OTHERS THEN
    RAISE;
END;
INSERT INTO PRODUCT_OFFERING (ID, PRODUCT_ID, TAX_POLICY_TYPE_ID, QUANTITY, UNIT_PRICE, CREATED_BY, CREATE_DATE) VALUES (PO_ID_SEQ.NEXTVAL, CUR_PRD_ID, '1', '300', '0', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_PRODUCT_OFFERING (OFFER_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (OFR_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
BEGIN
  SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'TimesMachine' AND ROWNUM <= 1;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    INSERT INTO PRODUCT (ID, NAME, CREATED_BY, CREATE_DATE) VALUES (PRD_ID_SEQ.NEXTVAL, 'TimesMachine', 'OFFERMAKER', SYSDATE);
    SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'TimesMachine' AND ROWNUM <= 1;
  WHEN OTHERS THEN
    RAISE;
END;
INSERT INTO PRODUCT_OFFERING (ID, PRODUCT_ID, TAX_POLICY_TYPE_ID, QUANTITY, UNIT_PRICE, CREATED_BY, CREATE_DATE) VALUES (PO_ID_SEQ.NEXTVAL, CUR_PRD_ID, '1', '84', '0', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_PRODUCT_OFFERING (OFFER_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (OFR_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
BEGIN
  SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Smartphone' AND ROWNUM <= 1;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    INSERT INTO PRODUCT (ID, NAME, CREATED_BY, CREATE_DATE) VALUES (PRD_ID_SEQ.NEXTVAL, 'Smartphone', 'OFFERMAKER', SYSDATE);
    SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Smartphone' AND ROWNUM <= 1;
  WHEN OTHERS THEN
    RAISE;
END;
INSERT INTO PRODUCT_OFFERING (ID, PRODUCT_ID, TAX_POLICY_TYPE_ID, QUANTITY, UNIT_PRICE, CREATED_BY, CREATE_DATE) VALUES (PO_ID_SEQ.NEXTVAL, CUR_PRD_ID, '1', '84', '0.178571', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_PRODUCT_OFFERING (OFFER_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (OFR_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
INSERT INTO DISCOUNT (ID, NAME, DESCRIPTION, FIXED_AMOUNT, PERCENT_AMOUNT, DISCOUNT_TYPE_ID, CREATED_BY, CREATE_DATE) VALUES (DSC_ID_SEQ.NEXTVAL, 'Discount', 'Off: 0.0. P.Disc: 0.0000. P.Full: 15.0000', '15.00', '0', 1, 'OFFERMAKER', SYSDATE);
INSERT INTO DISCOUNT_PRODUCT_OFFERING (DISCOUNT_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (DSC_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_OFFER_CHAIN (OFFER_ID, OFFER_CHAIN_ID, INDEX_VALUE, NUM_RECURRENCES, CREATED_BY, CREATE_DATE, updated_by, update_date) VALUES (OFR_ID_SEQ.CURRVAL, 4271558976, '0', '1', 'OFFERMAKER', SYSDATE, 'OFFERMAKER', SYSDATE);
END;
BEGIN
  SELECT 1 INTO TMP_VAR FROM OFFER_OFFER_CHAIN WHERE OFFER_CHAIN_ID = 4271558976 AND INDEX_VALUE = 1 AND ROWNUM <= 1;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
INSERT INTO OFFER (ID, OFFER_STATUS_ID, ENTITLEMENT_DURATION, CREATED_BY, CREATE_DATE, updated_by, update_date) VALUES (OFR_ID_SEQ.NEXTVAL, 1, 'P0Y0M28DT0H0M', 'OFFERMAKER', SYSDATE, 'OFFERMAKER', SYSDATE);
BEGIN
  SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Web' AND ROWNUM <= 1;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    INSERT INTO PRODUCT (ID, NAME, CREATED_BY, CREATE_DATE) VALUES (PRD_ID_SEQ.NEXTVAL, 'Web', 'OFFERMAKER', SYSDATE);
    SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Web' AND ROWNUM <= 1;
  WHEN OTHERS THEN
    RAISE;
END;
INSERT INTO PRODUCT_OFFERING (ID, PRODUCT_ID, TAX_POLICY_TYPE_ID, QUANTITY, UNIT_PRICE, CREATED_BY, CREATE_DATE) VALUES (PO_ID_SEQ.NEXTVAL, CUR_PRD_ID, '1', '28', '0.357143', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_PRODUCT_OFFERING (OFFER_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (OFR_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
BEGIN
  SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Mobile' AND ROWNUM <= 1;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    INSERT INTO PRODUCT (ID, NAME, CREATED_BY, CREATE_DATE) VALUES (PRD_ID_SEQ.NEXTVAL, 'Mobile', 'OFFERMAKER', SYSDATE);
    SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Mobile' AND ROWNUM <= 1;
  WHEN OTHERS THEN
    RAISE;
END;
INSERT INTO PRODUCT_OFFERING (ID, PRODUCT_ID, TAX_POLICY_TYPE_ID, QUANTITY, UNIT_PRICE, CREATED_BY, CREATE_DATE) VALUES (PO_ID_SEQ.NEXTVAL, CUR_PRD_ID, '1', '28', '0', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_PRODUCT_OFFERING (OFFER_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (OFR_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
BEGIN
  SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Archive Article' AND ROWNUM <= 1;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    INSERT INTO PRODUCT (ID, NAME, CREATED_BY, CREATE_DATE) VALUES (PRD_ID_SEQ.NEXTVAL, 'Archive Article', 'OFFERMAKER', SYSDATE);
    SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Archive Article' AND ROWNUM <= 1;
  WHEN OTHERS THEN
    RAISE;
END;
INSERT INTO PRODUCT_OFFERING (ID, PRODUCT_ID, TAX_POLICY_TYPE_ID, QUANTITY, UNIT_PRICE, CREATED_BY, CREATE_DATE) VALUES (PO_ID_SEQ.NEXTVAL, CUR_PRD_ID, '1', '100', '0', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_PRODUCT_OFFERING (OFFER_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (OFR_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
BEGIN
  SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'TimesMachine' AND ROWNUM <= 1;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    INSERT INTO PRODUCT (ID, NAME, CREATED_BY, CREATE_DATE) VALUES (PRD_ID_SEQ.NEXTVAL, 'TimesMachine', 'OFFERMAKER', SYSDATE);
    SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'TimesMachine' AND ROWNUM <= 1;
  WHEN OTHERS THEN
    RAISE;
END;
INSERT INTO PRODUCT_OFFERING (ID, PRODUCT_ID, TAX_POLICY_TYPE_ID, QUANTITY, UNIT_PRICE, CREATED_BY, CREATE_DATE) VALUES (PO_ID_SEQ.NEXTVAL, CUR_PRD_ID, '1', '28', '0', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_PRODUCT_OFFERING (OFFER_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (OFR_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
BEGIN
  SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Smartphone' AND ROWNUM <= 1;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    INSERT INTO PRODUCT (ID, NAME, CREATED_BY, CREATE_DATE) VALUES (PRD_ID_SEQ.NEXTVAL, 'Smartphone', 'OFFERMAKER', SYSDATE);
    SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Smartphone' AND ROWNUM <= 1;
  WHEN OTHERS THEN
    RAISE;
END;
INSERT INTO PRODUCT_OFFERING (ID, PRODUCT_ID, TAX_POLICY_TYPE_ID, QUANTITY, UNIT_PRICE, CREATED_BY, CREATE_DATE) VALUES (PO_ID_SEQ.NEXTVAL, CUR_PRD_ID, '1', '28', '0.178571', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_PRODUCT_OFFERING (OFFER_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (OFR_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_OFFER_CHAIN (OFFER_ID, OFFER_CHAIN_ID, INDEX_VALUE, NUM_RECURRENCES, CREATED_BY, CREATE_DATE, updated_by, update_date) VALUES (OFR_ID_SEQ.CURRVAL, 4271558976, '1', '-1', 'OFFERMAKER', SYSDATE, 'OFFERMAKER', SYSDATE);
END;
END;
/
COMMIT;
DECLARE
TMP_VAR NUMBER;
CUR_PRD_ID NUMBER;
CUR_CAPABILITY_ID NUMBER;
BEGIN
BEGIN
  SELECT 1 INTO TMP_VAR FROM OFFER_CHAIN WHERE ID = 1015115892 AND ROWNUM <= 1;
  UPDATE OFFER_CHAIN SET NAME='NYTimes: Web + Tablet App', DESCRIPTION='Unlimited access to NYTimes.com and the NYTimes tablet app.*', PRODUCT_URI='', VENDOR_SOURCE_ID='1', BILLING_SOURCE_ID=(SELECT ID FROM BILLING_SOURCE BS WHERE BS.NAME='Sartre'), IS_SEAT_LICENSE=0, GROUP_ACCOUNT_TYPE_ID='NO',IS_ADDRESS_REQUIRED=0, OFFER_CHAIN_STATUS_ID = 1, UPDATE_DATE = SYSDATE, UPDATED_BY = 'OFFERMAKER', IS_GIFT_CERTIFICATE='0', REVOKE_ENTITLEMENTS = '0', ADOPTABILITY_WINDOW_START_DATE = to_date('24-Jul-2013 00:00:00','DD-MON-YY HH24:MI:SS'), ADOPTABILITY_WINDOW_END_DATE = to_date('31-Dec-2014 00:00:00','DD-MON-YY HH24:MI:SS'), AMAZON_APPSTORE_SKU=NULL WHERE ID = 1015115892;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    INSERT INTO OFFER_CHAIN (ID, NAME, DESCRIPTION, ADOPTABILITY_WINDOW_START_DATE, ADOPTABILITY_WINDOW_END_DATE, IS_GIFT_CERTIFICATE, PRODUCT_URI, OFFER_CHAIN_STATUS_ID, REVOKE_ENTITLEMENTS, VENDOR_SOURCE_ID, BILLING_SOURCE_ID, IS_SEAT_LICENSE, GROUP_ACCOUNT_TYPE_ID, IS_ADDRESS_REQUIRED, AMAZON_APPSTORE_SKU, CREATED_BY, CREATE_DATE, updated_by, update_date) VALUES (1015115892, 'NYTimes: Web + Tablet App', 'Unlimited access to NYTimes.com and the NYTimes tablet app.*', to_date('24-Jul-2013 00:00:00','DD-MON-YY HH24:MI:SS'), to_date('31-Dec-2014 00:00:00','DD-MON-YY HH24:MI:SS'), '0', NULL, '1', '0', '1', (SELECT ID FROM BILLING_SOURCE BS WHERE BS.NAME='Sartre'), decode('NO','IL',1,0), 'NO', '0', '', 'OFFERMAKER', SYSDATE, 'OFFERMAKER', SYSDATE);
END;
DELETE FROM OFFER_CHAIN_ELIGIBILITY WHERE offer_chain_id = 1015115892;
INSERT INTO OFFER_CHAIN_ELIGIBILITY (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (ELG_ID_SEQ.NEXTVAL, 1015115892, 'IS_COMP', '0', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_ELIGIBILITY (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (ELG_ID_SEQ.NEXTVAL, 1015115892, 'MAX_CONCURRENT_SUBS', '1', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_ELIGIBILITY (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (ELG_ID_SEQ.NEXTVAL, 1015115892, 'INTERNAL_ONLY', '0', 'OFFERMAKER', SYSDATE);
DELETE FROM OFFER_CHAIN_META_DATA WHERE offer_chain_id = 1015115892;
INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1015115892, 'BUNDLE_EXPLANATION', 'Web + Tablet 12 wk free, Thereafter $20.00/4 wks', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1015115892, 'PRICE_DESCRIPTION', '12 wks free and then Regular Price $20.00 every 4 weeks', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1015115892, 'PRICE_SHORT_DESCRIPTION', ' BNDL B 12 wk free and then $20.00 / 4 weeks', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1015115892, 'OFFER_TYPE', 'Digital Subscription for 12 weeks free and then full price', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1015115892, 'OFFER_PRICE_DESCRIPTOR', 'RISK FREE TRIAL', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1015115892, 'OFFER_PRICE', 'Get your first 12 weeks free', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1015115892, 'OFFER_PRICE_DETAIL', '($5.00 / week thereafter)', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1015115892, 'PROMO_PRICE_FOOTER_LABEL', 'First 12 weeks', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1015115892, 'ACTUAL_PRICE_FOOTER_LABEL', 'Thereafter', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1015115892, 'BILLING_CYCLE', 'every 4 weeks', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1015115892, 'SUBSCRIBER_TYPE', 'Regular', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1015115892, 'REFUND_POLICY', 'Monthly Billing: No refund.  Users will maintain access for the remainder of the billing period.  Users will not be billed in the next billing cycle.', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1015115892, 'CANCELABLE', '1', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1015115892, 'PRORATED_REFUND_DAYS_LIMIT', '28', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1015115892, 'OPEN_TO_ANONYMOUS', '1', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1015115892, 'BUNDLE', 'Bundle B (Web+Tab)', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1015115892, 'ADX_BUNDLE', 'MM_PROMO', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1015115892, 'SIEBEL_CAMPAIGN_CODE', '3K9WH', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1015115892, 'ANNUAL_PRICE', '260.00', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1015115892, 'UID', 'e6af31696aadb9f7c4832efbc0b42fc215492ac2b3f353fb036c0e7177436434', 'OFFERMAKER', SYSDATE);
DELETE FROM OFFER_CHAIN_NOTIFICATION_TYPE WHERE offer_chain_id = 1015115892;
BEGIN
  SELECT 1 INTO TMP_VAR FROM ACTION WHERE NAME = 'SUBSCRIBE_TO_OFFER_CHAIN';
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    INSERT INTO ACTION (ID, NAME, CREATE_DATE, CREATED_BY) VALUES (ACTION_ID_SEQ.NEXTVAL, 'SUBSCRIBE_TO_OFFER_CHAIN', SYSDATE, 'OFFERMAKER');
END;
BEGIN
  SELECT 1 INTO TMP_VAR FROM CORE_OWNER.NOTIFICATION_TYPE WHERE VALUE = 'sartre-digital-purchase';
EXCEPTION
  WHEN NO_DATA_FOUND THEN NULL;
    INSERT INTO CORE_OWNER.NOTIFICATION_TYPE (ID, VALUE, TEMPLATE_URL) VALUES (CORE_OWNER.NOTTID_SEQ.NEXTVAL, 'sartre-digital-purchase', 'N/A');
END;
BEGIN
  SELECT 1 INTO TMP_VAR FROM ACTION WHERE NAME = 'UPGRADE_SUBSCRIPTION';
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    INSERT INTO ACTION (ID, NAME, CREATE_DATE, CREATED_BY) VALUES (ACTION_ID_SEQ.NEXTVAL, 'UPGRADE_SUBSCRIPTION', SYSDATE, 'OFFERMAKER');
END;
BEGIN
  SELECT 1 INTO TMP_VAR FROM CORE_OWNER.NOTIFICATION_TYPE WHERE VALUE = 'sartre-digital-purchase';
EXCEPTION
  WHEN NO_DATA_FOUND THEN NULL;
    INSERT INTO CORE_OWNER.NOTIFICATION_TYPE (ID, VALUE, TEMPLATE_URL) VALUES (CORE_OWNER.NOTTID_SEQ.NEXTVAL, 'sartre-digital-purchase', 'N/A');
END;
BEGIN
  SELECT 1 INTO TMP_VAR FROM ACTION WHERE NAME = 'CANCEL_SUBSCRIPTION';
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    INSERT INTO ACTION (ID, NAME, CREATE_DATE, CREATED_BY) VALUES (ACTION_ID_SEQ.NEXTVAL, 'CANCEL_SUBSCRIPTION', SYSDATE, 'OFFERMAKER');
END;
BEGIN
  SELECT 1 INTO TMP_VAR FROM CORE_OWNER.NOTIFICATION_TYPE WHERE VALUE = 'sartre-cancel';
EXCEPTION
  WHEN NO_DATA_FOUND THEN NULL;
    INSERT INTO CORE_OWNER.NOTIFICATION_TYPE (ID, VALUE, TEMPLATE_URL) VALUES (CORE_OWNER.NOTTID_SEQ.NEXTVAL, 'sartre-cancel', 'N/A');
END;
BEGIN
  SELECT 1 INTO TMP_VAR FROM ACTION WHERE NAME = 'SYSTEM_CANCEL';
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    INSERT INTO ACTION (ID, NAME, CREATE_DATE, CREATED_BY) VALUES (ACTION_ID_SEQ.NEXTVAL, 'SYSTEM_CANCEL', SYSDATE, 'OFFERMAKER');
END;
BEGIN
  SELECT 1 INTO TMP_VAR FROM CORE_OWNER.NOTIFICATION_TYPE WHERE VALUE = 'sartre-decline';
EXCEPTION
  WHEN NO_DATA_FOUND THEN NULL;
    INSERT INTO CORE_OWNER.NOTIFICATION_TYPE (ID, VALUE, TEMPLATE_URL) VALUES (CORE_OWNER.NOTTID_SEQ.NEXTVAL, 'sartre-decline', 'N/A');
END;
BEGIN
  SELECT 1 INTO TMP_VAR FROM ACTION WHERE NAME = 'CREDIT_CARD_EXP';
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    INSERT INTO ACTION (ID, NAME, CREATE_DATE, CREATED_BY) VALUES (ACTION_ID_SEQ.NEXTVAL, 'CREDIT_CARD_EXP', SYSDATE, 'OFFERMAKER');
END;
BEGIN
  SELECT 1 INTO TMP_VAR FROM CORE_OWNER.NOTIFICATION_TYPE WHERE VALUE = 'card_expiration';
EXCEPTION
  WHEN NO_DATA_FOUND THEN NULL;
    INSERT INTO CORE_OWNER.NOTIFICATION_TYPE (ID, VALUE, TEMPLATE_URL) VALUES (CORE_OWNER.NOTTID_SEQ.NEXTVAL, 'card_expiration', 'N/A');
END;
INSERT INTO OFFER_CHAIN_NOTIFICATION_TYPE (ID, OFFER_CHAIN_ID, NOTIFICATION_TYPE_ID, ACTION_ID, CREATED_BY, CREATE_DATE) VALUES (OCET_ID_SEQ.NEXTVAL, 1015115892, (SELECT ID FROM CORE_OWNER.NOTIFICATION_TYPE WHERE VALUE = 'sartre-digital-purchase'), (SELECT ID FROM ACTION WHERE NAME = 'SUBSCRIBE_TO_OFFER_CHAIN'), 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_NOTIFICATION_TYPE (ID, OFFER_CHAIN_ID, NOTIFICATION_TYPE_ID, ACTION_ID, CREATED_BY, CREATE_DATE) VALUES (OCET_ID_SEQ.NEXTVAL, 1015115892, (SELECT ID FROM CORE_OWNER.NOTIFICATION_TYPE WHERE VALUE = 'sartre-digital-purchase'), (SELECT ID FROM ACTION WHERE NAME = 'UPGRADE_SUBSCRIPTION'), 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_NOTIFICATION_TYPE (ID, OFFER_CHAIN_ID, NOTIFICATION_TYPE_ID, ACTION_ID, CREATED_BY, CREATE_DATE) VALUES (OCET_ID_SEQ.NEXTVAL, 1015115892, (SELECT ID FROM CORE_OWNER.NOTIFICATION_TYPE WHERE VALUE = 'sartre-cancel'), (SELECT ID FROM ACTION WHERE NAME = 'CANCEL_SUBSCRIPTION'), 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_NOTIFICATION_TYPE (ID, OFFER_CHAIN_ID, NOTIFICATION_TYPE_ID, ACTION_ID, CREATED_BY, CREATE_DATE) VALUES (OCET_ID_SEQ.NEXTVAL, 1015115892, (SELECT ID FROM CORE_OWNER.NOTIFICATION_TYPE WHERE VALUE = 'sartre-decline'), (SELECT ID FROM ACTION WHERE NAME = 'SYSTEM_CANCEL'), 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_NOTIFICATION_TYPE (ID, OFFER_CHAIN_ID, NOTIFICATION_TYPE_ID, ACTION_ID, CREATED_BY, CREATE_DATE) VALUES (OCET_ID_SEQ.NEXTVAL, 1015115892, (SELECT ID FROM CORE_OWNER.NOTIFICATION_TYPE WHERE VALUE = 'card_expiration'), (SELECT ID FROM ACTION WHERE NAME = 'CREDIT_CARD_EXP'), 'OFFERMAKER', SYSDATE);
BEGIN
  SELECT 1 INTO TMP_VAR FROM OFFER_OFFER_CHAIN WHERE OFFER_CHAIN_ID = 1015115892 AND INDEX_VALUE = 0 AND ROWNUM <= 1;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
INSERT INTO OFFER (ID, OFFER_STATUS_ID, ENTITLEMENT_DURATION, CREATED_BY, CREATE_DATE, updated_by, update_date) VALUES (OFR_ID_SEQ.NEXTVAL, 1, 'P0Y0M84DT0H0M', 'OFFERMAKER', SYSDATE, 'OFFERMAKER', SYSDATE);
BEGIN
  SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Web' AND ROWNUM <= 1;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    INSERT INTO PRODUCT (ID, NAME, CREATED_BY, CREATE_DATE) VALUES (PRD_ID_SEQ.NEXTVAL, 'Web', 'OFFERMAKER', SYSDATE);
    SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Web' AND ROWNUM <= 1;
  WHEN OTHERS THEN
    RAISE;
END;
INSERT INTO PRODUCT_OFFERING (ID, PRODUCT_ID, TAX_POLICY_TYPE_ID, QUANTITY, UNIT_PRICE, CREATED_BY, CREATE_DATE) VALUES (PO_ID_SEQ.NEXTVAL, CUR_PRD_ID, '1', '84', '0.357143', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_PRODUCT_OFFERING (OFFER_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (OFR_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
INSERT INTO DISCOUNT (ID, NAME, DESCRIPTION, FIXED_AMOUNT, PERCENT_AMOUNT, DISCOUNT_TYPE_ID, CREATED_BY, CREATE_DATE) VALUES (DSC_ID_SEQ.NEXTVAL, 'Discount', 'Off: 0.0. P.Disc: 0.0000. P.Full: 30.0000', '30.00', '0', 1, 'OFFERMAKER', SYSDATE);
INSERT INTO DISCOUNT_PRODUCT_OFFERING (DISCOUNT_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (DSC_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
BEGIN
  SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Mobile' AND ROWNUM <= 1;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    INSERT INTO PRODUCT (ID, NAME, CREATED_BY, CREATE_DATE) VALUES (PRD_ID_SEQ.NEXTVAL, 'Mobile', 'OFFERMAKER', SYSDATE);
    SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Mobile' AND ROWNUM <= 1;
  WHEN OTHERS THEN
    RAISE;
END;
INSERT INTO PRODUCT_OFFERING (ID, PRODUCT_ID, TAX_POLICY_TYPE_ID, QUANTITY, UNIT_PRICE, CREATED_BY, CREATE_DATE) VALUES (PO_ID_SEQ.NEXTVAL, CUR_PRD_ID, '1', '84', '0', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_PRODUCT_OFFERING (OFFER_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (OFR_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
BEGIN
  SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Archive Article' AND ROWNUM <= 1;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    INSERT INTO PRODUCT (ID, NAME, CREATED_BY, CREATE_DATE) VALUES (PRD_ID_SEQ.NEXTVAL, 'Archive Article', 'OFFERMAKER', SYSDATE);
    SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Archive Article' AND ROWNUM <= 1;
  WHEN OTHERS THEN
    RAISE;
END;
INSERT INTO PRODUCT_OFFERING (ID, PRODUCT_ID, TAX_POLICY_TYPE_ID, QUANTITY, UNIT_PRICE, CREATED_BY, CREATE_DATE) VALUES (PO_ID_SEQ.NEXTVAL, CUR_PRD_ID, '1', '300', '0', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_PRODUCT_OFFERING (OFFER_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (OFR_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
BEGIN
  SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'TimesMachine' AND ROWNUM <= 1;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    INSERT INTO PRODUCT (ID, NAME, CREATED_BY, CREATE_DATE) VALUES (PRD_ID_SEQ.NEXTVAL, 'TimesMachine', 'OFFERMAKER', SYSDATE);
    SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'TimesMachine' AND ROWNUM <= 1;
  WHEN OTHERS THEN
    RAISE;
END;
INSERT INTO PRODUCT_OFFERING (ID, PRODUCT_ID, TAX_POLICY_TYPE_ID, QUANTITY, UNIT_PRICE, CREATED_BY, CREATE_DATE) VALUES (PO_ID_SEQ.NEXTVAL, CUR_PRD_ID, '1', '84', '0', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_PRODUCT_OFFERING (OFFER_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (OFR_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
BEGIN
  SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Tablet' AND ROWNUM <= 1;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    INSERT INTO PRODUCT (ID, NAME, CREATED_BY, CREATE_DATE) VALUES (PRD_ID_SEQ.NEXTVAL, 'Tablet', 'OFFERMAKER', SYSDATE);
    SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Tablet' AND ROWNUM <= 1;
  WHEN OTHERS THEN
    RAISE;
END;
INSERT INTO PRODUCT_OFFERING (ID, PRODUCT_ID, TAX_POLICY_TYPE_ID, QUANTITY, UNIT_PRICE, CREATED_BY, CREATE_DATE) VALUES (PO_ID_SEQ.NEXTVAL, CUR_PRD_ID, '1', '84', '0.357143', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_PRODUCT_OFFERING (OFFER_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (OFR_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
INSERT INTO DISCOUNT (ID, NAME, DESCRIPTION, FIXED_AMOUNT, PERCENT_AMOUNT, DISCOUNT_TYPE_ID, CREATED_BY, CREATE_DATE) VALUES (DSC_ID_SEQ.NEXTVAL, 'Discount', 'Off: 0.0. P.Disc: 0.0000. P.Full: 30.0000', '30.00', '0', 1, 'OFFERMAKER', SYSDATE);
INSERT INTO DISCOUNT_PRODUCT_OFFERING (DISCOUNT_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (DSC_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
BEGIN
  SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'TimesReader' AND ROWNUM <= 1;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    INSERT INTO PRODUCT (ID, NAME, CREATED_BY, CREATE_DATE) VALUES (PRD_ID_SEQ.NEXTVAL, 'TimesReader', 'OFFERMAKER', SYSDATE);
    SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'TimesReader' AND ROWNUM <= 1;
  WHEN OTHERS THEN
    RAISE;
END;
INSERT INTO PRODUCT_OFFERING (ID, PRODUCT_ID, TAX_POLICY_TYPE_ID, QUANTITY, UNIT_PRICE, CREATED_BY, CREATE_DATE) VALUES (PO_ID_SEQ.NEXTVAL, CUR_PRD_ID, '1', '84', '0', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_PRODUCT_OFFERING (OFFER_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (OFR_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_OFFER_CHAIN (OFFER_ID, OFFER_CHAIN_ID, INDEX_VALUE, NUM_RECURRENCES, CREATED_BY, CREATE_DATE, updated_by, update_date) VALUES (OFR_ID_SEQ.CURRVAL, 1015115892, '0', '1', 'OFFERMAKER', SYSDATE, 'OFFERMAKER', SYSDATE);
END;
BEGIN
  SELECT 1 INTO TMP_VAR FROM OFFER_OFFER_CHAIN WHERE OFFER_CHAIN_ID = 1015115892 AND INDEX_VALUE = 1 AND ROWNUM <= 1;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
INSERT INTO OFFER (ID, OFFER_STATUS_ID, ENTITLEMENT_DURATION, CREATED_BY, CREATE_DATE, updated_by, update_date) VALUES (OFR_ID_SEQ.NEXTVAL, 1, 'P0Y0M28DT0H0M', 'OFFERMAKER', SYSDATE, 'OFFERMAKER', SYSDATE);
BEGIN
  SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Web' AND ROWNUM <= 1;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    INSERT INTO PRODUCT (ID, NAME, CREATED_BY, CREATE_DATE) VALUES (PRD_ID_SEQ.NEXTVAL, 'Web', 'OFFERMAKER', SYSDATE);
    SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Web' AND ROWNUM <= 1;
  WHEN OTHERS THEN
    RAISE;
END;
INSERT INTO PRODUCT_OFFERING (ID, PRODUCT_ID, TAX_POLICY_TYPE_ID, QUANTITY, UNIT_PRICE, CREATED_BY, CREATE_DATE) VALUES (PO_ID_SEQ.NEXTVAL, CUR_PRD_ID, '1', '28', '0.357143', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_PRODUCT_OFFERING (OFFER_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (OFR_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
BEGIN
  SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Mobile' AND ROWNUM <= 1;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    INSERT INTO PRODUCT (ID, NAME, CREATED_BY, CREATE_DATE) VALUES (PRD_ID_SEQ.NEXTVAL, 'Mobile', 'OFFERMAKER', SYSDATE);
    SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Mobile' AND ROWNUM <= 1;
  WHEN OTHERS THEN
    RAISE;
END;
INSERT INTO PRODUCT_OFFERING (ID, PRODUCT_ID, TAX_POLICY_TYPE_ID, QUANTITY, UNIT_PRICE, CREATED_BY, CREATE_DATE) VALUES (PO_ID_SEQ.NEXTVAL, CUR_PRD_ID, '1', '28', '0', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_PRODUCT_OFFERING (OFFER_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (OFR_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
BEGIN
  SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Archive Article' AND ROWNUM <= 1;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    INSERT INTO PRODUCT (ID, NAME, CREATED_BY, CREATE_DATE) VALUES (PRD_ID_SEQ.NEXTVAL, 'Archive Article', 'OFFERMAKER', SYSDATE);
    SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Archive Article' AND ROWNUM <= 1;
  WHEN OTHERS THEN
    RAISE;
END;
INSERT INTO PRODUCT_OFFERING (ID, PRODUCT_ID, TAX_POLICY_TYPE_ID, QUANTITY, UNIT_PRICE, CREATED_BY, CREATE_DATE) VALUES (PO_ID_SEQ.NEXTVAL, CUR_PRD_ID, '1', '100', '0', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_PRODUCT_OFFERING (OFFER_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (OFR_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
BEGIN
  SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'TimesMachine' AND ROWNUM <= 1;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    INSERT INTO PRODUCT (ID, NAME, CREATED_BY, CREATE_DATE) VALUES (PRD_ID_SEQ.NEXTVAL, 'TimesMachine', 'OFFERMAKER', SYSDATE);
    SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'TimesMachine' AND ROWNUM <= 1;
  WHEN OTHERS THEN
    RAISE;
END;
INSERT INTO PRODUCT_OFFERING (ID, PRODUCT_ID, TAX_POLICY_TYPE_ID, QUANTITY, UNIT_PRICE, CREATED_BY, CREATE_DATE) VALUES (PO_ID_SEQ.NEXTVAL, CUR_PRD_ID, '1', '28', '0', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_PRODUCT_OFFERING (OFFER_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (OFR_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
BEGIN
  SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Tablet' AND ROWNUM <= 1;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    INSERT INTO PRODUCT (ID, NAME, CREATED_BY, CREATE_DATE) VALUES (PRD_ID_SEQ.NEXTVAL, 'Tablet', 'OFFERMAKER', SYSDATE);
    SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Tablet' AND ROWNUM <= 1;
  WHEN OTHERS THEN
    RAISE;
END;
INSERT INTO PRODUCT_OFFERING (ID, PRODUCT_ID, TAX_POLICY_TYPE_ID, QUANTITY, UNIT_PRICE, CREATED_BY, CREATE_DATE) VALUES (PO_ID_SEQ.NEXTVAL, CUR_PRD_ID, '1', '28', '0.357143', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_PRODUCT_OFFERING (OFFER_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (OFR_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
BEGIN
  SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'TimesReader' AND ROWNUM <= 1;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    INSERT INTO PRODUCT (ID, NAME, CREATED_BY, CREATE_DATE) VALUES (PRD_ID_SEQ.NEXTVAL, 'TimesReader', 'OFFERMAKER', SYSDATE);
    SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'TimesReader' AND ROWNUM <= 1;
  WHEN OTHERS THEN
    RAISE;
END;
INSERT INTO PRODUCT_OFFERING (ID, PRODUCT_ID, TAX_POLICY_TYPE_ID, QUANTITY, UNIT_PRICE, CREATED_BY, CREATE_DATE) VALUES (PO_ID_SEQ.NEXTVAL, CUR_PRD_ID, '1', '28', '0', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_PRODUCT_OFFERING (OFFER_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (OFR_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_OFFER_CHAIN (OFFER_ID, OFFER_CHAIN_ID, INDEX_VALUE, NUM_RECURRENCES, CREATED_BY, CREATE_DATE, updated_by, update_date) VALUES (OFR_ID_SEQ.CURRVAL, 1015115892, '1', '-1', 'OFFERMAKER', SYSDATE, 'OFFERMAKER', SYSDATE);
END;
END;
/
COMMIT;
DECLARE
TMP_VAR NUMBER;
CUR_PRD_ID NUMBER;
CUR_CAPABILITY_ID NUMBER;
BEGIN
BEGIN
  SELECT 1 INTO TMP_VAR FROM OFFER_CHAIN WHERE ID = 1723593275 AND ROWNUM <= 1;
  UPDATE OFFER_CHAIN SET NAME='NYTimes: All Digital Access', DESCRIPTION='Unlimited access to NYTimes.com, and the NYTimes smartphone and tablet apps.*', PRODUCT_URI='', VENDOR_SOURCE_ID='1', BILLING_SOURCE_ID=(SELECT ID FROM BILLING_SOURCE BS WHERE BS.NAME='Sartre'), IS_SEAT_LICENSE=0, GROUP_ACCOUNT_TYPE_ID='FL',IS_ADDRESS_REQUIRED=0, OFFER_CHAIN_STATUS_ID = 1, UPDATE_DATE = SYSDATE, UPDATED_BY = 'OFFERMAKER', IS_GIFT_CERTIFICATE='0', REVOKE_ENTITLEMENTS = '0', ADOPTABILITY_WINDOW_START_DATE = to_date('24-Jul-2013 00:00:00','DD-MON-YY HH24:MI:SS'), ADOPTABILITY_WINDOW_END_DATE = to_date('31-Dec-2014 00:00:00','DD-MON-YY HH24:MI:SS'), AMAZON_APPSTORE_SKU=NULL WHERE ID = 1723593275;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    INSERT INTO OFFER_CHAIN (ID, NAME, DESCRIPTION, ADOPTABILITY_WINDOW_START_DATE, ADOPTABILITY_WINDOW_END_DATE, IS_GIFT_CERTIFICATE, PRODUCT_URI, OFFER_CHAIN_STATUS_ID, REVOKE_ENTITLEMENTS, VENDOR_SOURCE_ID, BILLING_SOURCE_ID, IS_SEAT_LICENSE, GROUP_ACCOUNT_TYPE_ID, IS_ADDRESS_REQUIRED, AMAZON_APPSTORE_SKU, CREATED_BY, CREATE_DATE, updated_by, update_date) VALUES (1723593275, 'NYTimes: All Digital Access', 'Unlimited access to NYTimes.com, and the NYTimes smartphone and tablet apps.*', to_date('24-Jul-2013 00:00:00','DD-MON-YY HH24:MI:SS'), to_date('31-Dec-2014 00:00:00','DD-MON-YY HH24:MI:SS'), '0', NULL, '1', '0', '1', (SELECT ID FROM BILLING_SOURCE BS WHERE BS.NAME='Sartre'), decode('FL','IL',1,0), 'FL', '0', '', 'OFFERMAKER', SYSDATE, 'OFFERMAKER', SYSDATE);
END;
DELETE FROM OFFER_CHAIN_ELIGIBILITY WHERE offer_chain_id = 1723593275;
INSERT INTO OFFER_CHAIN_ELIGIBILITY (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (ELG_ID_SEQ.NEXTVAL, 1723593275, 'IS_COMP', '0', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_ELIGIBILITY (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (ELG_ID_SEQ.NEXTVAL, 1723593275, 'MAX_CONCURRENT_SUBS', '1', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_ELIGIBILITY (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (ELG_ID_SEQ.NEXTVAL, 1723593275, 'INTERNAL_ONLY', '0', 'OFFERMAKER', SYSDATE);
DELETE FROM OFFER_CHAIN_META_DATA WHERE offer_chain_id = 1723593275;
INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1723593275, 'BUNDLE_EXPLANATION', 'Web + Smartphone + Tablet 12 wk free, Thereafter $35.00/4 wks', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1723593275, 'PRICE_DESCRIPTION', '12 wks free and then Regular Price $35.00 every 4 weeks', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1723593275, 'PRICE_SHORT_DESCRIPTION', ' BNDL D 12 wk free and then $35.00 / 4 weeks', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1723593275, 'OFFER_TYPE', 'Digital Subscription for 12 weeks free and then full price', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1723593275, 'OFFER_PRICE_DESCRIPTOR', 'RISK FREE TRIAL', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1723593275, 'OFFER_PRICE', 'Get your first 12 weeks free', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1723593275, 'OFFER_PRICE_DETAIL', '($8.75 / week thereafter)', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1723593275, 'PROMO_PRICE_FOOTER_LABEL', 'First 12 weeks', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1723593275, 'ACTUAL_PRICE_FOOTER_LABEL', 'Thereafter', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1723593275, 'BILLING_CYCLE', 'every 4 weeks', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1723593275, 'SUBSCRIBER_TYPE', 'Regular', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1723593275, 'REFUND_POLICY', 'Monthly Billing: No refund.  Users will maintain access for the remainder of the billing period.  Users will not be billed in the next billing cycle.', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1723593275, 'CANCELABLE', '1', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1723593275, 'PRORATED_REFUND_DAYS_LIMIT', '28', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1723593275, 'OPEN_TO_ANONYMOUS', '1', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1723593275, 'BUNDLE', 'Bundle D (Digital All Access)', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1723593275, 'ADX_BUNDLE', 'MM_PROMO', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1723593275, 'SIEBEL_CAMPAIGN_CODE', '3K9WH', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1723593275, 'ANNUAL_PRICE', '455.00', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_META_DATA (ID, OFFER_CHAIN_ID, NAME, VALUE, CREATED_BY, CREATE_DATE) VALUES (OCMD_ID_SEQ.NEXTVAL, 1723593275, 'UID', 'f88b5b0f016da505622230a6230aa7810bffbf40e3eaaa91c6a3ed6405aaeba6', 'OFFERMAKER', SYSDATE);
DELETE FROM OFFER_CHAIN_NOTIFICATION_TYPE WHERE offer_chain_id = 1723593275;
BEGIN
  SELECT 1 INTO TMP_VAR FROM ACTION WHERE NAME = 'SUBSCRIBE_TO_OFFER_CHAIN';
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    INSERT INTO ACTION (ID, NAME, CREATE_DATE, CREATED_BY) VALUES (ACTION_ID_SEQ.NEXTVAL, 'SUBSCRIBE_TO_OFFER_CHAIN', SYSDATE, 'OFFERMAKER');
END;
BEGIN
  SELECT 1 INTO TMP_VAR FROM CORE_OWNER.NOTIFICATION_TYPE WHERE VALUE = 'sartre-digital-purchase';
EXCEPTION
  WHEN NO_DATA_FOUND THEN NULL;
    INSERT INTO CORE_OWNER.NOTIFICATION_TYPE (ID, VALUE, TEMPLATE_URL) VALUES (CORE_OWNER.NOTTID_SEQ.NEXTVAL, 'sartre-digital-purchase', 'N/A');
END;
BEGIN
  SELECT 1 INTO TMP_VAR FROM ACTION WHERE NAME = 'UPGRADE_SUBSCRIPTION';
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    INSERT INTO ACTION (ID, NAME, CREATE_DATE, CREATED_BY) VALUES (ACTION_ID_SEQ.NEXTVAL, 'UPGRADE_SUBSCRIPTION', SYSDATE, 'OFFERMAKER');
END;
BEGIN
  SELECT 1 INTO TMP_VAR FROM CORE_OWNER.NOTIFICATION_TYPE WHERE VALUE = 'sartre-digital-purchase';
EXCEPTION
  WHEN NO_DATA_FOUND THEN NULL;
    INSERT INTO CORE_OWNER.NOTIFICATION_TYPE (ID, VALUE, TEMPLATE_URL) VALUES (CORE_OWNER.NOTTID_SEQ.NEXTVAL, 'sartre-digital-purchase', 'N/A');
END;
BEGIN
  SELECT 1 INTO TMP_VAR FROM ACTION WHERE NAME = 'CANCEL_SUBSCRIPTION';
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    INSERT INTO ACTION (ID, NAME, CREATE_DATE, CREATED_BY) VALUES (ACTION_ID_SEQ.NEXTVAL, 'CANCEL_SUBSCRIPTION', SYSDATE, 'OFFERMAKER');
END;
BEGIN
  SELECT 1 INTO TMP_VAR FROM CORE_OWNER.NOTIFICATION_TYPE WHERE VALUE = 'sartre-cancel';
EXCEPTION
  WHEN NO_DATA_FOUND THEN NULL;
    INSERT INTO CORE_OWNER.NOTIFICATION_TYPE (ID, VALUE, TEMPLATE_URL) VALUES (CORE_OWNER.NOTTID_SEQ.NEXTVAL, 'sartre-cancel', 'N/A');
END;
BEGIN
  SELECT 1 INTO TMP_VAR FROM ACTION WHERE NAME = 'SYSTEM_CANCEL';
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    INSERT INTO ACTION (ID, NAME, CREATE_DATE, CREATED_BY) VALUES (ACTION_ID_SEQ.NEXTVAL, 'SYSTEM_CANCEL', SYSDATE, 'OFFERMAKER');
END;
BEGIN
  SELECT 1 INTO TMP_VAR FROM CORE_OWNER.NOTIFICATION_TYPE WHERE VALUE = 'sartre-decline';
EXCEPTION
  WHEN NO_DATA_FOUND THEN NULL;
    INSERT INTO CORE_OWNER.NOTIFICATION_TYPE (ID, VALUE, TEMPLATE_URL) VALUES (CORE_OWNER.NOTTID_SEQ.NEXTVAL, 'sartre-decline', 'N/A');
END;
BEGIN
  SELECT 1 INTO TMP_VAR FROM ACTION WHERE NAME = 'CREDIT_CARD_EXP';
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    INSERT INTO ACTION (ID, NAME, CREATE_DATE, CREATED_BY) VALUES (ACTION_ID_SEQ.NEXTVAL, 'CREDIT_CARD_EXP', SYSDATE, 'OFFERMAKER');
END;
BEGIN
  SELECT 1 INTO TMP_VAR FROM CORE_OWNER.NOTIFICATION_TYPE WHERE VALUE = 'card_expiration';
EXCEPTION
  WHEN NO_DATA_FOUND THEN NULL;
    INSERT INTO CORE_OWNER.NOTIFICATION_TYPE (ID, VALUE, TEMPLATE_URL) VALUES (CORE_OWNER.NOTTID_SEQ.NEXTVAL, 'card_expiration', 'N/A');
END;
BEGIN
  SELECT 1 INTO TMP_VAR FROM ACTION WHERE NAME = 'FAMILY_PLAN_OWNER_ADD';
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    INSERT INTO ACTION (ID, NAME, CREATE_DATE, CREATED_BY) VALUES (ACTION_ID_SEQ.NEXTVAL, 'FAMILY_PLAN_OWNER_ADD', SYSDATE, 'OFFERMAKER');
END;
BEGIN
  SELECT 1 INTO TMP_VAR FROM CORE_OWNER.NOTIFICATION_TYPE WHERE VALUE = 'family-plan-welcome';
EXCEPTION
  WHEN NO_DATA_FOUND THEN NULL;
    INSERT INTO CORE_OWNER.NOTIFICATION_TYPE (ID, VALUE, TEMPLATE_URL) VALUES (CORE_OWNER.NOTTID_SEQ.NEXTVAL, 'family-plan-welcome', 'N/A');
END;
BEGIN
  SELECT 1 INTO TMP_VAR FROM ACTION WHERE NAME = 'FAMILY_PLAN_OWNER_EXPIRE';
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    INSERT INTO ACTION (ID, NAME, CREATE_DATE, CREATED_BY) VALUES (ACTION_ID_SEQ.NEXTVAL, 'FAMILY_PLAN_OWNER_EXPIRE', SYSDATE, 'OFFERMAKER');
END;
BEGIN
  SELECT 1 INTO TMP_VAR FROM CORE_OWNER.NOTIFICATION_TYPE WHERE VALUE = 'family-plan-child-remove';
EXCEPTION
  WHEN NO_DATA_FOUND THEN NULL;
    INSERT INTO CORE_OWNER.NOTIFICATION_TYPE (ID, VALUE, TEMPLATE_URL) VALUES (CORE_OWNER.NOTTID_SEQ.NEXTVAL, 'family-plan-child-remove', 'N/A');
END;
BEGIN
  SELECT 1 INTO TMP_VAR FROM ACTION WHERE NAME = 'FAMILY_PLAN_OWNER_INVITE';
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    INSERT INTO ACTION (ID, NAME, CREATE_DATE, CREATED_BY) VALUES (ACTION_ID_SEQ.NEXTVAL, 'FAMILY_PLAN_OWNER_INVITE', SYSDATE, 'OFFERMAKER');
END;
BEGIN
  SELECT 1 INTO TMP_VAR FROM CORE_OWNER.NOTIFICATION_TYPE WHERE VALUE = 'family-plan-child-invite';
EXCEPTION
  WHEN NO_DATA_FOUND THEN NULL;
    INSERT INTO CORE_OWNER.NOTIFICATION_TYPE (ID, VALUE, TEMPLATE_URL) VALUES (CORE_OWNER.NOTTID_SEQ.NEXTVAL, 'family-plan-child-invite', 'N/A');
END;
BEGIN
  SELECT 1 INTO TMP_VAR FROM ACTION WHERE NAME = 'FAMILY_PLAN_BORROWER_EXPIRE';
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    INSERT INTO ACTION (ID, NAME, CREATE_DATE, CREATED_BY) VALUES (ACTION_ID_SEQ.NEXTVAL, 'FAMILY_PLAN_BORROWER_EXPIRE', SYSDATE, 'OFFERMAKER');
END;
BEGIN
  SELECT 1 INTO TMP_VAR FROM CORE_OWNER.NOTIFICATION_TYPE WHERE VALUE = 'family-plan-parent-remove';
EXCEPTION
  WHEN NO_DATA_FOUND THEN NULL;
    INSERT INTO CORE_OWNER.NOTIFICATION_TYPE (ID, VALUE, TEMPLATE_URL) VALUES (CORE_OWNER.NOTTID_SEQ.NEXTVAL, 'family-plan-parent-remove', 'N/A');
END;
INSERT INTO OFFER_CHAIN_NOTIFICATION_TYPE (ID, OFFER_CHAIN_ID, NOTIFICATION_TYPE_ID, ACTION_ID, CREATED_BY, CREATE_DATE) VALUES (OCET_ID_SEQ.NEXTVAL, 1723593275, (SELECT ID FROM CORE_OWNER.NOTIFICATION_TYPE WHERE VALUE = 'sartre-digital-purchase'), (SELECT ID FROM ACTION WHERE NAME = 'SUBSCRIBE_TO_OFFER_CHAIN'), 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_NOTIFICATION_TYPE (ID, OFFER_CHAIN_ID, NOTIFICATION_TYPE_ID, ACTION_ID, CREATED_BY, CREATE_DATE) VALUES (OCET_ID_SEQ.NEXTVAL, 1723593275, (SELECT ID FROM CORE_OWNER.NOTIFICATION_TYPE WHERE VALUE = 'sartre-digital-purchase'), (SELECT ID FROM ACTION WHERE NAME = 'UPGRADE_SUBSCRIPTION'), 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_NOTIFICATION_TYPE (ID, OFFER_CHAIN_ID, NOTIFICATION_TYPE_ID, ACTION_ID, CREATED_BY, CREATE_DATE) VALUES (OCET_ID_SEQ.NEXTVAL, 1723593275, (SELECT ID FROM CORE_OWNER.NOTIFICATION_TYPE WHERE VALUE = 'sartre-cancel'), (SELECT ID FROM ACTION WHERE NAME = 'CANCEL_SUBSCRIPTION'), 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_NOTIFICATION_TYPE (ID, OFFER_CHAIN_ID, NOTIFICATION_TYPE_ID, ACTION_ID, CREATED_BY, CREATE_DATE) VALUES (OCET_ID_SEQ.NEXTVAL, 1723593275, (SELECT ID FROM CORE_OWNER.NOTIFICATION_TYPE WHERE VALUE = 'sartre-decline'), (SELECT ID FROM ACTION WHERE NAME = 'SYSTEM_CANCEL'), 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_NOTIFICATION_TYPE (ID, OFFER_CHAIN_ID, NOTIFICATION_TYPE_ID, ACTION_ID, CREATED_BY, CREATE_DATE) VALUES (OCET_ID_SEQ.NEXTVAL, 1723593275, (SELECT ID FROM CORE_OWNER.NOTIFICATION_TYPE WHERE VALUE = 'card_expiration'), (SELECT ID FROM ACTION WHERE NAME = 'CREDIT_CARD_EXP'), 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_NOTIFICATION_TYPE (ID, OFFER_CHAIN_ID, NOTIFICATION_TYPE_ID, ACTION_ID, CREATED_BY, CREATE_DATE) VALUES (OCET_ID_SEQ.NEXTVAL, 1723593275, (SELECT ID FROM CORE_OWNER.NOTIFICATION_TYPE WHERE VALUE = 'family-plan-welcome'), (SELECT ID FROM ACTION WHERE NAME = 'FAMILY_PLAN_OWNER_ADD'), 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_NOTIFICATION_TYPE (ID, OFFER_CHAIN_ID, NOTIFICATION_TYPE_ID, ACTION_ID, CREATED_BY, CREATE_DATE) VALUES (OCET_ID_SEQ.NEXTVAL, 1723593275, (SELECT ID FROM CORE_OWNER.NOTIFICATION_TYPE WHERE VALUE = 'family-plan-child-remove'), (SELECT ID FROM ACTION WHERE NAME = 'FAMILY_PLAN_OWNER_EXPIRE'), 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_NOTIFICATION_TYPE (ID, OFFER_CHAIN_ID, NOTIFICATION_TYPE_ID, ACTION_ID, CREATED_BY, CREATE_DATE) VALUES (OCET_ID_SEQ.NEXTVAL, 1723593275, (SELECT ID FROM CORE_OWNER.NOTIFICATION_TYPE WHERE VALUE = 'family-plan-child-invite'), (SELECT ID FROM ACTION WHERE NAME = 'FAMILY_PLAN_OWNER_INVITE'), 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_CHAIN_NOTIFICATION_TYPE (ID, OFFER_CHAIN_ID, NOTIFICATION_TYPE_ID, ACTION_ID, CREATED_BY, CREATE_DATE) VALUES (OCET_ID_SEQ.NEXTVAL, 1723593275, (SELECT ID FROM CORE_OWNER.NOTIFICATION_TYPE WHERE VALUE = 'family-plan-parent-remove'), (SELECT ID FROM ACTION WHERE NAME = 'FAMILY_PLAN_BORROWER_EXPIRE'), 'OFFERMAKER', SYSDATE);
BEGIN
  SELECT 1 INTO TMP_VAR FROM OFFER_OFFER_CHAIN WHERE OFFER_CHAIN_ID = 1723593275 AND INDEX_VALUE = 0 AND ROWNUM <= 1;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
INSERT INTO OFFER (ID, OFFER_STATUS_ID, ENTITLEMENT_DURATION, CREATED_BY, CREATE_DATE, updated_by, update_date) VALUES (OFR_ID_SEQ.NEXTVAL, 1, 'P0Y0M84DT0H0M', 'OFFERMAKER', SYSDATE, 'OFFERMAKER', SYSDATE);
BEGIN
  SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Web' AND ROWNUM <= 1;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    INSERT INTO PRODUCT (ID, NAME, CREATED_BY, CREATE_DATE) VALUES (PRD_ID_SEQ.NEXTVAL, 'Web', 'OFFERMAKER', SYSDATE);
    SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Web' AND ROWNUM <= 1;
  WHEN OTHERS THEN
    RAISE;
END;
INSERT INTO PRODUCT_OFFERING (ID, PRODUCT_ID, TAX_POLICY_TYPE_ID, QUANTITY, UNIT_PRICE, CREATED_BY, CREATE_DATE) VALUES (PO_ID_SEQ.NEXTVAL, CUR_PRD_ID, '1', '84', '0.357143', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_PRODUCT_OFFERING (OFFER_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (OFR_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
INSERT INTO DISCOUNT (ID, NAME, DESCRIPTION, FIXED_AMOUNT, PERCENT_AMOUNT, DISCOUNT_TYPE_ID, CREATED_BY, CREATE_DATE) VALUES (DSC_ID_SEQ.NEXTVAL, 'Discount', 'Off: 0.0. P.Disc: 0.0000. P.Full: 30.0000', '30.00', '0', 1, 'OFFERMAKER', SYSDATE);
INSERT INTO DISCOUNT_PRODUCT_OFFERING (DISCOUNT_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (DSC_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
BEGIN
  SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Mobile' AND ROWNUM <= 1;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    INSERT INTO PRODUCT (ID, NAME, CREATED_BY, CREATE_DATE) VALUES (PRD_ID_SEQ.NEXTVAL, 'Mobile', 'OFFERMAKER', SYSDATE);
    SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Mobile' AND ROWNUM <= 1;
  WHEN OTHERS THEN
    RAISE;
END;
INSERT INTO PRODUCT_OFFERING (ID, PRODUCT_ID, TAX_POLICY_TYPE_ID, QUANTITY, UNIT_PRICE, CREATED_BY, CREATE_DATE) VALUES (PO_ID_SEQ.NEXTVAL, CUR_PRD_ID, '1', '84', '0', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_PRODUCT_OFFERING (OFFER_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (OFR_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
BEGIN
  SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Archive Article' AND ROWNUM <= 1;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    INSERT INTO PRODUCT (ID, NAME, CREATED_BY, CREATE_DATE) VALUES (PRD_ID_SEQ.NEXTVAL, 'Archive Article', 'OFFERMAKER', SYSDATE);
    SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Archive Article' AND ROWNUM <= 1;
  WHEN OTHERS THEN
    RAISE;
END;
INSERT INTO PRODUCT_OFFERING (ID, PRODUCT_ID, TAX_POLICY_TYPE_ID, QUANTITY, UNIT_PRICE, CREATED_BY, CREATE_DATE) VALUES (PO_ID_SEQ.NEXTVAL, CUR_PRD_ID, '1', '300', '0', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_PRODUCT_OFFERING (OFFER_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (OFR_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
BEGIN
  SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'TimesMachine' AND ROWNUM <= 1;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    INSERT INTO PRODUCT (ID, NAME, CREATED_BY, CREATE_DATE) VALUES (PRD_ID_SEQ.NEXTVAL, 'TimesMachine', 'OFFERMAKER', SYSDATE);
    SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'TimesMachine' AND ROWNUM <= 1;
  WHEN OTHERS THEN
    RAISE;
END;
INSERT INTO PRODUCT_OFFERING (ID, PRODUCT_ID, TAX_POLICY_TYPE_ID, QUANTITY, UNIT_PRICE, CREATED_BY, CREATE_DATE) VALUES (PO_ID_SEQ.NEXTVAL, CUR_PRD_ID, '1', '84', '0', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_PRODUCT_OFFERING (OFFER_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (OFR_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
BEGIN
  SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Smartphone' AND ROWNUM <= 1;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    INSERT INTO PRODUCT (ID, NAME, CREATED_BY, CREATE_DATE) VALUES (PRD_ID_SEQ.NEXTVAL, 'Smartphone', 'OFFERMAKER', SYSDATE);
    SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Smartphone' AND ROWNUM <= 1;
  WHEN OTHERS THEN
    RAISE;
END;
INSERT INTO PRODUCT_OFFERING (ID, PRODUCT_ID, TAX_POLICY_TYPE_ID, QUANTITY, UNIT_PRICE, CREATED_BY, CREATE_DATE) VALUES (PO_ID_SEQ.NEXTVAL, CUR_PRD_ID, '1', '84', '0.178571', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_PRODUCT_OFFERING (OFFER_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (OFR_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
INSERT INTO DISCOUNT (ID, NAME, DESCRIPTION, FIXED_AMOUNT, PERCENT_AMOUNT, DISCOUNT_TYPE_ID, CREATED_BY, CREATE_DATE) VALUES (DSC_ID_SEQ.NEXTVAL, 'Discount', 'Off: 0.0. P.Disc: 0.0000. P.Full: 15.0000', '15.00', '0', 1, 'OFFERMAKER', SYSDATE);
INSERT INTO DISCOUNT_PRODUCT_OFFERING (DISCOUNT_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (DSC_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
BEGIN
  SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Tablet' AND ROWNUM <= 1;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    INSERT INTO PRODUCT (ID, NAME, CREATED_BY, CREATE_DATE) VALUES (PRD_ID_SEQ.NEXTVAL, 'Tablet', 'OFFERMAKER', SYSDATE);
    SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Tablet' AND ROWNUM <= 1;
  WHEN OTHERS THEN
    RAISE;
END;
INSERT INTO PRODUCT_OFFERING (ID, PRODUCT_ID, TAX_POLICY_TYPE_ID, QUANTITY, UNIT_PRICE, CREATED_BY, CREATE_DATE) VALUES (PO_ID_SEQ.NEXTVAL, CUR_PRD_ID, '1', '84', '0.714286', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_PRODUCT_OFFERING (OFFER_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (OFR_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
INSERT INTO DISCOUNT (ID, NAME, DESCRIPTION, FIXED_AMOUNT, PERCENT_AMOUNT, DISCOUNT_TYPE_ID, CREATED_BY, CREATE_DATE) VALUES (DSC_ID_SEQ.NEXTVAL, 'Discount', 'Off: 0.0. P.Disc: 0.0000. P.Full: 60.0000', '60.00', '0', 1, 'OFFERMAKER', SYSDATE);
INSERT INTO DISCOUNT_PRODUCT_OFFERING (DISCOUNT_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (DSC_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
BEGIN
  SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'TimesReader' AND ROWNUM <= 1;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    INSERT INTO PRODUCT (ID, NAME, CREATED_BY, CREATE_DATE) VALUES (PRD_ID_SEQ.NEXTVAL, 'TimesReader', 'OFFERMAKER', SYSDATE);
    SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'TimesReader' AND ROWNUM <= 1;
  WHEN OTHERS THEN
    RAISE;
END;
INSERT INTO PRODUCT_OFFERING (ID, PRODUCT_ID, TAX_POLICY_TYPE_ID, QUANTITY, UNIT_PRICE, CREATED_BY, CREATE_DATE) VALUES (PO_ID_SEQ.NEXTVAL, CUR_PRD_ID, '1', '84', '0', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_PRODUCT_OFFERING (OFFER_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (OFR_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_OFFER_CHAIN (OFFER_ID, OFFER_CHAIN_ID, INDEX_VALUE, NUM_RECURRENCES, CREATED_BY, CREATE_DATE, updated_by, update_date) VALUES (OFR_ID_SEQ.CURRVAL, 1723593275, '0', '1', 'OFFERMAKER', SYSDATE, 'OFFERMAKER', SYSDATE);
END;
BEGIN
  SELECT 1 INTO TMP_VAR FROM OFFER_OFFER_CHAIN WHERE OFFER_CHAIN_ID = 1723593275 AND INDEX_VALUE = 1 AND ROWNUM <= 1;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
INSERT INTO OFFER (ID, OFFER_STATUS_ID, ENTITLEMENT_DURATION, CREATED_BY, CREATE_DATE, updated_by, update_date) VALUES (OFR_ID_SEQ.NEXTVAL, 1, 'P0Y0M28DT0H0M', 'OFFERMAKER', SYSDATE, 'OFFERMAKER', SYSDATE);
BEGIN
  SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Web' AND ROWNUM <= 1;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    INSERT INTO PRODUCT (ID, NAME, CREATED_BY, CREATE_DATE) VALUES (PRD_ID_SEQ.NEXTVAL, 'Web', 'OFFERMAKER', SYSDATE);
    SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Web' AND ROWNUM <= 1;
  WHEN OTHERS THEN
    RAISE;
END;
INSERT INTO PRODUCT_OFFERING (ID, PRODUCT_ID, TAX_POLICY_TYPE_ID, QUANTITY, UNIT_PRICE, CREATED_BY, CREATE_DATE) VALUES (PO_ID_SEQ.NEXTVAL, CUR_PRD_ID, '1', '28', '0.357143', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_PRODUCT_OFFERING (OFFER_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (OFR_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
BEGIN
  SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Mobile' AND ROWNUM <= 1;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    INSERT INTO PRODUCT (ID, NAME, CREATED_BY, CREATE_DATE) VALUES (PRD_ID_SEQ.NEXTVAL, 'Mobile', 'OFFERMAKER', SYSDATE);
    SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Mobile' AND ROWNUM <= 1;
  WHEN OTHERS THEN
    RAISE;
END;
INSERT INTO PRODUCT_OFFERING (ID, PRODUCT_ID, TAX_POLICY_TYPE_ID, QUANTITY, UNIT_PRICE, CREATED_BY, CREATE_DATE) VALUES (PO_ID_SEQ.NEXTVAL, CUR_PRD_ID, '1', '28', '0', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_PRODUCT_OFFERING (OFFER_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (OFR_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
BEGIN
  SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Archive Article' AND ROWNUM <= 1;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    INSERT INTO PRODUCT (ID, NAME, CREATED_BY, CREATE_DATE) VALUES (PRD_ID_SEQ.NEXTVAL, 'Archive Article', 'OFFERMAKER', SYSDATE);
    SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Archive Article' AND ROWNUM <= 1;
  WHEN OTHERS THEN
    RAISE;
END;
INSERT INTO PRODUCT_OFFERING (ID, PRODUCT_ID, TAX_POLICY_TYPE_ID, QUANTITY, UNIT_PRICE, CREATED_BY, CREATE_DATE) VALUES (PO_ID_SEQ.NEXTVAL, CUR_PRD_ID, '1', '100', '0', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_PRODUCT_OFFERING (OFFER_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (OFR_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
BEGIN
  SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'TimesMachine' AND ROWNUM <= 1;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    INSERT INTO PRODUCT (ID, NAME, CREATED_BY, CREATE_DATE) VALUES (PRD_ID_SEQ.NEXTVAL, 'TimesMachine', 'OFFERMAKER', SYSDATE);
    SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'TimesMachine' AND ROWNUM <= 1;
  WHEN OTHERS THEN
    RAISE;
END;
INSERT INTO PRODUCT_OFFERING (ID, PRODUCT_ID, TAX_POLICY_TYPE_ID, QUANTITY, UNIT_PRICE, CREATED_BY, CREATE_DATE) VALUES (PO_ID_SEQ.NEXTVAL, CUR_PRD_ID, '1', '28', '0', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_PRODUCT_OFFERING (OFFER_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (OFR_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
BEGIN
  SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Smartphone' AND ROWNUM <= 1;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    INSERT INTO PRODUCT (ID, NAME, CREATED_BY, CREATE_DATE) VALUES (PRD_ID_SEQ.NEXTVAL, 'Smartphone', 'OFFERMAKER', SYSDATE);
    SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Smartphone' AND ROWNUM <= 1;
  WHEN OTHERS THEN
    RAISE;
END;
INSERT INTO PRODUCT_OFFERING (ID, PRODUCT_ID, TAX_POLICY_TYPE_ID, QUANTITY, UNIT_PRICE, CREATED_BY, CREATE_DATE) VALUES (PO_ID_SEQ.NEXTVAL, CUR_PRD_ID, '1', '28', '0.178571', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_PRODUCT_OFFERING (OFFER_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (OFR_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
BEGIN
  SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Tablet' AND ROWNUM <= 1;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    INSERT INTO PRODUCT (ID, NAME, CREATED_BY, CREATE_DATE) VALUES (PRD_ID_SEQ.NEXTVAL, 'Tablet', 'OFFERMAKER', SYSDATE);
    SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'Tablet' AND ROWNUM <= 1;
  WHEN OTHERS THEN
    RAISE;
END;
INSERT INTO PRODUCT_OFFERING (ID, PRODUCT_ID, TAX_POLICY_TYPE_ID, QUANTITY, UNIT_PRICE, CREATED_BY, CREATE_DATE) VALUES (PO_ID_SEQ.NEXTVAL, CUR_PRD_ID, '1', '28', '0.714286', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_PRODUCT_OFFERING (OFFER_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (OFR_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
BEGIN
  SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'TimesReader' AND ROWNUM <= 1;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    INSERT INTO PRODUCT (ID, NAME, CREATED_BY, CREATE_DATE) VALUES (PRD_ID_SEQ.NEXTVAL, 'TimesReader', 'OFFERMAKER', SYSDATE);
    SELECT ID INTO CUR_PRD_ID FROM PRODUCT WHERE NAME = 'TimesReader' AND ROWNUM <= 1;
  WHEN OTHERS THEN
    RAISE;
END;
INSERT INTO PRODUCT_OFFERING (ID, PRODUCT_ID, TAX_POLICY_TYPE_ID, QUANTITY, UNIT_PRICE, CREATED_BY, CREATE_DATE) VALUES (PO_ID_SEQ.NEXTVAL, CUR_PRD_ID, '1', '28', '0', 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_PRODUCT_OFFERING (OFFER_ID, PRODUCT_OFFERING_ID, CREATED_BY, CREATE_DATE) VALUES (OFR_ID_SEQ.CURRVAL, PO_ID_SEQ.CURRVAL, 'OFFERMAKER', SYSDATE);
INSERT INTO OFFER_OFFER_CHAIN (OFFER_ID, OFFER_CHAIN_ID, INDEX_VALUE, NUM_RECURRENCES, CREATED_BY, CREATE_DATE, updated_by, update_date) VALUES (OFR_ID_SEQ.CURRVAL, 1723593275, '1', '-1', 'OFFERMAKER', SYSDATE, 'OFFERMAKER', SYSDATE);
END;
END;
/
COMMIT;

