WHENEVER SQLERROR EXIT ROLLBACK;

UPDATE
  CORE_OWNER.TRANSACTION
SET
  TRANSACTION_TYPE_CODE = 'GIFT_CERTIFICATE_PURCHASE',
  UPDATED_BY = 'JIRA-SAR-434',
  UPDATE_DATE = SYSDATE
WHERE
  ID IN
  (
    SELECT
      CORE_OWNER.TRANSACTION.ID
    FROM
      CORE_OWNER.GIFT_CERTIFICATE
    INNER JOIN CORE_OWNER.CHARGE
    ON
      CORE_OWNER.GIFT_CERTIFICATE.PURCHASE_INVOICE_ID =
      CORE_OWNER.CHARGE.INVOICE_ID
    INNER JOIN CORE_OWNER.TRANSACTION
    ON
      CORE_OWNER.CHARGE.TRANSACTION_ID = CORE_OWNER.TRANSACTION.ID
    WHERE
      Core_Owner.Transaction.Transaction_Type_Code LIKE 'RECURRING_%'
  );
COMMIT;




