

Drop MATERIALIZED VIEW LOG ON "CORE_OWNER"."ACCOUNT";

 CREATE MATERIALIZED VIEW LOG ON "CORE_OWNER"."ACCOUNT" PCTFREE 10 PCTUSED 30 INITRANS 1 MAXTRANS 255 LOGGING STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "CORE"
WITH PRIMARY KEY EXCLUDING NEW VALUES;