WHENEVER SQLERROR EXIT ROLLBACK;

UPDATE CREDIT_CARD
SET CREDIT_CARD_STATUS_ID = 1,
UPDATED_BY = 'bugzilla-78909',
UPDATE_DATE = SYSDATE
WHERE ID IN ( 
  SELECT cc.ID
  FROM CREDIT_CARD cc, SUBSCRIPTION s
  WHERE cc.UPDATED_BY = 'report-poller'
  AND cc.CREDIT_CARD_STATUS_ID = 3
  AND cc.ID = s.INSTRUMENT_ID
  AND cc.ACCOUNT_ID = s.ACCOUNT_ID
  AND s.SUBSCRIPTION_STATUS_ID = 1
);

COMMIT;

